/*
use chium;

ALTER TABLE BUSINESS_AREA
ADD CONSTRAINT BusinessAreaSiteID
FOREIGN KEY(SITE_ID)
REFERENCES COMP_SITE(ID);

ALTER TABLE BUSINESS_AREA
ADD CONSTRAINT BusinessAreaBcode
FOREIGN KEY(KIKCD_B_CODE)
REFERENCES KIKCD_B(B_CODE);

ALTER TABLE BIDDING_DETAILS
ADD CONSTRAINT BiddingDetailsTrmtCode
FOREIGN KEY(TRMT_CODE)
REFERENCES WSTE_TRMT_METHOD(CODE);

ALTER TABLE BIDDING_DETAILS
ADD CONSTRAINT BiddingDetailsWsteCode
FOREIGN KEY(WSTE_CODE)
REFERENCES WSTE_CODE(CODE);

ALTER TABLE BIDDING_DETAILS
ADD CONSTRAINT BiddingDetailsCollectorBiddingId
FOREIGN KEY(COLLECTOR_BIDDING_ID)
REFERENCES COLLECTOR_BIDDING(ID);

ALTER TABLE CHAT_ROOMS
ADD CONSTRAINT ChatRoomsOrderId
FOREIGN KEY(ORDER_ID)
REFERENCES SITE_WSTE_DISPOSAL_ORDER(ID);

ALTER TABLE CHAT_ROOMS
ADD CONSTRAINT ChatRoomsBiddingId
FOREIGN KEY(BIDDING_ID)
REFERENCES COLLECTOR_BIDDING(ID);

ALTER TABLE TRANSACTION_REPORT
ADD CONSTRAINT TransactionReportTransactionId
FOREIGN KEY(TRANSACTION_ID)
REFERENCES WSTE_CLCT_TRMT_TRANSACTION(ID);   

ALTER TABLE TRANSACTION_REPORT
ADD CONSTRAINT TransactionReportCollectorSiteId
FOREIGN KEY(COLLECTOR_SITE_ID)
REFERENCES COMP_SITE(ID);   

ALTER TABLE TRANSACTION_REPORT
ADD CONSTRAINT TransactionReportCollectorManagerId
FOREIGN KEY(COLLECTOR_MANAGER_ID)
REFERENCES USERS(ID);      

ALTER TABLE TRANSACTION_REPORT
ADD CONSTRAINT TransactionReportTrmtMethod
FOREIGN KEY(TRMT_METHOD)
REFERENCES WSTE_TRMT_METHOD(CODE);    

ALTER TABLE TRANSACTION_REPORT
ADD CONSTRAINT TransactionReportWsteCode
FOREIGN KEY(WSTE_CODE)
REFERENCES WSTE_CODE(CODE);    

ALTER TABLE TRANSACTION_REPORT
ADD CONSTRAINT TransactionReportDisposerManagerId
FOREIGN KEY(DISPOSER_MANAGER_ID)
REFERENCES USERS(ID);    

ALTER TABLE TRANSACTION_REPORT
ADD CONSTRAINT TransactionReportDisposerOrderId
FOREIGN KEY(DISPOSER_ORDER_ID)
REFERENCES SITE_WSTE_DISPOSAL_ORDER(ID);    

ALTER TABLE TRANSACTION_REPORT
ADD CONSTRAINT TransactionReportWsteAppearance
FOREIGN KEY(WSTE_APPEARANCE)
REFERENCES WSTE_APPEARANCE(ID);    

2022.06.06 실시*/