CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_admin_get_real_time_status`(
	IN IN_USER_ID						BIGINT,
	IN IN_ADMIN_MAIN_DURATION			INT,
	OUT OUT_REAL_TIME_STATUS			JSON
)
BEGIN
    
	CREATE TEMPORARY TABLE IF NOT EXISTS RTS_TEMP (
		ID						INT,
		EMITTERS				INT,
		COLLECTORS				INT,
		PROCESSORS				INT,
		WAITING_ANSWERS			INT,
		ADMIN_MAIN_DURATION		INT
	);  
    
	SELECT COUNT(ID) INTO @EMITTERS
    FROM COMP_SITE
    WHERE 
		ACTIVE = TRUE AND
        TRMT_BIZ_CODE = 9 AND
        NOW() <= DATE_ADD(CREATED_AT, INTERVAL CAST(IN_ADMIN_MAIN_DURATION AS UNSIGNED) DAY);   
    
	SELECT COUNT(ID) INTO @PROCESSORS
    FROM COMP_SITE
    WHERE 
		ACTIVE = TRUE AND
        TRMT_BIZ_CODE > 1 AND TRMT_BIZ_CODE < 9 AND
        NOW() <= DATE_ADD(CREATED_AT, INTERVAL CAST(IN_ADMIN_MAIN_DURATION AS UNSIGNED) DAY);  
    
	SELECT COUNT(ID) INTO @COLLECTORS
    FROM COMP_SITE
    WHERE 
		ACTIVE = TRUE AND
        TRMT_BIZ_CODE = 1 AND
        NOW() <= DATE_ADD(CREATED_AT, INTERVAL CAST(IN_ADMIN_MAIN_DURATION AS UNSIGNED) DAY);
    
    CALL sp_get_count_waiting_answers(
		IN_ADMIN_MAIN_DURATION,
        @WAITING_ANSWERS
    );
    
	INSERT INTO 
	RTS_TEMP(
		ID,
		EMITTERS,
		COLLECTORS,
		PROCESSORS,
		WAITING_ANSWERS,
		ADMIN_MAIN_DURATION
	)
	VALUES(
		IN_USER_ID,
		NULL,
		NULL,
		NULL,
		NULL,
		NULL
	);
	UPDATE RTS_TEMP
    SET 
		EMITTERS 				= @EMITTERS,
        COLLECTORS 				= @COLLECTORS,
        PROCESSORS 				= @PROCESSORS,
        WAITING_ANSWERS 		= @WAITING_ANSWERS,
        ADMIN_MAIN_DURATION 	= @ADMIN_MAIN_DURATION
	WHERE ID 					= IN_USER_ID;
    
	SELECT JSON_ARRAYAGG(JSON_OBJECT(
		'ID'						, ID, 
		'EMITTERS'					, EMITTERS, 
        'COLLECTORS'				, COLLECTORS, 
        'PROCESSORS'				, PROCESSORS, 
        'WAITING_ANSWERS'			, WAITING_ANSWERS, 
        'ADMIN_MAIN_DURATION'		, ADMIN_MAIN_DURATION
	)) 
    INTO OUT_REAL_TIME_STATUS FROM RTS_TEMP;
    
	DROP TABLE IF EXISTS RTS_TEMP;

END