CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_admin_get_new_comings`(
	IN IN_SEARCH						VARCHAR(255),
    IN IN_OFFSET_SIZE					INT,
    IN IN_PAGE_SIZE						INT,
    OUT OUT_SITE_LIST					JSON
)
BEGIN

/*
Procedure Name 	: sp_admin_get_new_comings
Input param 	: 4개
Job 			: 사이트의 리스트를 반환한다.
Update 			: 2022.04.28
Version			: 0.0.1
AUTHOR 			: Leo Nam
*/

    DECLARE vRowCount 							INT DEFAULT 0;
    DECLARE endOfRow 							TINYINT 		DEFAULT FALSE;    
    DECLARE CUR_ORDER_ID						BIGINT;   
    DECLARE CUR_DISPOSER_ID						BIGINT;   
    DECLARE CUR_COLLECTOR_ID					BIGINT;  
    DECLARE CUR_SITE_ID							BIGINT;  
    DECLARE CUR_ACTIVE							TINYINT;   
    DECLARE CUR_ORDER_CODE						VARCHAR(10);  
    DECLARE CUR_PROSPECTIVE_VISITORS			INT; 
    DECLARE CUR_BIDDERS							INT;
    DECLARE CUR_PROSPECTIVE_BIDDERS				INT;
    DECLARE CUR_CREATED_AT						DATETIME;
    DECLARE CUR_KIKCD_B_CODE					VARCHAR(10);
    DECLARE CUR_ADDR							VARCHAR(255);
    DECLARE CUR_CHECK_STATE						TINYINT;
    DECLARE VAR_RECORD_COUNT					INT				DEFAULT 0;
    DECLARE TEMP_CURSOR		 					CURSOR FOR 
	SELECT 
		SQL_CALC_FOUND_ROWS
		A.ID, 
		A.DISPOSER_ID, 
        A.COLLECTOR_ID,
        A.SITE_ID,
        A.ACTIVE,
        A.ORDER_CODE,
        A.PROSPECTIVE_VISITORS,
        A.BIDDERS,
        A.PROSPECTIVE_BIDDERS,
        E.CREATED_AT,
        A.KIKCD_B_CODE,
        A.ADDR,
        A.IS_DELETED,
        A.ADDR,
        A.CHECK_STATE
    FROM SITE_WSTE_DISPOSAL_ORDER A
    LEFT JOIN KIKCD_B B ON A.KIKCD_B_CODE = B.B_CODE
    WHERE 
		IF(IN_SEARCH IS NULL,
			A.ID > 0,
			A.ID > 0 AND
			(
				A.DISPOSER_ID IN (SELECT ID FROM USERS WHERE USER_NAME LIKE CONCAT('%', IN_SEARCH, '%')) OR
				A.SITE_ID IN (
					SELECT A1.ID 
                    FROM COMP_SITE A1
                    LEFT JOIN COMPANY A2 ON A1.COMP_ID = A2.ID
                    WHERE 
						A1.SITE_NAME LIKE CONCAT('%', IN_SEARCH, '%') OR
						A1.ADDR LIKE CONCAT('%', IN_SEARCH, '%') OR
						A2.COMP_NAME LIKE CONCAT('%', IN_SEARCH, '%') OR
						A2.ADDR LIKE CONCAT('%', IN_SEARCH, '%') OR
						A2.REP_NAME LIKE CONCAT('%', IN_SEARCH, '%') OR
						REPLACE(A1.BIZ_REG_CODE, '-', '') LIKE CONCAT('%', IN_SEARCH, '%') OR
						REPLACE(A2.PERMIT_REG_CODE, '-', '') LIKE CONCAT('%', IN_SEARCH, '%')
                ) OR
				A.ADDR LIKE CONCAT('%', IN_SEARCH, '%') OR
				B.SI_DO LIKE CONCAT('%', IN_SEARCH, '%') OR
				B.SI_GUN_GU LIKE CONCAT('%', IN_SEARCH, '%') OR
				B.EUP_MYEON_DONG LIKE CONCAT('%', IN_SEARCH, '%') OR
				B.DONG_RI LIKE CONCAT('%', IN_SEARCH, '%') OR
				B.SI_GUN_GU LIKE CONCAT('%', IN_SEARCH, '%') OR
				B.EUP_MYEON_DONG LIKE CONCAT('%', IN_SEARCH, '%') OR
				B.DONG_RI LIKE CONCAT('%', IN_SEARCH, '%') OR
				B.B_CODE LIKE CONCAT('%', IN_SEARCH, '%')
			)
		)
    ORDER BY A.CREATED_AT DESC
    LIMIT IN_OFFSET_SIZE, IN_PAGE_SIZE;   
    
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET endOfRow = TRUE;
	SELECT COUNT(A.ID) INTO VAR_RECORD_COUNT
    FROM SITE_WSTE_DISPOSAL_ORDER A
    LEFT JOIN KIKCD_B B ON A.KIKCD_B_CODE = B.B_CODE
    WHERE 
		IF(IN_SEARCH IS NULL,
			A.ID > 0,
			A.ID > 0 AND
			(
				A.DISPOSER_ID IN (SELECT ID FROM USERS WHERE USER_NAME LIKE CONCAT('%', IN_SEARCH, '%')) OR
				A.SITE_ID IN (
					SELECT A1.ID 
                    FROM COMP_SITE A1
                    LEFT JOIN COMPANY A2 ON A1.COMP_ID = A2.ID
                    WHERE 
						A1.SITE_NAME LIKE CONCAT('%', IN_SEARCH, '%') OR
						A1.ADDR LIKE CONCAT('%', IN_SEARCH, '%') OR
						A2.COMP_NAME LIKE CONCAT('%', IN_SEARCH, '%') OR
						A2.ADDR LIKE CONCAT('%', IN_SEARCH, '%') OR
						A2.REP_NAME LIKE CONCAT('%', IN_SEARCH, '%') OR
						REPLACE(A1.BIZ_REG_CODE, '-', '') LIKE CONCAT('%', IN_SEARCH, '%') OR
						REPLACE(A2.PERMIT_REG_CODE, '-', '') LIKE CONCAT('%', IN_SEARCH, '%')
                ) OR
				A.ADDR LIKE CONCAT('%', IN_SEARCH, '%') OR
				B.SI_DO LIKE CONCAT('%', IN_SEARCH, '%') OR
				B.SI_GUN_GU LIKE CONCAT('%', IN_SEARCH, '%') OR
				B.EUP_MYEON_DONG LIKE CONCAT('%', IN_SEARCH, '%') OR
				B.DONG_RI LIKE CONCAT('%', IN_SEARCH, '%') OR
				B.SI_GUN_GU LIKE CONCAT('%', IN_SEARCH, '%') OR
				B.EUP_MYEON_DONG LIKE CONCAT('%', IN_SEARCH, '%') OR
				B.DONG_RI LIKE CONCAT('%', IN_SEARCH, '%') OR
				B.B_CODE LIKE CONCAT('%', IN_SEARCH, '%')
			)
		);
    
    SET OUT_SITE_LIST = NULL;
	CREATE TEMPORARY TABLE IF NOT EXISTS ADMIN_GET_NEW_COMINGS (
		ORDER_ID						BIGINT,
		DISPOSER_ID						BIGINT,
		COLLECTOR_ID					BIGINT,
		SITE_ID							BIGINT,
		ACTIVE							TINYINT,
		ORDER_CODE						VARCHAR(10),
		PROSPECTIVE_VISITORS			INT,
		BIDDERS							INT,
		PROSPECTIVE_BIDDERS				INT,
		CREATED_AT						DATETIME,
		KIKCD_B_CODE					VARCHAR(10),
		ADDR							VARCHAR(255),
		CHECK_STATE						TINYINT
	);        
	
	OPEN TEMP_CURSOR;	
	cloop: LOOP
		
		FETCH TEMP_CURSOR 
		INTO  
			CUR_ORDER_ID,
			CUR_DISPOSER_ID,
			CUR_COLLECTOR_ID,
			CUR_SITE_ID,
			CUR_ACTIVE,
			CUR_ORDER_CODE,
			CUR_PROSPECTIVE_VISITORS,
			CUR_BIDDERS,
			CUR_PROSPECTIVE_BIDDERS,
			CUR_CREATED_AT,
			CUR_KIKCD_B_CODE,
			CUR_ADDR,
			CUR_CHECK_STATE;
		
		SET vRowCount = vRowCount + 1;
		IF endOfRow THEN
			LEAVE cloop;
		END IF;
		
		INSERT INTO 
		ADMIN_GET_NEW_COMINGS(
			ORDER_ID,
			DISPOSER_ID,
			COLLECTOR_ID,
			SITE_ID,
			ACTIVE,
			ORDER_CODE,
			PROSPECTIVE_VISITORS,
			BIDDERS,
			PROSPECTIVE_BIDDERS,
			CREATED_AT,
			KIKCD_B_CODE,
			ADDR,
			CHECK_STATE
		)
		VALUES(
			CUR_ORDER_ID,
			CUR_DISPOSER_ID,
			CUR_COLLECTOR_ID,
			CUR_SITE_ID,
			CUR_ACTIVE,
			CUR_ORDER_CODE,
			CUR_PROSPECTIVE_VISITORS,
			CUR_BIDDERS,
			CUR_PROSPECTIVE_BIDDERS,
			CUR_CREATED_AT,
			CUR_KIKCD_B_CODE,
			CUR_ADDR,
			CUR_CHECK_STATE
		);
        
	END LOOP;   
	CLOSE TEMP_CURSOR;
	
	SELECT JSON_ARRAYAGG(JSON_OBJECT(
		'ORDER_ID'					, ORDER_ID, 
        'DISPOSER_ID'				, DISPOSER_ID, 
        'COLLECTOR_ID'				, COLLECTOR_ID, 
        'SITE_ID'					, SITE_ID, 
        'ACTIVE'					, ACTIVE, 
        'ORDER_CODE'				, ORDER_CODE, 
        'PROSPECTIVE_VISITORS'		, PROSPECTIVE_VISITORS, 
        'BIDDERS'					, BIDDERS, 
        'PROSPECTIVE_BIDDERS'		, PROSPECTIVE_BIDDERS, 
        'CREATED_AT'				, CREATED_AT, 
        'KIKCD_B_CODE'				, KIKCD_B_CODE, 
        'ADDR'						, ADDR, 
        'CHECK_STATE'				, CHECK_STATE
	)) 
    INTO OUT_SITE_LIST FROM ADMIN_GET_NEW_COMINGS;
    
	DROP TABLE IF EXISTS ADMIN_GET_NEW_COMINGS;
END