CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_admin_retrieve_stat_registeration_without_handler`(
	IN IN_YEAR		INT,
	IN IN_MONTH		INT,
    OUT STAT_LIST	JSON
)
BEGIN
	IF IN_MONTH IS NOT NULL THEN
		SELECT JSON_ARRAYAGG(
			JSON_OBJECT(
				'PARAM_YEAR'		, YEAR(CREATED_AT), 
				'PARAM_MONTH'		, MONTH(CREATED_AT), 
				'PARAM_DAY'			, DAY(CREATED_AT), 
				'USER_TYPE'			, TRMT_BIZ_CODE, 
				'QTY'				, COUNT(CREATED_AT)
			)
		) 
		INTO STAT_LIST
		FROM COMP_SITE 
		GROUP BY 
			YEAR(CREATED_AT), 
			MONTH(CREATED_AT), 
			DAY(CREATED_AT), 
			TRMT_BIZ_CODE
		HAVING 
			YEAR(CREATED_AT) 		= IN_YEAR AND 
            MONTH(CREATED_AT) 		= IN_MONTH;
    ELSE
		SELECT JSON_ARRAYAGG(
			JSON_OBJECT(
				'PARAM_YEAR'		, YEAR(CREATED_AT), 
				'PARAM_MONTH'		, MONTH(CREATED_AT), 
				'USER_TYPE'			, TRMT_BIZ_CODE, 
				'QTY'				, COUNT(CREATED_AT)
			)
		) 
		INTO STAT_LIST
		FROM COMP_SITE 
		GROUP BY 
			YEAR(CREATED_AT), 
			MONTH(CREATED_AT), 
			TRMT_BIZ_CODE
		HAVING 
			YEAR(CREATED_AT) 		= IN_YEAR;
    END IF;
END