CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_admin_retrieve_stat_registeration_year_without_handler`(
	IN IN_YEAR		INT,
    OUT STAT_LIST	JSON
)
BEGIN
    
	CREATE TEMPORARY TABLE IF NOT EXISTS ADMIN_RETRIEVE_STAT_REGISTERATION_YEAR_TEMP (
        PARAM_YEAR			INT,
        PARAM_MONTH			INT,
        USER_TYPE			INT,
        QTY					INT
	);
    
	INSERT INTO ADMIN_RETRIEVE_STAT_REGISTERATION_YEAR_TEMP(
		PARAM_YEAR,
        PARAM_MONTH,
        USER_TYPE,
        QTY
    )
    SELECT 
		YEAR(CREATED_AT),
		MONTH(CREATED_AT),
		TRMT_BIZ_CODE,
        COUNT(CREATED_AT)
	FROM COMP_SITE 
	WHERE 
		YEAR(CREATED_AT) 		= IN_YEAR AND
        TEST					= FALSE
	GROUP BY 
		YEAR(CREATED_AT), 
		MONTH(CREATED_AT), 
		TRMT_BIZ_CODE;	
    
	SELECT JSON_ARRAYAGG(
		JSON_OBJECT(
			'PARAM_YEAR'		, PARAM_YEAR, 
			'PARAM_MONTH'		, PARAM_MONTH, 
			'USER_TYPE'			, USER_TYPE, 
			'QTY'				, QTY
		)
	) 
	INTO STAT_LIST 
	FROM ADMIN_RETRIEVE_STAT_REGISTERATION_YEAR_TEMP;	
    DROP TABLE IF EXISTS ADMIN_RETRIEVE_STAT_REGISTERATION_YEAR_TEMP;
END