CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_admin_retrieve_stat_region_sido_without_handler`(
    OUT STAT_LIST	JSON
)
BEGIN
    
	CREATE TEMPORARY TABLE IF NOT EXISTS ADMIN_RETRIEVE_STAT_REGION_SIDO_TEMP (
        SI_DO				VARCHAR(10),
        SI_DO_CODE			VARCHAR(20),
        SI_GUN_GU			VARCHAR(10),
        SI_GUN_GU_CODE		VARCHAR(20),
        USER_TYPE			INT,
        QTY					INT
	);
    
	INSERT INTO ADMIN_RETRIEVE_STAT_REGION_SIDO_TEMP(
		SI_DO,
        SI_DO_CODE,
		SI_GUN_GU,
        SI_GUN_GU_CODE,
        USER_TYPE,
        QTY
    )
    SELECT 
		B.SI_DO,
		CONCAT(LEFT(A.KIKCD_B_CODE, 2), '00000000'),	
		C.SI_GUN_GU,	
		CONCAT(LEFT(A.KIKCD_B_CODE, 5), '00000'),
		A.TRMT_BIZ_CODE,
        COUNT(A.TRMT_BIZ_CODE)
	FROM COMP_SITE A
    LEFT JOIN KIKCD_B B ON CONCAT(LEFT(A.KIKCD_B_CODE, 2), '00000000') = B.B_CODE
    LEFT JOIN KIKCD_B C ON CONCAT(LEFT(A.KIKCD_B_CODE, 5), '00000') = C.B_CODE
	WHERE 
        A.TEST					= FALSE AND
        B.CANCELED_DATE			IS NULL AND
        C.CANCELED_DATE			IS NULL
	GROUP BY 
		CONCAT(LEFT(A.KIKCD_B_CODE, 2), '00000000'),		
		CONCAT(LEFT(A.KIKCD_B_CODE, 5), '00000'), 
		A.TRMT_BIZ_CODE;	
    
	SELECT JSON_ARRAYAGG(
		JSON_OBJECT(
			'SI_DO'				, SI_DO, 
			'SI_DO_CODE'		, SI_DO_CODE, 
			'SI_GUN_GU'			, SI_GUN_GU, 
			'SI_GUN_GU_CODE'	, SI_GUN_GU_CODE, 
			'USER_TYPE'			, USER_TYPE, 
			'QTY'				, QTY
		)
	) 
	INTO STAT_LIST 
	FROM ADMIN_RETRIEVE_STAT_REGION_SIDO_TEMP;	
END