CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_admin_get_new_comings_detail`(
    IN IN_PARAMS					JSON
)
BEGIN
    DECLARE VAR_USER_ID				BIGINT DEFAULT NULL;
    DECLARE VAR_ORDER_ID			BIGINT DEFAULT NULL;
    DECLARE JSON_ORDER_INFO			JSON DEFAULT NULL;
    DECLARE rtn_val					INT DEFAULT 0;
    DECLARE msg_txt					VARCHAR(200) DEFAULT 'success';
    DECLARE json_data				JSON DEFAULT NULL;
    
	SELECT USER_ID, ORDER_ID
    INTO VAR_USER_ID, VAR_ORDER_ID
    FROM JSON_TABLE(IN_PARAMS, "$[*]" COLUMNS(
		USER_ID 				BIGINT 				PATH "$.USER_ID",
		ORDER_ID 				BIGINT				PATH "$.ORDER_ID"
	)) AS PARAMS;   
    
	CREATE TEMPORARY TABLE IF NOT EXISTS ADMIN_GET_NEW_COMINGS_DETAIL (
        USER_ID					BIGINT,
        ORDER_ID				BIGINT,
        ORDER_INFO				JSON,
        INPUT_PARAM				JSON
	);
    
	CALL sp_admin_get_new_comings_detail_without_handler(
		VAR_ORDER_ID,
		JSON_ORDER_INFO
	);
    
	INSERT INTO 
	ADMIN_GET_NEW_COMINGS_DETAIL(
		USER_ID,
		ORDER_ID,
		ORDER_INFO
	)
	VALUES(
		VAR_USER_ID,
		VAR_ORDER_ID,
		JSON_ORDER_INFO
	);
    
	SELECT JSON_ARRAYAGG(JSON_OBJECT(
        'USER_ID'				, VAR_USER_ID,
        'ORDER_ID'				, VAR_ORDER_ID,
        'ORDER_INFO'			, JSON_ORDER_INFO,
        'INPUT_PARAM'			, IN_PARAMS
	)) 
    INTO json_data FROM ADMIN_GET_NEW_COMINGS_DETAIL;
    
	DROP TABLE IF EXISTS ADMIN_GET_NEW_COMINGS_DETAIL;
	CALL sp_return_results(json_data, msg_txt, json_data);
END