CREATE PROCEDURE `sp_admin_get_real_time_status` (
	OUT OUT_REAL_TIME_STATUS			JSON
)
BEGIN
    
	CREATE TEMPORARY TABLE IF NOT EXISTS RTS_TEMP (
		EMITTERS				INT,
		COLLECTORS				INT,
		PROCESSORS				INT
	);   
    
	SELECT COUNT(ID) INTO @EMITTERS
    FROM COMP_SITE
    WHERE 
		ACTIVE = TRUE AND
        TRMT_BIZ_CODE = 9;   
    
	SELECT COUNT(ID) INTO @PROCESSORS
    FROM COMP_SITE
    WHERE 
		ACTIVE = TRUE AND
        TRMT_BIZ_CODE > 1 AND TRMT_BIZ_CODE < 9;  
    
	SELECT COUNT(ID) INTO @COLLECTORS
    FROM COMP_SITE
    WHERE 
		ACTIVE = TRUE AND
        TRMT_BIZ_CODE = 1;
    
	INSERT INTO 
	RTS_TEMP(
		EMITTERS,
		COLLECTORS,
		PROCESSORS
	)
	VALUES(
		@EMITTERS,
		@COLLECTORS,
		@PROCESSORS
	);
	
	SELECT JSON_ARRAYAGG(JSON_OBJECT(
		'EMITTERS'			, EMITTERS, 
        'COLLECTORS'		, @COLLECTORS, 
        'PROCESSORS'		, @PROCESSORS
	)) 
    INTO OUT_REAL_TIME_STATUS FROM RTS_TEMP;
    
	DROP TABLE IF EXISTS RTS_TEMP;

END
