CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_admin_retrieve_chats_without_handler`(
    IN IN_ROOM_ID					BIGINT,
    IN IN_USER_ID					BIGINT,
    IN IN_PAGE_SIZE					INT,
    IN IN_OFFSET_SIZE				INT,
    OUT OUT_CHAT					JSON
)
BEGIN

    DECLARE vRowCount 							INT DEFAULT 0;
    DECLARE endOfRow 							TINYINT DEFAULT FALSE;   
    DECLARE VAR_AVATAR_PATH						VARCHAR(255) DEFAULT NULL;
    DECLARE VAR_SITE_NAME						VARCHAR(255) DEFAULT NULL;
    DECLARE CUR_DATE							DATE; 
    DECLARE TEMP_CURSOR		 					CURSOR FOR 
	SELECT DISTINCT DATE(CREATED_AT)
    FROM CHATS
	WHERE 
		ROOM_ID = IN_ROOM_ID;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET endOfRow = TRUE;
    
	CREATE TEMPORARY TABLE IF NOT EXISTS ADMIN_RETRIEVE_CHATS_WITHOUT_HANDLER_TEMP (
		VAR_DATE						DATE,
		DAILY_CHATS						JSON,
        AVATAR_PATH						VARCHAR(255),
        SITE_NAME						VARCHAR(255)
	);        
	
	OPEN TEMP_CURSOR;	
	cloop: LOOP
		
		FETCH TEMP_CURSOR 
		INTO 
			CUR_DATE;
		
		SET vRowCount = vRowCount + 1;
		IF endOfRow THEN
			LEAVE cloop;
		END IF;
		
		INSERT INTO 
		ADMIN_RETRIEVE_CHATS_WITHOUT_HANDLER_TEMP(
			VAR_DATE
		)
		VALUES(
			CUR_DATE
		);
        
        CALL sp_admin_retrieve_daily_chats_without_handler(
			IN_ROOM_ID,
            IN_USER_ID,
            CUR_DATE,
            @CHAT_LIST
        );
        
        SELECT A.AVATAR_PATH, B.SITE_NAME
        INTO VAR_AVATAR_PATH, VAR_SITE_NAME
        FROM USERS A
        LEFT JOIN COMP_SITE B ON A.AFFILIATED_SITE = B.ID
        WHERE A.ID IN (SELECT USER_ID FROM CHATS WHERE ROOM_ID = IN_ROOM_ID AND USER_ID NOT IN (IN_USER_ID));
        
		UPDATE ADMIN_RETRIEVE_CHATS_WITHOUT_HANDLER_TEMP 
        SET 
			DAILY_CHATS 	= @CHAT_LIST,
			AVATAR_PATH 	= VAR_AVATAR_PATH,
			SITE_NAME 		= VAR_SITE_NAME
        WHERE VAR_DATE 		= CUR_DATE;
        
	END LOOP;   
	CLOSE TEMP_CURSOR;
	
	SELECT JSON_ARRAYAGG(JSON_OBJECT(
		'VAR_DATE'			, VAR_DATE, 
        'DAILY_CHATS'		, DAILY_CHATS, 
        'AVATAR_PATH'		, AVATAR_PATH, 
        'SITE_NAME'			, SITE_NAME
	)) 
    INTO OUT_CHAT FROM ADMIN_RETRIEVE_CHATS_WITHOUT_HANDLER_TEMP;    
	DROP TABLE IF EXISTS ADMIN_RETRIEVE_CHATS_WITHOUT_HANDLER_TEMP;
END