CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_calc_bidder_and_prospective_visitors`()
BEGIN

    DECLARE vRowCount 						INT DEFAULT 0;
    DECLARE endOfRow 						TINYINT DEFAULT FALSE;  
    
    DECLARE CUR_ID		 					BIGINT;
    
    DECLARE TEMP_CURSOR 					CURSOR FOR 
    SELECT 
		ID
	FROM SITE_WSTE_DISPOSAL_ORDER;
    
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET endOfRow = TRUE;   
    	
	OPEN TEMP_CURSOR;	
	cloop: LOOP
		FETCH TEMP_CURSOR 
		INTO 
			CUR_ID;
		
		SET vRowCount = vRowCount + 1;
		IF endOfRow THEN
			LEAVE cloop;
		END IF;
				
		SELECT COUNT(ID) INTO @BIDDERS 
		FROM COLLECTOR_BIDDING 
		WHERE 
			DISPOSAL_ORDER_ID 		= CUR_ID AND 
			DATE_OF_BIDDING			IS NOT NULL AND
			CANCEL_BIDDING 			= FALSE AND
			REJECT_BIDDING 			<> TRUE AND
			REJECT_BIDDING_APPLY	<> TRUE;
            
		SELECT COUNT(ID) INTO @PROSPECTIVE_VISITORS 
		FROM COLLECTOR_BIDDING 
		WHERE 
			DISPOSAL_ORDER_ID 	= CUR_ID AND 
			DATE_OF_VISIT 		IS NOT NULL AND
			CANCEL_VISIT 		= FALSE AND
			RESPONSE_VISIT 		= TRUE;
			
		UPDATE SITE_WSTE_DISPOSAL_ORDER 
        SET 
			BIDDERS = @BIDDERS,
            PROSPECTIVE_VISITORS = @PROSPECTIVE_VISITORS
        WHERE ID = CUR_ID;

	END LOOP;   
	CLOSE TEMP_CURSOR;
    
END