CREATE PROCEDURE `sp_calc_distance_with_geo` (
	IN IN_LAT1			DECIMAL(12,9),
	IN IN_LNG1			DECIMAL(12,9),
	IN IN_LAT2			DECIMAL(12,9),
	IN IN_LNG2			DECIMAL(12,9),
	IN OUT_DIST			FLOAT
)
BEGIN
	SET @LAT_DIFF = IN_LAT1 - IN_LAT2;
	SET @LNG_DIFF = IN_LNG1 - IN_LNG2;
    SET @LAT_1 = IN_LAT1 * PI() / 180;
    SET @LNG_1 = IN_LNG1 * PI() / 180;
    SET @LAT_2 = IN_LAT2 * PI() / 180;
    SET @LNG_2 = IN_LNG2 * PI() / 180;
    SET @DIST = 6378.137 * ACOS(COS(@LAT_1)*COS(@LAT_2)*COS(@LNG_2 - @LNG_1)) + SIN(@LAT_1) * SIN(@LAT_2);
    SET OUT_DIST = @DIST;
END
