CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_check_if_wste_code_valid`(
	IN IN_WSTE_BCODE				VARCHAR(8),
    OUT OUT_VALID					TINYINT
)
BEGIN
	SELECT COUNT(CODE) INTO OUT_VALID
	FROM WSTE_CODE
	WHERE 
		CODE = IN_WSTE_BCODE AND
		DISPLAY = TRUE;

END