CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_check_if_trmt_biz_code_valid`(
	IN IN_TRMT_BIZ_CODE						VARCHAR(4),
    OUT OUT_TRMT_BIZ_CODE_VALID				INT
)
BEGIN
	SELECT COUNT(ID) INTO OUT_TRMT_BIZ_CODE_VALID
    FROM WSTE_TRMT_BIZ
    WHERE CODE = IN_TRMT_BIZ_CODE;
END