CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_calc_bidder_and_prospective_visitors`(
	IN IN_DISPOSER_ORDER_ID			BIGINT
)
BEGIN
    CALL sp_req_current_time(@REG_DT);
	SELECT COUNT(ID) INTO @BIDDERS 
	FROM COLLECTOR_BIDDING 
	WHERE 
		BID_AMOUNT 				IS NOT NULL AND
		DISPOSAL_ORDER_ID 		= IN_DISPOSER_ORDER_ID AND 
		DATE_OF_BIDDING			IS NOT NULL AND
		CANCEL_BIDDING 			= FALSE AND
		REJECT_BIDDING 			<> TRUE AND
		REJECT_BIDDING_APPLY	<> TRUE AND
		GIVEUP_BIDDING			<> TRUE AND
		ACTIVE					= TRUE AND
        DELETED					= FALSE;
		
	SELECT COUNT(ID) INTO @PROSPECTIVE_VISITORS 
	FROM COLLECTOR_BIDDING 
	WHERE 
		DISPOSAL_ORDER_ID 	= IN_DISPOSER_ORDER_ID AND 
		DATE_OF_VISIT 		IS NOT NULL AND
		CANCEL_VISIT 		= FALSE AND
		RESPONSE_VISIT 		= TRUE AND
        DELETED				= FALSE;
		
	SELECT COUNT(ID) INTO @COUNT_BIDDINGS
	FROM COLLECTOR_BIDDING 
	WHERE DISPOSAL_ORDER_ID 	= IN_DISPOSER_ORDER_ID;   
	
	SELECT COUNT(A.ID) INTO @UNABLED_BIDDERS 
	FROM COLLECTOR_BIDDING A
    LEFT JOIN COMP_SITE B ON A.COLLECTOR_ID = B.ID
	WHERE 
		A.DISPOSAL_ORDER_ID 	= IN_DISPOSER_ORDER_ID AND 
		(
			A.ACTIVE		 			= FALSE OR
			A.DELETED 					= TRUE OR
			A.DATE_OF_VISIT 			IS NULL OR
			A.RESPONSE_VISIT 			= FALSE OR
			A.RESPONSE_VISIT 			IS NULL OR
			A.CANCEL_VISIT 				= TRUE OR
			A.REJECT_BIDDING_APPLY 		= TRUE OR
			A.GIVEUP_BIDDING 			= TRUE OR
			A.CANCEL_BIDDING 			= TRUE OR
			A.REJECT_BIDDING 			= TRUE OR
			A.DATE_OF_BIDDING			IS NOT NULL OR
            B.ACTIVE					= FALSE
		);
		
	UPDATE SITE_WSTE_DISPOSAL_ORDER 
	SET 
		BIDDERS = @BIDDERS,
		PROSPECTIVE_VISITORS = @PROSPECTIVE_VISITORS,
		PROSPECTIVE_BIDDERS = @COUNT_BIDDINGS - @UNABLED_BIDDERS,
        UPDATED_AT = @REG_DT
	WHERE ID = IN_DISPOSER_ORDER_ID;
    
END