CREATE PROCEDURE `sp_check_if_bcode_valid` (
	IN IN_BCODE				VARCHAR(10),
    OUT OUT_VALID			TINYINT
)
BEGIN
	SELECT COUNT(ID) INTO OUT_VALID
	FROM KIKCD_B
	WHERE 
		B_CODE = IN_BCODE AND
		CANCELED_DATE IS NULL;

END
