CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_count_lists`(
	IN IN_LIST			VARCHAR(200),
    OUT OUT_COUNT		INT
)
BEGIN
	SET @IN_ARRAY = IN_LIST;
    SET @ITEM = NULL;
    SET @LIST_COUNT = 0;
    
	WHILE (LOCATE(',', @IN_ARRAY) > 0) DO
		SET @ITEM = SUBSTRING(@IN_ARRAY, 1, LOCATE(',', @IN_ARRAY) - 1);
		SET @IN_ARRAY = SUBSTRING(@IN_ARRAY, LOCATE(',', @IN_ARRAY) + 1);   
		SET @LIST_COUNT = @LIST_COUNT + 1;
	END WHILE;
    
    SET OUT_COUNT = @LIST_COUNT;
END