CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_calc_bidding_rank`(
	IN IN_DISPOSER_ORDER_ID			BIGINT
)
BEGIN

/*
Procedure Name 	: sp_calc_bidding_rank
Input param 	: 1개
Job 			: 투찰한 업체의 낙찰순위를 일괄 계산한다. 향후 탄소배출량 등을 추가한 계산방식을 적용하는 경우 이 프로시저의 ORDER BY BID_AMOUNT 부분을 수정하면 된다.
Update 			: 2022.03.19
Version			: 0.0.1
AUTHOR 			: Leo Nam
*/

    CALL sp_req_current_time(@REG_DT);
    
	UPDATE COLLECTOR_BIDDING SET BIDDING_RANK = NULL WHERE DISPOSAL_ORDER_ID = IN_DISPOSER_ORDER_ID;
	
	SET @rank:=0;
	UPDATE COLLECTOR_BIDDING 
	SET BIDDING_RANK			= @rank := @rank+1 
	WHERE 
		BID_AMOUNT 				IS NOT NULL AND
		DISPOSAL_ORDER_ID 		= IN_DISPOSER_ORDER_ID AND 
		DATE_OF_BIDDING			IS NOT NULL AND
		CANCEL_BIDDING 			= FALSE AND
		REJECT_BIDDING 			<> TRUE AND
		REJECT_BIDDING_APPLY	<> TRUE AND
		ACTIVE					= TRUE
	ORDER BY BID_AMOUNT ASC;
    
    SELECT BIDDERS INTO @BIDDERS FROM SITE_WSTE_DISPOSAL_ORDER WHERE ID = IN_DISPOSER_ORDER_ID;
	UPDATE COLLECTOR_BIDDING SET WINNER = FALSE, UPDATED_AT = @REG_DT WHERE DISPOSAL_ORDER_ID = IN_DISPOSER_ORDER_ID;
	UPDATE COLLECTOR_BIDDING SET WINNER = TRUE, UPDATED_AT = @REG_DT WHERE DISPOSAL_ORDER_ID = IN_DISPOSER_ORDER_ID AND BIDDING_RANK = 1;
    
    SELECT COUNT(ID) INTO @BIDDERS FROM COLLECTOR_BIDDING WHERE BIDDING_RANK IS NOT NULL;
    IF @BIDDERS > 0 THEN
		SELECT ID INTO @FIRST_PLACE FROM COLLECTOR_BIDDING WHERE BIDDING_RANK = 1 AND DISPOSAL_ORDER_ID = IN_DISPOSER_ORDER_ID;
        UPDATE SITE_WSTE_DISPOSAL_ORDER SET FIRST_PLACE = @FIRST_PLACE WHERE ID = IN_DISPOSER_ORDER_ID;
		IF @BIDDERS > 1 THEN
			SELECT ID INTO @SECOND_PLACE FROM COLLECTOR_BIDDING WHERE BIDDING_RANK = 2 AND DISPOSAL_ORDER_ID = IN_DISPOSER_ORDER_ID;
			UPDATE SITE_WSTE_DISPOSAL_ORDER SET SECOND_PLACE = @SECOND_PLACE WHERE ID = IN_DISPOSER_ORDER_ID;
        END IF;
    END IF;
    
END