CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_check_if_trmt_method_valid`(
	IN IN_TRMT_METHOD_CODE					VARCHAR(4),
    OUT OUT_METHOD_CODE_VALID				INT
)
BEGIN
	SELECT COUNT(ID) INTO OUT_METHOD_CODE_VALID
    FROM WSTE_TRMT_METHOD 
    WHERE CODE = IN_TRMT_METHOD_CODE;
END