CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_calc_bidding_rank_all`()
BEGIN

    DECLARE vRowCount 						INT DEFAULT 0;
    DECLARE endOfRow 						TINYINT DEFAULT FALSE;      
    DECLARE CUR_ID		 					BIGINT;    
    DECLARE TEMP_CURSOR 					CURSOR FOR 
    SELECT 
		ID
	FROM SITE_WSTE_DISPOSAL_ORDER;
    
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET endOfRow = TRUE;   
    	
	OPEN TEMP_CURSOR;	
    CALL sp_req_current_time(@REG_DT);
	cloop: LOOP
		FETCH TEMP_CURSOR 
		INTO 
			CUR_ID;
		
		SET vRowCount = vRowCount + 1;
		IF endOfRow THEN
			LEAVE cloop;
		END IF;
		
        UPDATE COLLECTOR_BIDDING SET BIDDING_RANK = NULL WHERE DISPOSAL_ORDER_ID = CUR_ID;
        
        SET @rank:=0;
		UPDATE COLLECTOR_BIDDING 
        SET BIDDING_RANK=@rank:=@rank+1 
        WHERE 
			BID_AMOUNT 				IS NOT NULL AND
			DISPOSAL_ORDER_ID 		= CUR_ID AND 
			DATE_OF_BIDDING			IS NOT NULL AND
			CANCEL_BIDDING 			= FALSE AND
			REJECT_BIDDING 			<> TRUE AND
			REJECT_BIDDING_APPLY	<> TRUE AND
            ACTIVE					= TRUE
        ORDER BY BID_AMOUNT ASC;
    
		SELECT BIDDERS INTO @BIDDERS FROM SITE_WSTE_DISPOSAL_ORDER WHERE ID = CUR_ID;
		UPDATE COLLECTOR_BIDDING SET WINNER = FALSE, UPDATED_AT = @REG_DT WHERE DISPOSAL_ORDER_ID = CUR_ID;
		UPDATE COLLECTOR_BIDDING SET WINNER = TRUE, UPDATED_AT = @REG_DT WHERE DISPOSAL_ORDER_ID = CUR_ID AND BIDDING_RANK = 1;

	END LOOP;   
	CLOSE TEMP_CURSOR;
    
END