CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_calc_bidder_and_prospective_visitors`(
	IN IN_DISPOSER_ORDER_ID			BIGINT
)
BEGIN
	SELECT COUNT(ID) INTO @BIDDERS 
	FROM COLLECTOR_BIDDING 
	WHERE 
		BID_AMOUNT 				IS NOT NULL AND
		DISPOSAL_ORDER_ID 		= IN_DISPOSER_ORDER_ID AND 
		DATE_OF_BIDDING			IS NOT NULL AND
		CANCEL_BIDDING 			= FALSE AND
		REJECT_BIDDING 			<> TRUE AND
		REJECT_BIDDING_APPLY	<> TRUE AND
		GIVEUP_BIDDING			<> TRUE AND
		ACTIVE					= TRUE;
		
	SELECT COUNT(ID) INTO @PROSPECTIVE_VISITORS 
	FROM COLLECTOR_BIDDING 
	WHERE 
		DISPOSAL_ORDER_ID 	= IN_DISPOSER_ORDER_ID AND 
		DATE_OF_VISIT 		IS NOT NULL AND
		CANCEL_VISIT 		= FALSE AND
		RESPONSE_VISIT 		= TRUE;
		
	SELECT COUNT(ID) INTO @COUNT_BIDDINGS
	FROM COLLECTOR_BIDDING 
	WHERE DISPOSAL_ORDER_ID 	= IN_DISPOSER_ORDER_ID;   
	
	SELECT COUNT(ID) INTO @UNABLED_BIDDERS 
	FROM COLLECTOR_BIDDING 
	WHERE 
		DISPOSAL_ORDER_ID 	= IN_DISPOSER_ORDER_ID AND 
		(
			ACTIVE		 			= FALSE OR
			DELETED 				= TRUE OR
			DATE_OF_VISIT 			IS NULL OR
			RESPONSE_VISIT 			= FALSE OR
			RESPONSE_VISIT 			IS NULL OR
			CANCEL_VISIT 			= TRUE OR
			REJECT_BIDDING_APPLY 	= TRUE OR
			GIVEUP_BIDDING 			= TRUE OR
			CANCEL_BIDDING 			= TRUE OR
			REJECT_BIDDING 			= TRUE OR
			DATE_OF_BIDDING			IS NOT NULL
		);
		
	UPDATE SITE_WSTE_DISPOSAL_ORDER 
	SET 
		BIDDERS = @BIDDERS,
		PROSPECTIVE_VISITORS = @PROSPECTIVE_VISITORS,
		PROSPECTIVE_BIDDERS = @COUNT_BIDDINGS - @UNABLED_BIDDERS
	WHERE ID = IN_DISPOSER_ORDER_ID;
    
END