CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_get_report_wste_lists`(
	IN IN_DISPOSER_ORDER_ID				BIGINT,
	IN IN_TRANSACTION_ID				BIGINT,
    OUT OUT_WSTE_LIST					JSON
)
BEGIN	
	SELECT JSON_ARRAYAGG(
		JSON_OBJECT(
			'WSTE_CODE'			, A.WSTE_CODE, 
			'WSTE_NM'			, B.NAME, 
			'WSTE_APPEARANCE'	, C.KOREAN, 
			'QUANTITY'			, A.QUANTITY, 
			'TRMT_METHOD'		, D.NAME, 
			'UNIT'				, A.UNIT,
			'PRICE'				, A.PRICE,
			'UPDATED_AT'		, A.CREATED_AT,
            'COLLECT_END_AT'	, E.COLLECT_END_AT
		)
	) 
	INTO OUT_WSTE_LIST 
	FROM TRANSACTION_REPORT A 
    LEFT JOIN WSTE_CODE B ON A.WSTE_CODE = B.CODE
    LEFT JOIN WSTE_APPEARANCE C ON A.WSTE_APPEARANCE = C.ID
    LEFT JOIN WSTE_TRMT_METHOD D ON A.TRMT_METHOD = D.CODE
    LEFT JOIN WSTE_CLCT_TRMT_TRANSACTION E ON A.TRANSACTION_ID = E.ID
	WHERE 
		A.DISPOSER_ORDER_ID = IN_DISPOSER_ORDER_ID AND
        E.ID = IN_TRANSACTION_ID;
END