CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_get_no_confirm_license_counts_monthly`(
	IN IN_TARGET_DATE				DATE,
	IN IN_MENU_ID					INT,
    OUT OUT_LIST					JSON
)
BEGIN
    IF IN_MENU_ID IS NOT NULL THEN
		SET @TARGET_YEAR = YEAR(IN_TARGET_DATE);
		SET @TARGET_MONTH = MONTH(IN_TARGET_DATE);
		
		CREATE TEMPORARY TABLE IF NOT EXISTS NO_CONFIRM_LICENSE_LIST_MONTHLY (
			TARGET_DATE								DATE,
			NO_CONFIRM_COUNT						INT
		);        
		
		INSERT INTO NO_CONFIRM_LICENSE_LIST_MONTHLY(
			TARGET_DATE,
			NO_CONFIRM_COUNT
		)
		SELECT DATE(A.CREATED_AT), COUNT(DATE(A.CREATED_AT))
		FROM COMP_SITE A
		LEFT JOIN COMPANY B ON A.COMP_ID = B.ID
		WHERE 
			B.ACTIVE = TRUE AND
			A.ACTIVE = TRUE AND
            IF(IN_MENU_ID = 0,
				IF(IN_TARGET_DATE IS NOT NULL, 
					B.CONFIRMED = FALSE AND YEAR(A.CREATED_AT) = @TARGET_YEAR AND MONTH(A.CREATED_AT) = @TARGET_MONTH, 
					B.CONFIRMED = FALSE
				),
				IF(IN_MENU_ID = 1,
					IF(IN_TARGET_DATE IS NOT NULL, 
						(
							B.CONFIRMED = FALSE OR
                            A.CONFIRMED = FALSE
                        ) AND 
                        B.TRMT_BIZ_CODE = '1' AND
                        YEAR(A.CREATED_AT) = @TARGET_YEAR AND MONTH(A.CREATED_AT) = @TARGET_MONTH, 
						(
							B.CONFIRMED = FALSE OR
							A.CONFIRMED = FALSE
                        ) AND 
                        B.TRMT_BIZ_CODE = '1'
					),
					IF(IN_TARGET_DATE IS NOT NULL, 
						(
							B.CONFIRMED = FALSE OR
                            A.CONFIRMED = FALSE
                        ) AND 
                        B.TRMT_BIZ_CODE IN (
							SELECT CODE FROM WSTE_TRMT_BIZ WHERE CAST(CODE AS UNSIGNED) > 1 AND CAST(CODE AS UNSIGNED) < 9
						) AND
                        YEAR(A.CREATED_AT) = @TARGET_YEAR AND MONTH(A.CREATED_AT) = @TARGET_MONTH, 
						(
							B.CONFIRMED = FALSE OR
							A.CONFIRMED = FALSE
                        ) AND 
                        B.TRMT_BIZ_CODE IN (
							SELECT CODE FROM WSTE_TRMT_BIZ WHERE CAST(CODE AS UNSIGNED) > 1 AND CAST(CODE AS UNSIGNED) < 9
						)
					)
				)
            )
		GROUP BY DATE(A.CREATED_AT);      
		
		SELECT JSON_ARRAYAGG(
			JSON_OBJECT(
				'TARGET_DATE'		, TARGET_DATE, 
				'NO_CONFIRM_COUNT'	, NO_CONFIRM_COUNT
			)
		) 
		INTO OUT_LIST 
		FROM NO_CONFIRM_LICENSE_LIST_MONTHLY;
		DROP TABLE IF EXISTS NO_CONFIRM_LICENSE_LIST_MONTHLY;
    ELSE
		SET OUT_LIST = NULL;
    END IF;
    
END