CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_get_collector_lists_2`(
	IN IN_DISPOSER_ORDER_ID				BIGINT,
    IN IN_STATE_CATEGORY_CODE			INT,
    OUT OUT_COLLECTOR_LIST				JSON
)
BEGIN	
		
	SELECT JSON_ARRAYAGG(
		JSON_OBJECT(
			'COLLECTOR_BIDDING_ID'			, A.COLLECTOR_BIDDING_ID, 
			'COLLECTOR_SITE_ID'				, A.COLLECTOR_SITE_ID, 
			'COLLECTOR_SI_DO'				, A.COLLECTOR_SI_DO, 
			'COLLECTOR_SI_GUN_GU'			, A.COLLECTOR_SI_GUN_GU, 
			'COLLECTOR_STATE'				, A.STATE, 
			'COLLECTOR_STATE_CODE'			, A.STATE_CODE, 
			'COLLECTOR_LAT'					, A.COLLECTOR_LAT, 
			'COLLECTOR_LNG'					, A.COLLECTOR_LNG, 
			'COLLECTOR_SITE_NAME'			, A.COLLECTOR_SITE_NAME, 
			'COLLECTOR_TRMT_BIZ_CODE'		, A.COLLECTOR_TRMT_BIZ_CODE, 
			'COLLECTOR_TRMT_BIZ_NM'			, A.TRMT_BIZ_NM, 
			'COLLECTOR_BID_AMOUNT'			, A.COLLECTOR_BID_AMOUNT, 
			'COLLECTOR_GREENHOUSE_GAS'		, A.COLLECTOR_GREENHOUSE_GAS, 
			'COLLECTOR_WINNER'				, A.COLLECTOR_WINNER, 
			'COLLECTOR_ACTIVE'				, A.COLLECTOR_ACTIVE, 
			'COLLECTOR_CANCEL_VISIT'		, A.COLLECTOR_CANCEL_VISIT, 
			'COLLECTOR_CANCEL_BIDDING'		, A.COLLECTOR_CANCEL_BIDDING, 
			'COLLECTOR_DATE_OF_VISIT'		, A.COLLECTOR_DATE_OF_VISIT, 
			'COLLECTOR_DATE_OF_BIDDING'		, A.COLLECTOR_DATE_OF_BIDDING, 
			'COLLECTOR_SELECTED'			, A.COLLECTOR_SELECTED, 
			'COLLECTOR_SELECTED_AT'			, A.COLLECTOR_SELECTED_AT, 
			'COLLECTOR_MAKE_DECISION'		, A.COLLECTOR_MAKE_DECISION, 
			'COLLECTOR_MAKE_DECISION_AT'	, A.COLLECTOR_MAKE_DECISION_AT, 
			'DISPOSER_RESPONSE_VISIT'		, A.DISPOSER_RESPONSE_VISIT, 
			'DISPOSER_RESPONSE_VISIT_AT'	, A.DISPOSER_RESPONSE_VISIT_AT,
			'DISPOSER_REJECT_BIDDING'		, A.DISPOSER_REJECT_BIDDING, 
			'DISPOSER_REJECT_BIDDING_AT'	, A.DISPOSER_REJECT_BIDDING_AT, 
			'COLLECTOR_STATE_CATEGORY_ID'	, A.STATE_CATEGORY_ID, 
			'COLLECTOR_STATE_CATEGORY'		, A.STATE_CATEGORY, 
			'BIDDING_RANK'					, A.BIDDING_RANK, 
			'COLLECTOR_WINNER'				, A.COLLECTOR_WINNER,
			'AVATAR_PATH'					, B.AVATAR_PATH
		)
	) 
	INTO OUT_COLLECTOR_LIST
	FROM V_COLLECTOR_BIDDING_WITH_STATE A 
	LEFT JOIN USERS B ON A.COLLECTOR_SITE_ID = B.AFFILIATED_SITE
	WHERE 
		A.DISPOSER_ORDER_ID 		= IN_DISPOSER_ORDER_ID AND 
		A.STATE_CATEGORY_ID 		>= IN_STATE_CATEGORY_CODE AND
		A.STATE_PID					<> 211 AND
		A.STATE_CODE				<> 211 AND
		B.CLASS						= 201 AND
		B.ACTIVE					= TRUE AND
		IF (IN_STATE_CATEGORY_CODE = 4, A.BIDDING_RANK <= 2, A.BIDDING_RANK >= 0 OR A.BIDDING_RANK IS NULL);	

END