CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_get_disposer_name_from_report`(
	IN IN_REPORT_ID				BIGINT,
    OUT rtn_val					INT,
    OUT msg_txt					VARCHAR(200),
    OUT OUT_SITE_NAME_INFO		JSON
)
BEGIN
    DECLARE vRowCount 							INT DEFAULT 0;
    DECLARE endOfRow 							TINYINT DEFAULT FALSE;    
    DECLARE CUR_SITE_NAME						VARCHAR(255); 
    DECLARE TEMP_CURSOR		 					CURSOR FOR 
	SELECT 
		IF(B.SITE_ID = 0, D.USER_NAME, C.SITE_NAME)
	FROM TRANSACTION_REPORT A 
    LEFT JOIN SITE_WSTE_DISPOSAL_ORDER B ON A.DISPOSER_ORDER_ID = B.ID
    LEFT JOIN COMP_SITE C ON B.SITE_ID = C.ID
    LEFT JOIN USERS D ON B.DISPOSER_ID = D.ID
	WHERE 
		A.ID = IN_REPORT_ID;    
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET endOfRow = TRUE;	      
        
	CREATE TEMPORARY TABLE IF NOT EXISTS GET_DISPOSER_NAME_TEMP (
		SITE_NAME				VARCHAR(255)
	);      
	
	OPEN TEMP_CURSOR;	
	cloop: LOOP
		FETCH TEMP_CURSOR 
		INTO 
			CUR_SITE_NAME;
		
		SET vRowCount = vRowCount + 1;
		IF endOfRow THEN
			LEAVE cloop;
		END IF;
		
		INSERT INTO GET_DISPOSER_NAME_TEMP (
			SITE_NAME
		)
		VALUES(
			CUR_SITE_NAME
		);
	END LOOP;   
	CLOSE TEMP_CURSOR;
	
	SELECT JSON_ARRAYAGG(
		JSON_OBJECT(
			'SITE_NAME'					, SITE_NAME
		)
	) INTO OUT_SITE_NAME_INFO FROM GET_DISPOSER_NAME_TEMP;
    
	SET rtn_val = 0;
	SET msg_txt = 'Success';
	DROP TABLE IF EXISTS GET_DISPOSER_NAME_TEMP;
END