CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_get_site_lists_registered`(
	IN IN_TARGET_DATE				DATETIME,
	IN IN_MENU_ID					INT,
    OUT OUT_LIST					JSON
)
BEGIN
	
    IF IN_MENU_ID IS NOT NULL THEN
		CREATE TEMPORARY TABLE IF NOT EXISTS SITE_LISTS_REGISTERED_TEMP (
			ID							BIGINT,
			SITE_NAME					VARCHAR(255),
			BIZ_REG_CODE				VARCHAR(12),
			PERMIT_REG_CODE				VARCHAR(100),
			CREATED_AT					DATE,
			BIZ_REG_CODE_REGISTERED		TINYINT,
			PERMIT_REG_CODE_REGISTERED	TINYINT
		);     
		
		INSERT INTO SITE_LISTS_REGISTERED_TEMP (
			ID,
			SITE_NAME,
			BIZ_REG_CODE,
			PERMIT_REG_CODE,
			CREATED_AT,
			BIZ_REG_CODE_REGISTERED,
			PERMIT_REG_CODE_REGISTERED
		)
		SELECT 
			A.ID, 
			IF(A.AFFILIATED_SITE = 0, A.USER_NAME, B.SITE_NAME),
			IF(A.AFFILIATED_SITE = 0, NULL, C.BIZ_REG_CODE),
            B.PERMIT_REG_CODE,
			DATE(A.CREATED_AT),
			IF(A.AFFILIATED_SITE = 0, NULL, C.CONFIRMED),
			IF(A.AFFILIATED_SITE = 0, NULL, C.CONFIRMED)
		FROM USERS A         
		LEFT JOIN COMP_SITE B ON A.AFFILIATED_SITE = B.ID
		LEFT JOIN COMPANY C ON B.COMP_ID = C.ID
		LEFT JOIN KIKCD_B D ON B.KIKCD_B_CODE = D.B_CODE
		WHERE 
			DATE(A.CREATED_AT) = IN_TARGET_DATE AND
			(
				IF(IN_MENU_ID = 0,
					A.AFFILIATED_SITE = 0 OR 	
					B.TRMT_BIZ_CODE IN (
						SELECT CODE FROM WSTE_TRMT_BIZ WHERE USER_TYPE = 3
					),	
                    IF(IN_MENU_ID = 1,
						B.TRMT_BIZ_CODE = '1',
						B.TRMT_BIZ_CODE IN (
							SELECT CODE FROM WSTE_TRMT_BIZ WHERE CAST(CODE AS UNSIGNED) > 1 AND CAST(CODE AS UNSIGNED) < 9
						)
                    )			
                )
			);
		
		SELECT JSON_ARRAYAGG(
			JSON_OBJECT(
				'ID'							, ID, 
				'SITE_NAME'						, SITE_NAME, 
				'BIZ_REG_CODE'					, BIZ_REG_CODE,
				'PERMIT_REG_CODE'				, PERMIT_REG_CODE,
				'CREATED_AT'					, CREATED_AT,
				'BIZ_REG_CODE_REGISTERED'		, BIZ_REG_CODE_REGISTERED,
				'PERMIT_REG_CODE_REGISTERED'	, PERMIT_REG_CODE_REGISTERED
			)
		) 
		INTO OUT_LIST 
		FROM SITE_LISTS_REGISTERED_TEMP;	
		DROP TABLE IF EXISTS SITE_LISTS_REGISTERED_TEMP;
    ELSE
		SET OUT_LIST = NULL;
    END IF;
END