CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_get_collector_img_lists`(
	IN IN_TRANSACTION_ID			BIGINT,
    OUT OUT_IMG_LIST				JSON
)
BEGIN
	SELECT JSON_ARRAYAGG(
		JSON_OBJECT(
			'FILE_NAME'			, FILE_NAME, 
			'IMG_PATH'			, IMG_PATH, 
			'FILE_SIZE'			, FILE_SIZE
		)
	) 
	INTO OUT_IMG_LIST 
	FROM WSTE_REGISTRATION_PHOTO  
	WHERE TRANSACTION_ID = IN_TRANSACTION_ID;	
END