CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_get_transaction_report`(
	IN IN_REPORT_ID						BIGINT,
    OUT OUT_TRANSACTION_REPORT			JSON
)
BEGIN	
	SELECT JSON_ARRAYAGG(
		JSON_OBJECT(
			'ID'							, A.ID, 
			'WSTE_CODE'						, A.WSTE_CODE, 
			'WSTE_NM'						, B.NAME, 
			'WSTE_APPEARANCE'				, C.KOREAN, 
			'QUANTITY'						, A.QUANTITY, 
			'TRMT_METHOD'					, D.NAME, 
			'UNIT'							, A.UNIT,
			'PRICE'							, A.PRICE,
			'COMPLETED_AT'					, A.TRANSACTION_COMPLETED_AT,
            'SITE_NAME'						, F.SITE_NAME
		)
	) 
	INTO OUT_TRANSACTION_REPORT 
	FROM TRANSACTION_REPORT A 
    LEFT JOIN WSTE_CODE B ON A.WSTE_CODE = B.CODE
    LEFT JOIN WSTE_APPEARANCE C ON A.WSTE_APPEARANCE = C.ID
    LEFT JOIN WSTE_TRMT_METHOD D ON A.TRMT_METHOD = D.CODE
    LEFT JOIN WSTE_CLCT_TRMT_TRANSACTION E ON A.TRANSACTION_ID = E.ID
    LEFT JOIN COMP_SITE F ON A.COLLECTOR_SITE_ID = F.ID
	WHERE 
		A.ID = IN_REPORT_ID;
END