CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_get_disposer_wste_geo_info`(
	IN IN_DISPOSER_ORDER_ID			BIGINT,
    OUT OUT_IMG_LIST				JSON
)
BEGIN		
	SELECT JSON_ARRAYAGG(JSON_OBJECT(
		'ID'			, ID, 
		'LAT'			, LAT, 
		'LNG'			, LNG
	)) 
	INTO OUT_IMG_LIST
	FROM SITE_WSTE_DISPOSAL_ORDER 
	WHERE ID = IN_DISPOSER_ORDER_ID;
END