CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_get_bidding_state`(
	IN IN_ORDER_ID					BIGINT,
    OUT OUT_STATE					TINYINT
)
BEGIN
	SELECT COUNT(ID) INTO @RECORD_COUNT
    FROM COLLECTOR_BIDDING
    WHERE 
		DISPOSAL_ORDER_ID = IN_ORDER_ID AND
        CHECK_STATE = FALSE;
        
	IF @RECORD_COUNT > 0 THEN
		SET OUT_STATE = TRUE;
    ELSE
		SET OUT_STATE = FALSE;
    END IF;
END