CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_get_disposal_wste_lists_3`(
	IN IN_DISPOSER_ORDER_ID				BIGINT,
    OUT OUT_DISPOSER_WSTE_LIST			JSON
)
BEGIN	
        
	SELECT JSON_ARRAYAGG(JSON_OBJECT(
		'WSTE_CLASS'	, WSTE_CLASS, 
		'WSTE_NM'		, WSTE_CLASS_NM, 
		'APR'			, WSTE_APPEARANCE_NM, 
		'QTY'			, WSTE_QUANTITY, 
		'UNIT'			, WSTE_UNIT, 
		'CREATED_AT'	, WSTE_DISCHARGED_CREATED_AT
	)) 
	INTO OUT_DISPOSER_WSTE_LIST 
	FROM V_WSTE_DISCHARGED_FROM_SITE 
	WHERE DISPOSAL_ORDER_ID = IN_DISPOSER_ORDER_ID;

END