CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_get_address_with_bcode`(
	IN IN_BCODE				VARCHAR(10),
    OUT OUT_ADDRESS_INFO	JSON
)
BEGIN
	
	CREATE TEMPORARY TABLE IF NOT EXISTS ADDRESS_INFO_TEMP (
		B_CODE					VARCHAR(10),
		SI_DO					VARCHAR(20),
		SI_GUN_GU				VARCHAR(20),
        EUP_MYEON_DONG			VARCHAR(20),
        DONG_RI					VARCHAR(20),
        JACHIGU					TINYINT
	);     
    
    INSERT INTO ADDRESS_INFO_TEMP (
		B_CODE,
		SI_DO,
		SI_GUN_GU,
        EUP_MYEON_DONG,
        DONG_RI,
        JACHIGU
	)
	SELECT 
		B_CODE,
		SI_DO,
		SI_GUN_GU,
        EUP_MYEON_DONG,
        DONG_RI,
        JACHIGU
	FROM KIKCD_B 
	WHERE 
		B_CODE = IN_BCODE AND
        CANCELED_DATE IS NULL;	
    
	SELECT JSON_ARRAYAGG(
		JSON_OBJECT(
			'B_CODE'					, B_CODE, 
			'SI_DO'						, SI_DO, 
			'SI_GUN_GU'					, SI_GUN_GU, 
			'EUP_MYEON_DONG'			, EUP_MYEON_DONG,
			'DONG_RI'					, DONG_RI,
			'JACHIGU'					, JACHIGU
		)
	) 
	INTO OUT_ADDRESS_INFO 
	FROM ADDRESS_INFO_TEMP;	
	DROP TABLE IF EXISTS ADDRESS_INFO_TEMP;
END