CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_get_disposal_order_info`(
	IN IN_DISPOSER_ORDER_ID			BIGINT,
    OUT OUT_DISPOSAL_ORDER_INFO		JSON
)
BEGIN
	SELECT JSON_ARRAYAGG(
		JSON_OBJECT(
			'ID'				, A.ID, 
			'ORDER_CODE'		, A.ORDER_CODE, 
			'SITE_ID'			, A.SITE_ID, 
			'SITE_NAME'			, B.SITE_NAME, 
			'B_CODE'			, A.KIKCD_B_CODE, 
			'SI_DO'				, C.SI_DO,
			'SI_GUN_GU'			, C.SI_GUN_GU,
			'EUP_MYEON_DONG'	, C.EUP_MYEON_DONG,
			'DONG_RI'			, C.DONG_RI,
			'ADDR'				, A.ADDR,
			'ASK_END_AT'		, D.COLLECT_ASK_END_AT,
			'NOTE'				, A.NOTE,
			'VISIT_START_AT'	, A.VISIT_START_AT,
			'VISIT_END_AT'		, A.VISIT_END_AT,
			'BIDDING_END_AT'	, A.BIDDING_END_AT,
			'DISPOSER_ID'		, A.DISPOSER_ID,
			'AVATAR_PATH'		, E.AVATAR_PATH
		)
	) 
	INTO OUT_DISPOSAL_ORDER_INFO 
	FROM SITE_WSTE_DISPOSAL_ORDER A 
    LEFT JOIN COMP_SITE B ON A.SITE_ID = B.ID
    LEFT JOIN KIKCD_B C ON A.KIKCD_B_CODE = C.B_CODE
    LEFT JOIN WSTE_CLCT_TRMT_TRANSACTION D ON A.ID = D.DISPOSAL_ORDER_ID
    LEFT JOIN USERS E ON A.SITE_ID = E.AFFILIATED_SITE
	WHERE 
		A.ID = IN_DISPOSER_ORDER_ID AND
        E.CLASS = 201 AND
        E.ACTIVE = TRUE;
END