CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_get_collector_state`(
	IN IN_ORDER_ID				BIGINT,
    IN IN_COLLECTOR_SITE_ID		BIGINT,
    OUT OUT_STATE				VARCHAR(20),
    OUT OUT_STATE_CODE			INT,
    OUT OUT_STATE_CATEGORY_ID	INT,
    OUT OUT_STATE_CATEGORY		VARCHAR(20)
)
BEGIN
	SELECT
		STATE,
		STATE_CODE,
		STATE_CATEGORY_ID,
		STATE_CATEGORY
	INTO 
		OUT_STATE,
		OUT_STATE_CODE,
		OUT_STATE_CATEGORY_ID,
		OUT_STATE_CATEGORY
	FROM V_BIDDING_STATE_NAME
	WHERE 
		DISPOER_ORDER_ID = IN_ORDER_ID AND
		COLLECTOR_ID = IN_COLLECTOR_SITE_ID;
END