CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_get_transaction_state_info`(
	IN IN_TRANSACTION_ID			BIGINT,
    OUT OUT_TRANSACTION_STATE_INFO	JSON
)
BEGIN
	SELECT JSON_ARRAYAGG(JSON_OBJECT(
		'STATE'						, STATE, 
		'STATE_CODE'				, STATE_CODE, 
		'STATE_CATEGORY'			, STATE_CATEGORY, 
		'STATE_CATEGORY_ID'			, STATE_CATEGORY_ID
	)) 
	INTO OUT_TRANSACTION_STATE_INFO
	FROM V_TRANSACTION_STATE_NAME
    WHERE TRANSACTION_ID = IN_TRANSACTION_ID; 
END