CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_get_collector_wste_lists`(
	IN IN_DISPOSER_ORDER_ID				BIGINT,
	IN IN_TRANSACTION_ID				BIGINT,
    OUT OUT_WSTE_LIST					JSON
)
BEGIN	
	SELECT JSON_ARRAYAGG(
		JSON_OBJECT(
			'WSTE_CODE'			, A.WSTE_CODE, 
			'WSTE_NM'			, B.NAME, 
			'WSTE_APPEARANCE'	, C.KOREAN, 
			'QUANTITY'			, A.WSTE_QUANTITY, 
			'UNIT'				, A.WSTE_UNIT,
			'UPDATED_AT'		, A.CREATED_AT,
            'COLLECT_END_AT'	, A.COLLECT_END_AT
		)
	) 
	INTO OUT_WSTE_LIST 
	FROM WSTE_CLCT_TRMT_TRANSACTION A 
    LEFT JOIN WSTE_CODE B ON A.WSTE_CODE = B.CODE
    LEFT JOIN WSTE_APPEARANCE C ON A.WSTE_APPEARANCE = C.ID
	WHERE 
		A.DISPOSAL_ORDER_ID = IN_DISPOSER_ORDER_ID AND
        A.ID = IN_TRANSACTION_ID;
END