CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_get_disposal_order_info`(
	IN IN_DISPOSER_ORDER_ID			BIGINT,
    OUT OUT_DISPOSAL_ORDER_INFO		JSON
)
BEGIN
	SELECT JSON_ARRAYAGG(
		JSON_OBJECT(
			'ID'				, A.ID, 
			'SITE_ID'			, A.SITE_ID, 
			'SITE_NAME'			, B.SITE_NAME
		)
	) 
	INTO OUT_DISPOSAL_ORDER_INFO 
	FROM SITE_WSTE_DISPOSAL_ORDER A 
    LEFT JOIN COMP_SITE B ON A.SITE_ID = B.ID
	WHERE 
		ID 		= IN_DISPOSER_ORDER_ID;	
END