CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_get_company`(
	IN IN_COMP_ID				BIGINT
/*
    OUT OUT_COMP_NAME			VARCHAR(100),
    OUT OUT_REP_NAME			VARCHAR(50),
    OUT OUT_KIKCD_B_CODE		VARCHAR(10),
    OUT OUT_ADDR				VARCHAR(300),
    OUT OUT_CONTACT				VARCHAR(100),
    OUT OUT_TRMT_BIZ_CODE		VARCHAR(4),
    OUT OUT_BIZ_REG_CODE		VARCHAR(12),
    OUT OUT_PERMIT_REG_CODE		VARCHAR(100),
    OUT OUT_BIZ_REG_IMG_PATH	VARCHAR(200),
    OUT OUT_PERMIT_REG_IMG_PATH	VARCHAR(200)
*/
)
BEGIN

/*
Procedure Name 	: sp_get_company
Input param 	: 1개
Output param 	: 10개
Job 			: 사업자 정보를 반환한다.
Update 			: 2022.01.10
Version			: 0.0.2
AUTHOR 			: Leo Nam
*/
/*
	SELECT COMP_NAME, REP_NAME, KIKCD_B_CODE, ADDR, CONTACT, TRMT_BIZ_CODE, BIZ_REG_CODE, PERMIT_REG_CODE, BIZ_REG_IMG_PATH, PERMIT_REG_IMG_PATH
	INTO OUT_COMP_NAME, OUT_REP_NAME, OUT_KIKCD_B_CODE, OUT_ADDR, OUT_CONTACT, OUT_TRMT_BIZ_CODE, OUT_BIZ_REG_CODE, OUT_PERMIT_REG_CODE, OUT_BIZ_REG_IMG_PATH, OUT_PERMIT_REG_IMG_PATH
	FROM COMPANY WHERE ID = IN_COMP_ID; 
*/
	SELECT 
		COMP_NAME, 
		REP_NAME, 
        KIKCD_B_CODE, 
        ADDR, 
        CONTACT, 
        TRMT_BIZ_CODE, 
        BIZ_REG_CODE, 
        PERMIT_REG_CODE, 
        BIZ_REG_IMG_PATH, 
        PERMIT_REG_IMG_PATH
	FROM COMPANY WHERE ID = IN_COMP_ID; 

/*
다른 프로시저에서 프로시저가 반환하는 레코드를 받아서 사용하는 예
CREATE PROCEDURE p(
	IN IN_COMP_ID		BIGINT
)
BEGIN
	SET @SQL_TEMP = CONCAT('CALL sp_get_company(', IN_COMP_ID, ')');
	PREPARE Q FROM @SQL_TEMP;
	EXECUTE Q;
END

SET @COMP_ID = 10;
CALL p(@COMP_ID);
*/
END