CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_get_site_wste_info`(
	IN IN_SITE_ID						BIGINT,
    OUT OUT_SITE_WSTE_LIST				JSON
)
BEGIN
	SELECT JSON_ARRAYAGG(JSON_OBJECT(
		'SITE_ID'					, A.SITE_ID,
		'WSTE_CODE'					, A.WSTE_CODE,
		'WSTE_NM'					, B.NAME,
		'APPR_CODE'					, A.WSTE_APPEARANCE,
		'APPR_NM'					, C.KOREAN,
		'CREATED_AT'				, A.CREATED_AT,
		'UPDATED_AT'				, A.UPDATED_AT
	)) 
	INTO OUT_SITE_WSTE_LIST
	FROM WSTE_SITE_MATCH A
    LEFT JOIN WSTE_CODE B ON A.WSTE_CODE = B.CODE
    LEFT JOIN WSTE_APPEARANCE C ON A.WSTE_APPEARANCE = C.ID
    WHERE 
		A.SITE_ID = IN_SITE_ID AND
        A.ACTIVE = TRUE; 

END