CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_get_collector_lists`(
	IN IN_DISPOSER_ORDER_ID				BIGINT,
    IN IN_STATE_CATEGORY_CODE			INT,
    OUT OUT_COLLECTOR_LIST				JSON
)
BEGIN			
	SELECT JSON_ARRAYAGG(
		JSON_OBJECT(
			'ID'							, A.COLLECTOR_BIDDING_ID, 
			'COLLECTOR_SITE_ID'				, A.COLLECTOR_SITE_ID, 
			'COLLECTOR_SITE_NM'				, A.COLLECTOR_SITE_NAME, 
			'BIZ'							, A.TRMT_BIZ_NM, 
			'DIST'							, A.STRAIGHT_DISTANCE, 
			'STATE'							, A.STATE,
			'STATE_CODE'					, A.STATE_CODE,
			'DISPOSER_SITE_ID'				, A.DISPOSER_SITE_ID,
			'COLLECTOR_DATE_OF_VISIT'		, A.COLLECTOR_DATE_OF_VISIT,
			'COLLECTOR_DATE_OF_BIDDING'		, A.COLLECTOR_DATE_OF_BIDDING,
			'COLLECTOR_SELECTED_AT'			, A.COLLECTOR_SELECTED_AT,
			'COLLECTOR_MAKE_DECISION_AT'	, A.COLLECTOR_MAKE_DECISION_AT,
			'COLLECTOR_AVATAR_PATH'			, B.AVATAR_PATH,
			'COLLECTOR_MANAGER_ID'			, B.ID,
			'COLLECTOR_CONTACT'				, A.COLLECTOR_CONTACT,
			'COLLECTOR_MANAGER_PHONE'		, B.PHONE,
			'TRMT_BIZ_NM'					, A.TRMT_BIZ_NM,
			'BIDDING_RANK'					, A.BIDDING_RANK,
			'COLLECTOR_WINNER'				, A.COLLECTOR_WINNER,
			'TRANSACTION_ID'				, A.TRANSACTION_ID
		)
	) 
	INTO OUT_COLLECTOR_LIST 
	FROM V_COLLECTOR_BIDDING_WITH_STATE A 
	INNER JOIN USERS B 
	ON A.COLLECTOR_SITE_ID = B.AFFILIATED_SITE
	WHERE 
		B.CLASS 					= 201 AND
		B.ACTIVE					= TRUE AND
		A.DISPOSER_ORDER_ID 		= IN_DISPOSER_ORDER_ID AND
		A.STATE_CATEGORY_ID			>= IN_STATE_CATEGORY_CODE AND
		IF (IN_STATE_CATEGORY_CODE = 4 OR IN_STATE_CATEGORY_CODE = 5, 
			A.BIDDING_RANK <= 2 AND A.STATE_CODE = 236, 
			A.BIDDING_RANK >= 0 OR A.BIDDING_RANK IS NULL
		)
	ORDER BY A.BIDDING_RANK ASC;
	/*수거자정보를 JSON형태로 변환한다.*/

END