CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_get_reply`(
	IN IN_PID						BIGINT,
    OUT OUT_REPLY_LIST				JSON
)
BEGIN

	SELECT JSON_ARRAYAGG(
		JSON_OBJECT(
			'ID'					, POST_ID, 
			'SITE_ID'				, POST_SITE_ID, 
			'SITE_NAME'				, POST_SITE_NAME, 
			'CREATOR_ID'			, POST_CREATOR_ID, 
			'CREATOR_NAME'			, POST_CREATOR_NAME, 
			'SUBJECTS'				, POST_SUBJECTS, 
			'CONTENTS'				, POST_CONTENTS, 
			'CATEGORY_ID'			, POST_CATEGORY_ID, 
			'CATEGORY_NAME'			, POST_CATEGORY_NAME, 
			'SUB_CATEGORY_ID'		, POST_SUB_CATEGORY_ID, 
			'SUB_CATEGORY_NAME'		, POST_SUB_CATEGORY_NAME, 
			'VISITORS'				, POST_VISITORS, 
			'CREATED_AT'			, POST_CREATED_AT, 
			'UPDATED_AT'			, POST_UPDATED_AT, 
			'RATING'				, POST_RATING
		)
	) 
	INTO OUT_REPLY_LIST
	FROM V_POSTS 
	WHERE POST_PID = IN_PID AND
		POST_ACTIVE = TRUE;   
END