CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_get_collector_lists`(
	IN IN_DISPOSER_ORDER_ID				BIGINT,
    IN IN_STATE_CATEGORY_CODE			INT,
    OUT OUT_COLLECTOR_LIST				JSON
)
BEGIN			
	SELECT JSON_ARRAYAGG(
		JSON_OBJECT(
			'ID'							, A.ID, 
			'COLLECTOR_SITE_ID'				, A.COLLECTOR_ID, 
			'COLLECTOR_SITE_NM'				, C.SITE_NAME, 
			'BIZ'							, D.NAME, 
			'DIST'							, SQRT((POW((C.LAT - E.LAT), 2) + POW((C.LNG - E.LNG), 2))), 
			'STATE'							, F.STATE,
			'STATE_CODE'					, F.STATE_CODE,
			'DISPOSER_SITE_ID'				, E.SITE_ID,
			'COLLECTOR_DATE_OF_VISIT'		, A.DATE_OF_VISIT,
			'COLLECTOR_DATE_OF_BIDDING'		, A.DATE_OF_BIDDING,
			'COLLECTOR_SELECTED_AT'			, A.SELECTED_AT,
			'COLLECTOR_MAKE_DECISION_AT'	, A.MAKE_DECISION_AT,
			'COLLECTOR_AVATAR_PATH'			, B.AVATAR_PATH,
			'COLLECTOR_MANAGER_ID'			, B.ID,
			'COLLECTOR_CONTACT'				, C.CONTACT,
			'COLLECTOR_MANAGER_PHONE'		, B.PHONE,
			'TRMT_BIZ_NM'					, D.NAME,
			'BIDDING_RANK'					, A.BIDDING_RANK,
			'COLLECTOR_WINNER'				, A.WINNER,
			'TRANSACTION_ID'				, E.TRANSACTION_ID
		)
	) 
	INTO OUT_COLLECTOR_LIST 
	FROM COLLECTOR_BIDDING A 
	LEFT JOIN USERS B ON A.COLLECTOR_ID = B.AFFILIATED_SITE
	LEFT JOIN COMP_SITE C ON A.COLLECTOR_ID = C.ID
	LEFT JOIN WSTE_TRMT_BIZ D ON C.TRMT_BIZ_CODE = D.CODE
	LEFT JOIN SITE_WSTE_DISPOSAL_ORDER E ON A.DISPOSAL_ORDER_ID = E.ID
    LEFT JOIN V_BIDDING_STATE_NAME F ON A.ID = F.COLLECTOR_BIDDING_ID
	WHERE 
		B.CLASS 					= 201 AND
		B.ACTIVE					= TRUE AND
		E.ID 						= IN_DISPOSER_ORDER_ID AND
		F.STATE_CATEGORY_ID			>= IN_STATE_CATEGORY_CODE AND
		IF (IN_STATE_CATEGORY_CODE = 4 OR IN_STATE_CATEGORY_CODE = 5, 
			A.BIDDING_RANK <= 2 AND F.STATE_CODE = 236, 
			A.BIDDING_RANK >= 0 OR A.BIDDING_RANK IS NULL
		)
	ORDER BY A.BIDDING_RANK ASC;
	/*수거자정보를 JSON형태로 변환한다.*/
END