CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_get_disposal_wste_lists_2`(
	IN IN_DISPOSER_ORDER_ID				BIGINT,
    OUT OUT_DISPOSER_WSTE_LIST			JSON
)
BEGIN	
	SELECT JSON_ARRAYAGG(
		JSON_OBJECT(
			'ID'				, WSTE_REG_ID, 
			'WSTE_NM'			, WSTE_CLASS_NM, 
			'APR'				, WSTE_APPEARANCE_NM, 
			'QTY'				, WSTE_QUANTITY, 
			'UNIT'				, WSTE_UNIT,
			'UPDATED_AT'		, WSTE_DISCHARGED_UPDATED_AT
		)
	) 
	INTO OUT_DISPOSER_WSTE_LIST 
	FROM V_WSTE_DISCHARGED_FROM_SITE 
	WHERE DISPOSAL_ORDER_ID = IN_DISPOSER_ORDER_ID;
END