CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_get_collector_lists_2`(
	IN IN_DISPOSER_ORDER_ID				BIGINT,
    IN IN_STATE_CATEGORY_CODE			INT,
    OUT OUT_COLLECTOR_LIST				JSON
)
BEGIN	
		
	SELECT JSON_ARRAYAGG(
		JSON_OBJECT(
			'COLLECTOR_BIDDING_ID'			, A.ID, 
			'COLLECTOR_SITE_ID'				, A.COLLECTOR_ID, 
			'COLLECTOR_SI_DO'				, G.SI_DO, 
			'COLLECTOR_SI_GUN_GU'			, G.SI_GUN_GU, 
			'COLLECTOR_STATE'				, F.STATE, 
			'COLLECTOR_STATE_CODE'			, F.STATE_CODE, 
			'COLLECTOR_LAT'					, C.LAT, 
			'COLLECTOR_LNG'					, C.LNG, 
			'COLLECTOR_SITE_NAME'			, C.SITE_NAME, 
			'COLLECTOR_TRMT_BIZ_CODE'		, C.TRMT_BIZ_CODE, 
			'COLLECTOR_TRMT_BIZ_NM'			, D.NAME, 
			'COLLECTOR_BID_AMOUNT'			, A.BID_AMOUNT, 
			'COLLECTOR_GREENHOUSE_GAS'		, A.GREENHOUSE_GAS, 
			'COLLECTOR_WINNER'				, A.WINNER, 
			'COLLECTOR_ACTIVE'				, A.ACTIVE, 
			'COLLECTOR_CANCEL_VISIT'		, A.CANCEL_VISIT, 
			'COLLECTOR_CANCEL_BIDDING'		, A.CANCEL_BIDDING, 
			'COLLECTOR_DATE_OF_VISIT'		, A.DATE_OF_VISIT, 
			'COLLECTOR_DATE_OF_BIDDING'		, A.DATE_OF_BIDDING, 
			'COLLECTOR_SELECTED'			, A.SELECTED, 
			'COLLECTOR_SELECTED_AT'			, A.SELECTED_AT, 
			'COLLECTOR_MAKE_DECISION'		, A.MAKE_DECISION, 
			'COLLECTOR_MAKE_DECISION_AT'	, A.MAKE_DECISION_AT, 
			'DISPOSER_RESPONSE_VISIT'		, A.RESPONSE_VISIT, 
			'DISPOSER_RESPONSE_VISIT_AT'	, A.RESPONSE_VISIT_AT,
			'DISPOSER_REJECT_BIDDING'		, A.REJECT_BIDDING, 
			'DISPOSER_REJECT_BIDDING_AT'	, A.REJECT_BIDDING_AT, 
			'COLLECTOR_STATE_CATEGORY_ID'	, F.STATE_CATEGORY_ID, 
			'COLLECTOR_STATE_CATEGORY'		, F.STATE_CATEGORY, 
			'BIDDING_RANK'					, A.BIDDING_RANK, 
			'COLLECTOR_WINNER'				, A.WINNER,
			'AVATAR_PATH'					, B.AVATAR_PATH
		)
	) 
	INTO OUT_COLLECTOR_LIST
	FROM COLLECTOR_BIDDING A 
	LEFT JOIN USERS B ON A.COLLECTOR_ID = B.AFFILIATED_SITE
	LEFT JOIN COMP_SITE C ON A.COLLECTOR_ID = C.ID
	LEFT JOIN WSTE_TRMT_BIZ D ON C.TRMT_BIZ_CODE = D.CODE
	LEFT JOIN SITE_WSTE_DISPOSAL_ORDER E ON A.DISPOSAL_ORDER_ID = E.ID
    LEFT JOIN V_BIDDING_STATE_NAME F ON A.ID = F.COLLECTOR_BIDDING_ID
	LEFT JOIN KIKCD_B G ON C.KIKCD_B_CODE = G.B_CODE
	WHERE 
		E.ID				 		= IN_DISPOSER_ORDER_ID AND 
		F.STATE_CATEGORY_ID 		>= IN_STATE_CATEGORY_CODE AND
		F.STATE_PID					<> 211 AND
		F.STATE_CODE				<> 211 AND
		(B.CLASS = 201 OR B.CLASS = 202) AND
		B.ACTIVE					= TRUE AND
        A.DELETED					= FALSE AND
		IF (IN_STATE_CATEGORY_CODE = 4, A.BIDDING_RANK <= 2, A.BIDDING_RANK >= 0 OR A.BIDDING_RANK IS NULL);	
END