CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_push_disposer_select_collector`(
	IN IN_COLLECTOR_BIDDING_ID		BIGINT,
    OUT OUT_TARGET_LIST				JSON
)
BEGIN
	
	SELECT COUNT(ID) 
    INTO @BIDDING_EXISTS
    FROM COLLECTOR_BIDDING
    WHERE 
		ID = IN_COLLECTOR_BIDDING_ID AND
        DELETED = FALSE AND
        ACTIVE = TRUE;
        
    IF @BIDDING_EXISTS = 1 THEN
		SELECT B.ORDER_CODE, A.COLLECTOR_ID, A.RESPONSE_VISIT
        INTO @ORDER_CODE, @COLLECTOR_SITE_ID, @RESPONSE_VISIT
        FROM COLLECTOR_BIDDING A
        LEFT JOIN SITE_WSTE_DISPOSAL_ORDER B ON A.DISPOSAL_ORDER_ID = B.ID
        WHERE
			A.ID = IN_COLLECTOR_BIDDING_ID;
            
		SET @MSG = CONCAT('신청하신 [', @ORDER_CODE, ']의 입찰에 낙찰되셨습니다. 상세 내용을 확인해주세요.');
		SELECT JSON_ARRAYAGG(
			JSON_OBJECT(
				'USER_ID'	, ID, 
				'FCM'		, FCM,
				'MSG'		, @MSG
			)
		) 
		INTO OUT_TARGET_LIST
		FROM USERS
		WHERE 
			ACTIVE 					= TRUE AND
			PUSH_ENABLED			= TRUE AND
			AFFILIATED_SITE			= @COLLECTOR_SITE_ID;
    ELSE
		SET OUT_TARGET_LIST = NULL;
    END IF;
END