CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_push_disposer_response_visit_1`(
	IN IN_COLLECTOR_BIDDING_ID		BIGINT,
    OUT OUT_TARGET_LIST				JSON
)
BEGIN
	
	SELECT COUNT(ID) 
    INTO @BIDDING_EXISTS
    FROM COLLECTOR_BIDDING
    WHERE 
		ID = IN_COLLECTOR_BIDDING_ID AND
        DELETED = FALSE AND
        CANCEL_VISIT = FALSE AND
        ACTIVE = TRUE;
        
    IF @BIDDING_EXISTS = 1 THEN
		SELECT B.ORDER_CODE, A.COLLECTOR_ID, A.RESPONSE_VISIT
        INTO @ORDER_CODE, @SITE_ID, @RESPONSE_VISIT
        FROM COLLECTOR_BIDDING A
        LEFT JOIN SITE_WSTE_DISPOSAL_ORDER B ON A.DISPOSAL_ORDER_ID = B.ID
        WHERE
			A.ID = IN_COLLECTOR_BIDDING_ID;
		IF @RESPONSE_VISIT = TRUE THEN
			SET @STR_RESPONSE = '수락';
        ELSE
			SET @STR_RESPONSE = '거절';
        END IF;
		SET @MSG = CONCAT('신청하신 [', @ORDER_CODE, ']에 대한 방문신청이 ', @STR_RESPONSE, '되었습니다.');
        IF @SITE_ID = 0 THEN
			SELECT JSON_ARRAYAGG(
				JSON_OBJECT(
					'USER_ID'	, ID, 
					'FCM'		, FCM,
					'MSG'		, @MSG
				)
			) 
			INTO OUT_TARGET_LIST
			FROM USERS 
			WHERE 
				ACTIVE 					= TRUE AND
				PUSH_ENABLED			= TRUE AND
                AFFILIATED_SITE			= @SITE_ID;
        ELSE
			SELECT JSON_ARRAYAGG(
				JSON_OBJECT(
					'USER_ID'	, ID, 
					'FCM'		, FCM,
					'MSG'		, @MSG
				)
			) 
			INTO OUT_TARGET_LIST
			FROM USERS
			WHERE 
				ACTIVE 					= TRUE AND
				PUSH_ENABLED			= TRUE AND
                AFFILIATED_SITE			= @SITE_ID;
        END IF;
    ELSE
		SET OUT_TARGET_LIST = NULL;
    END IF;
END