CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_push_collector_list_share_business_areas`(
	IN IN_B_CODE					VARCHAR(10),
    OUT OUT_COLLECTOR_LIST			JSON
)
BEGIN
	
	SELECT COUNT(B_CODE) INTO @BCODE_EXISTS
    FROM KIKCD_B
    WHERE 
		B_CODE = IN_B_CODE AND
        CANCELED_DATE IS NULL;
    IF @BCODE_EXISTS = 1 THEN
		SELECT SI_DO, SI_GUN_GU
        INTO @SI_DO, @SI_GUN_GU
        FROM KIKCD_B
        WHERE
			B_CODE = IN_B_CODE AND
			CANCELED_DATE IS NULL;
		SET @MSG = CONCAT(@SI_DO, ' ', @SI_GUN_GU, '에 신규 폐기물이 등록되었습니다.');
		SELECT JSON_ARRAYAGG(
			JSON_OBJECT(
				'USER_ID'	, C.ID, 
				'FCM'		, C.FCM,
                'MSG'		, @MSG
			)
		) 
		INTO OUT_COLLECTOR_LIST
		FROM BUSINESS_AREA A 
		LEFT JOIN COMP_SITE B ON A.SITE_ID = B.ID
		LEFT JOIN USERS C ON B.ID = C.AFFILIATED_SITE
		WHERE 
			A.ACTIVE 					= TRUE AND
			B.ACTIVE 					= TRUE AND
			C.ACTIVE	 				= TRUE AND
            C.PUSH_ENABLED				= TRUE AND
			LEFT(A.KIKCD_B_CODE, 5) 	= LEFT(IN_B_CODE, 5);
    ELSE
		SET OUT_COLLECTOR_LIST = NULL;
    END IF;
END