CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_push_collector_dispose_new_wste`(
	IN IN_USER_ID					BIGINT,
	IN IN_ORDER_ID					BIGINT,
	IN IN_COLLECTOR_SITE_ID			BIGINT,
    OUT OUT_TARGET_LIST				JSON,
    OUT rtn_val 					INT,				/*출력값 : 처리결과 반환값*/
    OUT msg_txt 					VARCHAR(200)		/*출력값 : 처리결과 문자열*/
)
BEGIN
	SELECT IF(A.AFFILIATED_SITE = 0, A.USER_NAME, B.SITE_NAME)
    INTO @DISPOSER_NAME
	FROM USERS A
    LEFT JOIN COMP_SITE B ON A.AFFILIATED_SITE = B.ID
	WHERE A.ID = IN_USER_ID;
		
	SELECT ORDER_CODE INTO @ORDER_CODE
	FROM SITE_WSTE_DISPOSAL_ORDER
	WHERE ID = IN_ORDER_ID;
	SET @ORDER_ID = IN_ORDER_ID;
    
    SELECT ID INTO @TRANSACTION_ID
    FROM WSTE_CLCT_TRMT_TRANSACTION
    WHERE 
		DISPOSAL_ORDER_ID = IN_ORDER_ID AND
        COLLECTOR_SITE_ID = IN_COLLECTOR_SITE_ID;
    
    SELECT AVATAR_PATH INTO @AVATAR_PATH
    FROM USERS
    WHERE ID = IN_USER_ID;
    
	SET @SUBJECTS = CONCAT('[', @ORDER_CODE, ']신규 폐기물 등록');
	SET @CONTENTS = CONCAT('[', @DISPOSER_NAME, ']님이 신규 폐기물 처리를 요청하셨습니다 .');
	SELECT JSON_ARRAYAGG(
		JSON_OBJECT(
			'USER_ID'				, ID, 
			'FCM'					, FCM, 
			'AVATAR_PATH'			, @AVATAR_PATH,
			'SUBJECTS'				, @TITLE,
			'CONTENTS'				, @BODY,
			'ORDER_ID'				, @ORDER_ID, 
			'BIDDING_ID'			, NULL, 
			'TRANSACTION_ID'		, @TRANSACTION_ID, 
			'REPORT_ID'				, NULL, 
			'TARGET_URL'			, NULL
		)
	) 
	INTO OUT_TARGET_LIST
	FROM USERS
	WHERE 
		ACTIVE 					= TRUE AND
		PUSH_ENABLED			= TRUE AND
		AFFILIATED_SITE			= IN_COLLECTOR_SITE_ID;
        
	CALL sp_insert_push(
		0,
		OUT_TARGET_LIST,
		rtn_val,
		msg_txt
	);
END