CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_push_collector_dispose_new_wste`(
	IN IN_DISPOSER_ORDER_ID			BIGINT,
	IN IN_COLLECTOR_SITE_ID			BIGINT,
    OUT OUT_TARGET_LIST				JSON
)
BEGIN
	SELECT IF(A.SITE_ID = 0, C.USER_NAME, B.SITE_NAME)
    INTO @DISPOSER_NAME
	FROM SITE_WSTE_DISPOSAL_ORDER A
    LEFT JOIN COMP_SITE B ON A.SITE_ID = B.ID
    LEFT JOIN USERS C ON A.DISPOSER_ID = C.ID
	WHERE A.ID = IN_DISPOSER_ORDER_ID;
		
	SET @MSG = CONCAT('[', @DISPOSER_NAME, ']님이 신규 폐기물 처리를 요청하셨습니다 .');
	SELECT JSON_ARRAYAGG(
		JSON_OBJECT(
			'USER_ID'	, ID, 
			'FCM'		, FCM,
			'MSG'		, @MSG
		)
	) 
	INTO OUT_TARGET_LIST
	FROM USERS
	WHERE 
		ACTIVE 					= TRUE AND
		PUSH_ENABLED			= TRUE AND
		AFFILIATED_SITE			= IN_COLLECTOR_SITE_ID;
END