CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_push_collector_accept_ask_end`(
	IN IN_TRANSACTION_ID			BIGINT,
	IN IN_WHAT						VARCHAR(10),
    OUT OUT_TARGET_LIST				JSON
)
BEGIN
	
	SELECT COUNT(ID) 
    INTO @TRANSACTION_EXISTS
    FROM WSTE_CLCT_TRMT_TRANSACTION
    WHERE 
		ID = IN_TRANSACTION_ID;
        
    IF @TRANSACTION_EXISTS = 1 THEN
		SELECT B.ORDER_CODE, B.SITE_ID, B.DISPOSER_ID, C.SITE_NAME
        INTO @ORDER_CODE, @DISPOSER_SITE_ID, @DISPOSER_ID, @COLLECTOR_SITE_NAME
        FROM WSTE_CLCT_TRMT_TRANSACTION A
        LEFT JOIN SITE_WSTE_DISPOSAL_ORDER B ON A.DISPOSAL_ORDER_ID = B.ID
        LEFT JOIN COMP_SITE C ON A.COLLECTOR_ID = C.ID
        WHERE
			A.ID = IN_TRANSACTION_ID;
            
		SET @MSG = CONCAT('신청하신 [', @ORDER_CODE, ']의 요청을 ', @COLLECTOR_SITE_NAME, '님이 수락하셨습니다.');
        IF @DISPOSER_SITE_ID = 0 THEN
			SELECT JSON_ARRAYAGG(
				JSON_OBJECT(
					'USER_ID'	, ID, 
					'FCM'		, FCM,
					'MSG'		, @MSG
				)
			) 
			INTO OUT_TARGET_LIST
			FROM USERS 
			WHERE 
				ACTIVE 					= TRUE AND
				PUSH_ENABLED			= TRUE AND
                ID						= @DISPOSER_ID;
        ELSE
			SELECT JSON_ARRAYAGG(
				JSON_OBJECT(
					'USER_ID'	, ID, 
					'FCM'		, FCM,
					'MSG'		, @MSG
				)
			) 
			INTO OUT_TARGET_LIST
			FROM USERS
			WHERE 
				ACTIVE 					= TRUE AND
				PUSH_ENABLED			= TRUE AND
                AFFILIATED_SITE			= @DISPOSER_SITE_ID;
        END IF;
    ELSE
		SET OUT_TARGET_LIST = NULL;
    END IF;
END