CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_push_disposer_write_review`(
	IN IN_DISPOSER_SITE_ID				BIGINT,
	IN IN_COLLECTOR_SITE_ID				BIGINT,
    OUT OUT_TARGET_LIST					JSON
)
BEGIN
	
	SELECT SITE_NAME INTO @DISPOSER_SITE_NAME
	FROM COMP_SITE
	WHERE ID = IN_DISPOSER_SITE_ID;
		
	SET @MSG = CONCAT('[', @DISPOSER_SITE_NAME, ']님이 리뷰를 등록했습니다.');
	SELECT JSON_ARRAYAGG(
		JSON_OBJECT(
			'USER_ID'	, ID, 
			'FCM'		, FCM,
			'MSG'		, @MSG
		)
	) 
	INTO OUT_TARGET_LIST
	FROM USERS
	WHERE 
		ACTIVE 					= TRUE AND
		PUSH_ENABLED			= TRUE AND
		AFFILIATED_SITE			= IN_COLLECTOR_SITE_ID;
END