CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_req_get_user_current_type`(
	IN IN_USER_ID				BIGINT,
    OUT OUT_USER_CURRENT_TYPE	INT
)
BEGIN          
	SELECT USER_CURRENT_TYPE INTO OUT_USER_CURRENT_TYPE
	FROM USERS WHERE ID = IN_USER_ID;
END