CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_req_order_details_t252`(
	IN IN_ORDER_ID				BIGINT,
    OUT OUT_DETAILS				JSON
)
BEGIN
	CREATE TEMPORARY TABLE IF NOT EXISTS ORDER_DETAILS_T252_TEMP (
		ORDER_ID							BIGINT,
		ORDER_CODE							VARCHAR(10),
        COLLECTOR_SITE_ID					BIGINT,
        COLLECTOR_SITE_NAME					VARCHAR(255),
		COLLECTOR_TRMT_BIZ_CODE				VARCHAR(4),    
		COLLECTOR_TRMT_BIZ_NAME				VARCHAR(255),  
        AVATAR_PATH							VARCHAR(255),
		DISPOSER_WSTE_LIST					JSON,
        STATE_CODE							INT,
        STATE								VARCHAR(20),
        STATE_CATEGORY_ID					INT,
        STATE_CATEGORY						VARCHAR(20)
        
	);        
    
    CALL sp_req_current_time(@REG_DT);
    SET @STATE_CODE = NULL;
    SET @STATE = NULL;
    SET @STATE_CATEGORY_ID = NULL;
    SET @STATE_CATEGORY = NULL;
    
    INSERT INTO ORDER_DETAILS_T252_TEMP(
		ORDER_ID, 
        ORDER_CODE, 
        COLLECTOR_SITE_ID, 
        COLLECTOR_SITE_NAME, 
        COLLECTOR_TRMT_BIZ_CODE, 
        COLLECTOR_TRMT_BIZ_NAME, 
        AVATAR_PATH,
        STATE_CODE,
        STATE,
        STATE_CATEGORY_ID,
        STATE_CATEGORY
    )
    SELECT 
		A.ID,
        A.ORDER_CODE,
        A.COLLECTOR_ID,
        B.SITE_NAME,
        B.TRMT_BIZ_CODE,
        C.NAME,
        D.AVATAR_PATH,
        E.STATE_CODE,
        E.STATE,
        E.STATE_CATEGORY_ID,
        E.STATE_CATEGORY
    FROM SITE_WSTE_DISPOSAL_ORDER A
    LEFT JOIN COMP_SITE B ON A.COLLECTOR_ID = B.ID
    LEFT JOIN WSTE_TRMT_BIZ C ON B.TRMT_BIZ_CODE = C.CODE
    LEFT JOIN USERS D ON B.ID = D.AFFILIATED_SITE
    LEFT JOIN V_TRANSACTION_STATE_NAME E ON A.ID = E.DISPOSAL_ORDER_ID
    WHERE 
		A.ID = IN_ORDER_ID AND
        D.CLASS = 201 AND
        D.ACTIVE = TRUE;  
    	
    CALL sp_get_disposal_wste_lists(
		IN_ORDER_ID,
        @DISPOSER_WSTE_LIST
    );
    
    UPDATE ORDER_DETAILS_T252_TEMP 
    SET DISPOSER_WSTE_LIST 			= @DISPOSER_WSTE_LIST 
    WHERE ORDER_ID = IN_ORDER_ID;
    
	SELECT JSON_ARRAYAGG(JSON_OBJECT(
		'ORDER_ID'					, ORDER_ID, 
        'ORDER_CODE'				, ORDER_CODE, 
        'COLLECTOR_SITE_ID'			, COLLECTOR_SITE_ID, 
        'COLLECTOR_SITE_NAME'		, COLLECTOR_SITE_NAME, 
        'COLLECTOR_TRMT_BIZ_CODE'	, COLLECTOR_TRMT_BIZ_CODE, 
        'COLLECTOR_TRMT_BIZ_NAME'	, COLLECTOR_TRMT_BIZ_NAME, 
        'AVATAR_PATH'				, AVATAR_PATH, 
        'DISPOSER_WSTE_LIST'		, DISPOSER_WSTE_LIST, 
		'STATE'						, STATE, 
		'STATE_CODE'				, STATE_CODE, 
		'STATE_CATEGORY_ID'			, STATE_CATEGORY_ID, 
		'STATE_CATEGORY'			, STATE_CATEGORY
	)) 
    INTO OUT_DETAILS 
    FROM ORDER_DETAILS_T252_TEMP;
	DROP TABLE IF EXISTS ORDER_DETAILS_T252_TEMP;
END