CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_req_parent_comp_id`(
	IN IN_COMP_ID		BIGINT,
    OUT OUT_PARENT_ID	BIGINT
)
BEGIN
	SELECT P_COMP_ID INTO OUT_PARENT_ID FROM COMPANY WHERE ID = IN_COMP_ID;
END