CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_req_user_class_by_user_reg_id`(
	IN IN_USER_ID		BIGINT,
    OUT OUT_USER_CLASS	INT
)
BEGIN
	SELECT CLASS INTO OUT_USER_CLASS FROM USERS WHERE ID = IN_USER_ID;
END