CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_req_site_id_of_transaction_id`(
	IN IN_TRANSACTION_ID			BIGINT,
    OUT OUT_DISPOER_SITE_ID			BIGINT,
    OUT OUT_COLLECTOR_SITE_ID		BIGINT
)
BEGIN

/*
Procedure Name 	: sp_req_site_id_of_transaction_id
Input param 	: 1개
Output param 	: 1개
Job 			: CIN_TRANSACTION_ID로 해당 폐기물 처리 작업중인 사이트의 고유등록번호를 반환한다.
Update 			: 2022.01.25
Version			: 0.0.1
AUTHOR 			: Leo Nam
*/
/*
	SELECT DISPOSER_SITE_ID, COLLECTOR_SITE_ID, COLLECTOR_BIDDING_ID 
    INTO @DISPOER_SITE_ID, @COLLECTOR_SITE_ID, @COLLECTOR_BIDDING_ID
    FROM WSTE_CLCT_TRMT_TRANSACTION 
    WHERE TRANSACTION_ID = IN_TRANSACTION_ID;
*/
	SELECT B.SITE_ID, C.COLLECTOR_ID, D.ID 
    INTO OUT_DISPOER_SITE_ID, @COLLECTOR_SITE_ID_IN_DIRECTLY, @COLLECTOR_SITE_ID_OVER_BIDDING
    FROM WSTE_CLCT_TRMT_TRANSACTION A 
    LEFT JOIN SITE_WSTE_DISPOSAL_ORDER B ON A.DISPOSAL_ORDER_ID = B.ID
    LEFT JOIN COLLECTOR_BIDDING C ON A.COLLECTOR_BIDDING_ID = C.ID
    LEFT JOIN COMP_SITE D ON A.COLLECTOR_SITE_ID = D.ID
    WHERE A.ID = IN_TRANSACTION_ID;
    
    IF @COLLECTOR_SITE_ID_IN_DIRECTLY IS NOT NULL THEN
    /*기존거래인 경우*/
		SET OUT_COLLECTOR_SITE_ID = @COLLECTOR_SITE_ID_IN_DIRECTLY;
    ELSE
    /*입찰거래인 경우*/
		SET OUT_COLLECTOR_SITE_ID = @COLLECTOR_SITE_ID_OVER_BIDDING;
    END IF;
END