CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_req_comp_id_of_user`(
	IN IN_USER_REG_ID		VARCHAR(50),
    OUT OUT_BELONG_TO		BIGINT
)
BEGIN
	SELECT BELONG_TO INTO OUT_BELONG_TO FROM USERS WHERE USER_ID = IN_USER_REG_ID;
END