CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_req_disposal_order_details`(
	IN IN_DISPOSER_ORDER_ID							BIGINT
)
BEGIN

/*
Procedure Name 	: sp_req_disposal_order_details
Input param 	: 1개
Job 			: 배출자의 배출신청에 대한 입찰 상세정보
Update 			: 2022.02.15
Version			: 0.0.4
AUTHOR 			: Leo Nam
*/

    DECLARE vRowCount 								INT DEFAULT 0;
    DECLARE endOfRow 								TINYINT DEFAULT FALSE;    
    DECLARE CUR_DISPOSER_ORDER_ID					BIGINT;
    DECLARE CUR_DISPOSER_ORDER_CODE					VARCHAR(10);
    DECLARE CUR_DISPOSER_SITE_ID					BIGINT;
    DECLARE CUR_DISPOSER_SITE_SI_DO					VARCHAR(20);
    DECLARE CUR_DISPOSER_SITE_SI_GUN_GU				VARCHAR(20);
    DECLARE CUR_DISPOSER_SITE_EUP_MYEON_DONG		VARCHAR(20);
    DECLARE CUR_DISPOSER_SITE_DONG_RI				VARCHAR(20);
    DECLARE CUR_DISPOSER_SITE_ADDR					VARCHAR(255);
    DECLARE CUR_DATE 								DATETIME;	
    DECLARE CUR_STATE								VARCHAR(20);
    DECLARE CUR_STATE_CODE							INT;
    DECLARE TEMP_CURSOR		 						CURSOR FOR 
	SELECT 
		DISPOSER_ORDER_ID, 
		DISPOSER_ORDER_CODE, 
        DISPOSER_SITE_ID,
        DISPOSER_SITE_SI_DO,
        DISPOSER_SITE_SI_GUN_GU,
        DISPOSER_SITE_EUP_MYEON_DONG,
        DISPOSER_SITE_DONG_RI,
        DISPOSER_SITE_ADDR,
		IF (STATE = '기존거래', 
			DISPOSER_UPDATED_AT,
			IF (STATE = '방문중', DISPOSER_VISIT_END_AT, 
				IF (STATE = '입찰중', 
					DISPOSER_BIDDING_END_AT, 
					DISPOSER_CREATED_AT
				)
			)
		), 
        STATE, 
        STATE_CODE
    FROM V_SITE_WSTE_DISPOSAL_ORDER_WITH_STATE
	WHERE DISPOSER_ORDER_ID = IN_DISPOSER_ORDER_ID;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET endOfRow = TRUE;
    
	CREATE TEMPORARY TABLE IF NOT EXISTS CURRENT_STATE (
		DISPOSER_ORDER_ID							BIGINT,
		DISPOSER_ORDER_CODE							VARCHAR(10),
		DISPOSER_SITE_ID							BIGINT,
		DISPOSER_SITE_SI_DO							VARCHAR(20),
		DISPOSER_SITE_SI_GUN_GU						VARCHAR(20),
		DISPOSER_SITE_EUP_MYEON_DONG				VARCHAR(20),
		DISPOSER_SITE_DONG_RI						VARCHAR(20),
		DISPOSER_SITE_ADDR							VARCHAR(255),
		DISPLAY_DATE								DATETIME,
		STATE										VARCHAR(20),
		STATE_CODE									INT,
		DISPOSAL_WSTE_LIST							JSON,
		IMG_LIST									JSON,
		COLLECTOR_INFO								JSON
	);        
	
	OPEN TEMP_CURSOR;	
	cloop: LOOP
		FETCH TEMP_CURSOR 
		INTO 
			CUR_DISPOSER_ORDER_ID,
			CUR_DISPOSER_ORDER_CODE,
			CUR_DISPOSER_SITE_ID,
			CUR_DISPOSER_SITE_SI_DO,
			CUR_DISPOSER_SITE_SI_GUN_GU,
			CUR_DISPOSER_SITE_EUP_MYEON_DONG,
			CUR_DISPOSER_SITE_DONG_RI,
			CUR_DISPOSER_SITE_ADDR,
			CUR_DATE,
			CUR_STATE,
			CUR_STATE_CODE;   
		
		SET vRowCount = vRowCount + 1;
		IF endOfRow THEN
			LEAVE cloop;
		END IF;
		
		INSERT INTO 
		CURRENT_STATE(
			DISPOSER_ORDER_ID, 
			DISPOSER_ORDER_CODE, 
			DISPOSER_SITE_ID, 
			DISPOSER_SITE_SI_DO,
			DISPOSER_SITE_SI_GUN_GU,
			DISPOSER_SITE_EUP_MYEON_DONG,
			DISPOSER_SITE_DONG_RI,
			DISPOSER_SITE_ADDR,
			DISPLAY_DATE, 
			STATE, 
			STATE_CODE
		)
		VALUES(
			CUR_DISPOSER_ORDER_ID, 
			CUR_DISPOSER_ORDER_CODE, 
			CUR_DISPOSER_SITE_ID, 
			DISPOSER_SITE_SI_DO,
			DISPOSER_SITE_SI_GUN_GU,
			DISPOSER_SITE_EUP_MYEON_DONG,
			DISPOSER_SITE_DONG_RI,
			DISPOSER_SITE_ADDR,
			CUR_DATE, 
			CUR_STATE, 
			CUR_STATE_CODE
		);
        /*
		SELECT JSON_ARRAYAGG(
			JSON_OBJECT(
				'ID'							, COLLECTOR_BIDDING_ID, 
                'COLLECTOR_SITE_ID'				, COLLECTOR_SITE_ID, 
                'COLLECTOR_SITE_NM'				, COLLECTOR_SITE_NAME, 
                'BIZ'							, TRMT_BIZ_NM, 
                'DIST'							, STRAIGHT_DISTANCE, 
                'STATE'							, STATE,
                'STATE_CODE'					, STATE_CODE,
                'DISPOSER_SITE_ID'				, DISPOSER_SITE_ID,
                'COLLECTOR_DATE_OF_VISIT'		, COLLECTOR_DATE_OF_VISIT,
                'COLLECTOR_DATE_OF_BIDDING'		, COLLECTOR_DATE_OF_BIDDING,
                'COLLECTOR_SELECTED_AT'			, COLLECTOR_SELECTED_AT,
                'COLLECTOR_MAKE_DECISION_AT'	, COLLECTOR_MAKE_DECISION_AT
			)
		) 
		INTO @COLLECTOR_INFO 
        FROM V_COLLECTOR_BIDDING_WITH_STATE 
        WHERE 
			DISPOSER_ORDER_ID 			= CUR_DISPOSER_ORDER_ID; *//*AND*/
            /*DISPOSER_RESPONSE_VISIT 	<> TRUE AND*/						/* 수거자가 배출자게에게 방문거절을 당하지 않은 상태*/
            /*DISPOSER_REJECT_BIDDING 	<> TRUE;*/						/* 수거자가 배출자게에게 입찰거절을 당하지 않은 상태*/
		/*수거자정보를 JSON형태로 변환한다.*/
        
		SELECT JSON_ARRAYAGG(
			JSON_OBJECT(
				'WSTE_REG_ID'			, WSTE_REG_ID, 
                'DISPOSAL_ORDER_ID'		, DISPOSAL_ORDER_ID, 
                'WSTE_CLASS'			, WSTE_CLASS, 
                'WSTE_CLASS_NM'			, WSTE_CLASS_NM, 
                'WSTE_APPEARANCE_NM'	, WSTE_APPEARANCE_NM, 
                'WSTE_QUANTITY'			, WSTE_QUANTITY, 
                'WSTE_UNIT'				, WSTE_UNIT
			)
		) 
		INTO @DISPOSAL_WSTE_LIST 
        FROM V_WSTE_DISCHARGED_FROM_SITE
        WHERE DISPOSAL_ORDER_ID 		= CUR_DISPOSER_ORDER_ID;
        
		SELECT JSON_ARRAYAGG(
			JSON_OBJECT(
				'FILE_NAME'			, FILE_NAME, 
                'IMG_PATH'			, IMG_PATH, 
                'FILE_SIZE'			, FILE_SIZE
			)
		) 
		INTO @IMG_LIST 
        FROM WSTE_REGISTRATION_PHOTO  
        WHERE DISPOSAL_ORDER_ID 		= CUR_DISPOSER_ORDER_ID;
		
		UPDATE CURRENT_STATE 
        SET 
			COLLECTOR_INFO 				= @COLLECTOR_INFO, 
			DISPOSAL_WSTE_LIST 			= @DISPOSAL_WSTE_LIST, 
			IMG_LIST		 			= @IMG_LIST 
        WHERE DISPOSER_ORDER_ID 		= CUR_DISPOSER_ORDER_ID;
		/*위에서 받아온 JSON 타입 데이타를 비롯한 몇가지의 데이타를 NEW_COMING 테이블에 반영한다.*/
		
	END LOOP;   
	CLOSE TEMP_CURSOR;
	
	SELECT JSON_ARRAYAGG(
		JSON_OBJECT(
			'DISPOSER_ORDER_ID'						, DISPOSER_ORDER_ID, 
            'DISPOSER_ORDER_CODE'					, DISPOSER_ORDER_CODE, 
            'DISPOSER_SITE_ID'						, DISPOSER_SITE_ID, 
            'DISPOSER_SITE_SI_DO'					, DISPOSER_SITE_SI_DO, 
            'DISPOSER_SITE_SI_GUN_GU'				, DISPOSER_SITE_SI_GUN_GU, 
            'DISPOSER_SITE_EUP_MYEON_DONG'			, DISPOSER_SITE_EUP_MYEON_DONG, 
            'DISPOSER_SITE_DONG_RI'					, DISPOSER_SITE_DONG_RI, 
            'DISPOSER_SITE_ADDR'					, DISPOSER_SITE_ADDR, 
            'DISPLAY_DATE'							, DISPLAY_DATE, 
            'STATE'									, STATE, 
            'DISPOSAL_WSTE_LIST'					, DISPOSAL_WSTE_LIST, 
            'IMG_LIST'								, IMG_LIST, 
            'COLLECTOR_INFO'						, COLLECTOR_INFO
		)
	) 
    INTO @json_data FROM CURRENT_STATE;
    
    IF vRowCount = 0 THEN
		SET @rtn_val 					= 27901;
		SET @msg_txt 					= 'No data found';
    ELSE
		SET @rtn_val 					= 0;
		SET @msg_txt 					= 'Success';
    END IF;
	CALL sp_return_results(@rtn_val, @msg_txt, @json_data);    
	DROP TABLE IF EXISTS CURRENT_STATE;
END