CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_req_wste_record`(
	IN IN_WSTE_CLS		VARCHAR(8)
)
BEGIN
	IF IN_WSTE_CLS = '01' THEN
		SELECT * FROM WSTE_CODE WHERE LEFT(CODE, 2) = '91';
    ELSE
		IF IN_WSTE_CLS = '01-01' THEN
			SELECT * FROM WSTE_CODE WHERE LEFT(CODE, 2) = '91' AND CODE <> '91-02-00';
		ELSE
			IF IN_WSTE_CLS = '01-02' THEN
				SELECT * FROM WSTE_CODE WHERE CODE = '91-02-00';
			ELSE
				IF IN_WSTE_CLS = '02' OR IN_WSTE_CLS = '02-01' OR IN_WSTE_CLS = '02-01-01' OR IN_WSTE_CLS = '02-01-02' THEN
					SELECT * FROM WSTE_CODE WHERE LEFT(CODE, 2) = '51';
				ELSE
					IF IN_WSTE_CLS = '02-02' THEN
						SELECT * FROM WSTE_CODE WHERE LEFT(CODE, 2) = '40';
					ELSE
						IF IN_WSTE_CLS = '02-03' THEN
							SELECT * FROM WSTE_CODE WHERE CAST(LEFT(CODE, 2) AS UNSIGNED) <= 30 AND CAST(LEFT(CODE, 2) AS UNSIGNED) <> 10;
						ELSE
							IF IN_WSTE_CLS = '02-03-01' THEN
								SELECT * FROM WSTE_CODE WHERE CAST(LEFT(CODE, 2) AS UNSIGNED) <= 30 AND CAST(LEFT(CODE, 2) AS UNSIGNED) <> 10;
							ELSE
								IF IN_WSTE_CLS = '02-03-02' THEN
									SELECT * FROM WSTE_CODE WHERE CAST(LEFT(CODE, 2) AS UNSIGNED) <= 30 AND CAST(LEFT(CODE, 2) AS UNSIGNED) <> 10;
								ELSE
									IF IN_WSTE_CLS = '02-03-03' THEN
										SELECT * FROM WSTE_CODE WHERE CAST(LEFT(CODE, 2) AS UNSIGNED) = 10;
									ELSE
										SELECT @rtn_val = 20000;
									END IF;
								END IF;
							END IF;
						END IF;
					END IF;
				END IF;
			END IF;
		END IF;
    END IF;
END