CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_retrieve_collection_request`(
	IN IN_USER_ID							BIGINT
)
BEGIN

/*
Procedure Name 	: sp_retrieve_collection_request
Input param 	: 1개
Job 			: 수거자가 배출자의 수거요청목록을 열람한다
Update 			: 2022.04.12
Version			: 0.0.1
AUTHOR 			: Leo Nam
*/

    DECLARE vRowCount 							INT DEFAULT 0;
    DECLARE endOfRow 							TINYINT DEFAULT FALSE;    
    DECLARE CUR_TRANSACTION_ID					BIGINT; 
    DECLARE CUR_USER_ID							BIGINT;
    DECLARE CUR_COLLECTOR_SITE_ID				BIGINT;
    DECLARE CUR_DISPOSER_ORDER_ID				BIGINT;
    DECLARE CUR_DISPOSER_USER_ID				BIGINT;
    DECLARE CUR_DISPOSER_SITE_ID				BIGINT;
    DECLARE CUR_STATE							VARCHAR(20);
    DECLARE CUR_STATE_CODE						INT;
    DECLARE TEMP_CURSOR		 					CURSOR FOR 
	SELECT 
		A.ID, 
        B.ID, 
        A.COLLECTOR_SITE_ID, 
        A.DISPOSAL_ORDER_ID, 
        E.ID, 
        E.AFFILIATED_SITE,
        C.STATE,
        C.STATE_CODE
    FROM WSTE_CLCT_TRMT_TRANSACTION A
    LEFT JOIN USERS B ON A.COLLECTOR_SITE_ID = B.AFFILIATED_SITE
    LEFT JOIN V_TRANSACTION_STATE_NAME C ON A.ID = C.TRANSACTION_ID
    LEFT JOIN SITE_WSTE_DISPOSAL_ORDER D ON A.DISPOSAL_ORDER_ID = D.ID
    LEFT JOIN USERS E ON D.DISPOSER_ID = E.ID
	WHERE 
        A.IN_PROGRESS = TRUE AND
        (B.CLASS = 201 OR B.CLASS = 202) AND
        B.ACTIVE = TRUE AND
        C.STATE_CODE NOT IN (246, 250, 251) AND
        B.ID = IN_USER_ID;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET endOfRow = TRUE;
            
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		ROLLBACK;
		DROP TABLE IF EXISTS RETRIEVE_COLLECTION_REQUEST_TEMP;
		SET @json_data 		= NULL;
		CALL sp_return_results(@rtn_val, @msg_txt, @json_data);
	END;        
	START TRANSACTION;	   
    /*트랜잭션 시작*/  
    
	CREATE TEMPORARY TABLE IF NOT EXISTS RETRIEVE_COLLECTION_REQUEST_TEMP (
		TRANSACTION_ID							BIGINT,
		USER_ID									BIGINT,
		COLLECTOR_SITE_ID						BIGINT,
        DISPOSER_ORDER_ID						BIGINT,
        DISPOSER_USER_ID						BIGINT,
        DISPOSER_SITE_ID						BIGINT,
        STATE									VARCHAR(20),
        STATE_CODE								BIGINT,
        DISPOSER_IMG_INFO						JSON,
        DISPOSER_WSTE_INFO						JSON,
        DISPOSER_ORDER_INFO						JSON,
        DISPLAY_DATE							DATETIME
        
	);        
	
	OPEN TEMP_CURSOR;	
	cloop: LOOP
		
		FETCH TEMP_CURSOR 
		INTO 
			CUR_TRANSACTION_ID,
			CUR_USER_ID,
			CUR_COLLECTOR_SITE_ID,
			CUR_DISPOSER_ORDER_ID,
			CUR_DISPOSER_USER_ID,
			CUR_DISPOSER_SITE_ID,
            CUR_STATE,
            CUR_STATE_CODE;
		
		SET vRowCount = vRowCount + 1;
		IF endOfRow THEN
			LEAVE cloop;
		END IF;
		
		INSERT INTO 
		RETRIEVE_COLLECTION_REQUEST_TEMP(
			TRANSACTION_ID, 
			USER_ID, 
			COLLECTOR_SITE_ID,
			DISPOSER_ORDER_ID,
			DISPOSER_USER_ID,
			DISPOSER_SITE_ID,
            STATE,
            STATE_CODE
		)
		VALUES(
			CUR_TRANSACTION_ID,
			CUR_USER_ID,
			CUR_COLLECTOR_SITE_ID,
			CUR_DISPOSER_ORDER_ID,
			CUR_DISPOSER_USER_ID,
			CUR_DISPOSER_SITE_ID,
            CUR_STATE,
            CUR_STATE_CODE
		);
        
        CALL sp_get_disposal_img_lists(
			CUR_DISPOSER_ORDER_ID,
            '입찰',
            @DISPOSER_IMG_INFO
        );
        
        CALL sp_get_disposal_wste_lists(
			CUR_DISPOSER_ORDER_ID,
            @DISPOSER_WSTE_INFO
        );
        
        CALL sp_get_disposal_order_info(
			CUR_DISPOSER_ORDER_ID,
            @DISPOSER_ORDER_INFO
        );
            
		CALL sp_set_display_time_for_transaction(
			CUR_TRANSACTION_ID,
            CUR_STATE_CODE,
			@DISPLAY_DATE
		);
        
        UPDATE RETRIEVE_COLLECTION_REQUEST_TEMP
        SET 
			DISPOSER_IMG_INFO 	= @DISPOSER_IMG_INFO,
			DISPOSER_WSTE_INFO	= @DISPOSER_WSTE_INFO,
			DISPOSER_ORDER_INFO	= @DISPOSER_ORDER_INFO,
			DISPLAY_DATE 		= @DISPLAY_DATE
        WHERE TRANSACTION_ID 	= CUR_TRANSACTION_ID;
	END LOOP;   
	CLOSE TEMP_CURSOR;
	
	SELECT JSON_ARRAYAGG(JSON_OBJECT(
		'TRANSACTION_ID'				, TRANSACTION_ID, 
        'USER_ID'						, USER_ID, 
        'COLLECTOR_SITE_ID'				, COLLECTOR_SITE_ID, 
        'DISPOSER_ORDER_ID'				, DISPOSER_ORDER_ID, 
        'DISPOSER_USER_ID'				, DISPOSER_USER_ID, 
        'DISPOSER_SITE_ID'				, DISPOSER_SITE_ID, 
        'STATE'							, STATE, 
        'STATE_CODE'					, STATE_CODE, 
        'DISPOSER_IMG_INFO'				, DISPOSER_IMG_INFO, 
        'DISPOSER_WSTE_INFO'			, DISPOSER_WSTE_INFO, 
        'DISPOSER_ORDER_INFO'			, DISPOSER_ORDER_INFO, 
        'DISPLAY_DATE'					, DISPLAY_DATE
	)) 
    INTO @json_data FROM RETRIEVE_COLLECTION_REQUEST_TEMP;
    
    IF vRowCount = 0 THEN
		SET @rtn_val = 37401;
		SET @msg_txt = 'No data found';
		SIGNAL SQLSTATE '23000';
    ELSE
		SET @rtn_val = 0;
		SET @msg_txt = 'Success';
    END IF;
	DROP TABLE IF EXISTS RETRIEVE_COLLECTION_REQUEST_TEMP;
    COMMIT;
	CALL sp_return_results(@rtn_val, @msg_txt, @json_data);
END