CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_req_order_details_118`(
	IN IN_ORDER_ID				BIGINT,
    OUT OUT_DETAILS				JSON
)
BEGIN
	CREATE TEMPORARY TABLE IF NOT EXISTS ORDER_DETAILS_118_TEMP (
		ORDER_ID							BIGINT,
		ORDER_CODE							VARCHAR(10),
        COLLECTOR_SITE_ID					BIGINT,
        COLLECTOR_SITE_NAME					VARCHAR(255),
		COLLECTOR_TRMT_BIZ_CODE				VARCHAR(4),    
		COLLECTOR_TRMT_BIZ_NAME				VARCHAR(255),  
        AVATAR_PATH							VARCHAR(255),
		COLLECTOR_BIDDING_ID				BIGINT,
		DISPOSER_WSTE_LIST					JSON,
        STATE_CODE							INT,
        STATE								VARCHAR(20),
        STATE_CATEGORY_ID					INT,
        STATE_CATEGORY						VARCHAR(20)
        
	);        
    
    INSERT INTO ORDER_DETAILS_118_TEMP(
		ORDER_ID, 
        ORDER_CODE, 
        COLLECTOR_SITE_ID, 
        COLLECTOR_SITE_NAME, 
        COLLECTOR_TRMT_BIZ_CODE, 
        COLLECTOR_TRMT_BIZ_NAME, 
        AVATAR_PATH, 
        COLLECTOR_BIDDING_ID
    )
    SELECT 
		A.ID,
        A.ORDER_CODE,
        D.ID,
        D.SITE_NAME,
        D.TRMT_BIZ_CODE,
        E.NAME,
        F.AVATAR_PATH,
        C.ID
    FROM SITE_WSTE_DISPOSAL_ORDER A
    LEFT JOIN WSTE_CLCT_TRMT_TRANSACTION B ON A.ID = B.DISPOSAL_ORDER_ID
    LEFT JOIN COLLECTOR_BIDDING C ON B.COLLECTOR_BIDDING_ID = C.ID
    LEFT JOIN COMP_SITE D ON C.COLLECTOR_ID = D.ID
    LEFT JOIN WSTE_TRMT_BIZ E ON D.TRMT_BIZ_CODE = E.CODE
    LEFT JOIN USERS F ON D.ID = F.AFFILIATED_SITE
    LEFT JOIN V_ORDER_STATE G ON A.ID = G.DISPOSER_ORDER_ID
    WHERE 
        F.CLASS = 201 AND
        F.ACTIVE = TRUE AND
        G.STATE_CODE = 118 AND
        A.ID = IN_ORDER_ID;    
	
    CALL sp_get_disposal_wste_lists(
		IN_ORDER_ID,
        @DISPOSER_WSTE_LIST
    );
    
    SELECT COLLECTOR_SITE_ID INTO @SITE_ID
    FROM ORDER_DETAILS_118_TEMP
    WHERE ORDER_ID = IN_ORDER_ID;
        
	CALL sp_get_collector_state(
		IN_ORDER_ID,
		@SITE_ID,
		@STATE,
		@STATE_CODE,
		@STATE_CATEGORY_ID,
		@STATE_CATEGORY
	);
    
    UPDATE ORDER_DETAILS_118_TEMP 
    SET 
		DISPOSER_WSTE_LIST = @DISPOSER_WSTE_LIST
    WHERE ORDER_ID = IN_ORDER_ID;
    
	SELECT JSON_ARRAYAGG(JSON_OBJECT(
		'ORDER_ID'					, ORDER_ID, 
        'ORDER_CODE'				, ORDER_CODE, 
        'COLLECTOR_SITE_ID'			, COLLECTOR_SITE_ID, 
        'COLLECTOR_SITE_NAME'		, COLLECTOR_SITE_NAME, 
        'COLLECTOR_TRMT_BIZ_CODE'	, COLLECTOR_TRMT_BIZ_CODE, 
        'COLLECTOR_TRMT_BIZ_NAME'	, COLLECTOR_TRMT_BIZ_NAME, 
        'AVATAR_PATH'				, AVATAR_PATH, 
        'COLLECTOR_BIDDING_ID'		, COLLECTOR_BIDDING_ID, 
        'DISPOSER_WSTE_LIST'		, DISPOSER_WSTE_LIST, 
		'STATE'						, @STATE, 
		'STATE_CODE'				, @STATE_CODE, 
		'STATE_CATEGORY_ID'			, @STATE_CATEGORY_ID, 
		'STATE_CATEGORY'			, @STATE_CATEGORY
	)) 
    INTO OUT_DETAILS 
    FROM ORDER_DETAILS_118_TEMP;
	DROP TABLE IF EXISTS ORDER_DETAILS_118_TEMP;
END