CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_req_user_type`(
	IN IN_USER_ID				BIGINT,
    OUT OUT_USER_TYPE			VARCHAR(20)
)
BEGIN
	SELECT USER_TYPE INTO OUT_USER_TYPE FROM V_USERS WHERE ID = IN_USER_ID;
END