CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_req_registered_site_lists_without_handler`(
	IN IN_USER_ID			BIGINT,				/*입력값 : 사용자 등록번호(USERS.ID)*/
    IN IN_USER_SITE_ID		BIGINT,	
    OUT rtn_val				INT,
    OUT msg_txt				VARCHAR(200),
    OUT OUT_SITE_LISTS		JSON
)
BEGIN

/*
Procedure Name 	: sp_req_registered_site_lists_without_handler
Input param 	: 3개
Job 			: 등록 사이트를 반환한다.
Update 			: 2022.05.09
Version			: 0.0.1
AUTHOR 			: Leo Nam
*/

    DECLARE vRowCount 							INT DEFAULT 0;
    DECLARE endOfRow 							TINYINT DEFAULT FALSE;  
    DECLARE CUR_COLLECTOR_SITE_ID				BIGINT;
    DECLARE CUR_COUNT_OF_TRANSACTION			INT;
    DECLARE TEMP_CURSOR		 					CURSOR FOR 
	SELECT 
		A.TARGET_ID,
		COUNT(B.ID)
	FROM REGISTERED_SITE A 
	LEFT JOIN TRANSACTION_REPORT B ON A.TARGET_ID = B.COLLECTOR_SITE_ID
	LEFT JOIN COMP_SITE C ON A.TARGET_ID = C.ID
	LEFT JOIN USERS D ON IF(IN_USER_SITE_ID = 0, A.USER_ID = D.ID, A.SITE_ID = D.AFFILIATED_SITE)
	WHERE 
		A.ACTIVE = TRUE AND
		A.DELETED_AT IS NULL AND
        A.REGISTER_TYPE = 1 AND
		C.ACTIVE = TRUE AND
		D.ACTIVE = TRUE AND
		D.ID = IN_USER_ID
	GROUP BY 
		A.TARGET_ID;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET endOfRow = TRUE;
    
	CREATE TEMPORARY TABLE IF NOT EXISTS PREV_TRANSACTION_SITE_LIST_TEMP (
		COLLECTOR_SITE_ID				BIGINT,
		CATEGORY						TINYINT,
		COUNT_OF_TRANSACTION			INT,
        COLLECTOR_INFO					JSON,
        REPORT_CONFIRMED_AT				DATETIME
	);        
	
	OPEN TEMP_CURSOR;	
	cloop: LOOP
		FETCH TEMP_CURSOR 
		INTO 
			CUR_COLLECTOR_SITE_ID,
			CUR_COUNT_OF_TRANSACTION;
		
		SET vRowCount = vRowCount + 1;
		IF endOfRow THEN
			LEAVE cloop;
		END IF;
		
		INSERT INTO 
		PREV_TRANSACTION_SITE_LIST_TEMP(
			COLLECTOR_SITE_ID,
			CATEGORY,
			COUNT_OF_TRANSACTION
		)
		VALUES(
			CUR_COLLECTOR_SITE_ID,
			TRUE,
			CUR_COUNT_OF_TRANSACTION
		);		
        
        CALL sp_get_site_info(
			CUR_COLLECTOR_SITE_ID,
            @COLLECTOR_INFO
        );	
        
        CALL sp_get_last_report_confirmed_at(
			IN_USER_ID,
			CUR_COLLECTOR_SITE_ID,
            @REPORT_CONFIRMED_AT
        );
        
		UPDATE PREV_TRANSACTION_SITE_LIST_TEMP 
        SET 
			COLLECTOR_INFO 			= @COLLECTOR_INFO,
			REPORT_CONFIRMED_AT 	= @REPORT_CONFIRMED_AT
		WHERE COLLECTOR_SITE_ID		= CUR_COLLECTOR_SITE_ID;
	END LOOP;   
	CLOSE TEMP_CURSOR;
    
    IF vRowCount = 0 THEN
		SET rtn_val 				= 29701;
		SET msg_txt 				= 'No data found';
		SET OUT_SITE_LISTS 				= NULL;
    ELSE
		SET rtn_val 				= 0;
		SET msg_txt 				= 'Success';	
		SELECT JSON_ARRAYAGG(
			JSON_OBJECT(
				'COLLECTOR_SITE_ID'				, COLLECTOR_SITE_ID, 
				'CATEGORY'						, CATEGORY,
				'COUNT_OF_TRANSACTION'			, COUNT_OF_TRANSACTION,
				'REPORT_CONFIRMED_AT'			, REPORT_CONFIRMED_AT,
				'COLLECTOR_INFO'				, COLLECTOR_INFO
			)
		) 
		INTO OUT_SITE_LISTS 
		FROM PREV_TRANSACTION_SITE_LIST_TEMP;
    END IF; 
	DROP TABLE IF EXISTS PREV_TRANSACTION_SITE_LIST_TEMP;
END