CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_req_site_id_of_disposal_order_id`(
	IN IN_DISPOSER_ORDER_ID				BIGINT,
    OUT	OUT_SITE_ID						BIGINT
)
BEGIN
	SELECT SITE_ID INTO OUT_SITE_ID FROM SITE_WSTE_DISPOSAL_ORDER WHERE ID = IN_DISPOSER_ORDER_ID;
END