CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_req_wste_list_by_wste_class`(
	IN IN_WSTE_CLS		VARCHAR(8)
)
BEGIN    
	SET @rtn_val = 0;
	SET @msg_txt = 'Success';
	IF IN_WSTE_CLS = '01' THEN
		SELECT JSON_ARRAYAGG(JSON_OBJECT('WSTE_CODE', CODE, 'WSTE_NM', NAME)) INTO @json_data FROM WSTE_CODE WHERE LEFT(CODE, 2) = '91';
    ELSE
		IF IN_WSTE_CLS = '01-01' THEN
            SELECT JSON_ARRAYAGG(JSON_OBJECT('WSTE_CODE', CODE, 'WSTE_NM', NAME)) INTO @json_data FROM WSTE_CODE WHERE LEFT(CODE, 2) = '91' AND CODE <> '91-02-00';
		ELSE
			IF IN_WSTE_CLS = '01-02' THEN
				SELECT JSON_ARRAYAGG(JSON_OBJECT('WSTE_CODE', CODE, 'WSTE_NM', NAME)) INTO @json_data FROM WSTE_CODE WHERE CODE = '91-02-00';
			ELSE
				IF IN_WSTE_CLS = '02' OR IN_WSTE_CLS = '02-01' OR IN_WSTE_CLS = '02-01-01' OR IN_WSTE_CLS = '02-01-02' THEN
					SELECT JSON_ARRAYAGG(JSON_OBJECT('WSTE_CODE', CODE, 'WSTE_NM', NAME)) INTO @json_data FROM WSTE_CODE WHERE LEFT(CODE, 2) = '51';
				ELSE
					IF IN_WSTE_CLS = '02-02' THEN
						SELECT JSON_ARRAYAGG(JSON_OBJECT('WSTE_CODE', CODE, 'WSTE_NM', NAME)) INTO @json_data FROM WSTE_CODE WHERE LEFT(CODE, 2) = '40';
					ELSE
						IF IN_WSTE_CLS = '02-03' THEN
							SELECT JSON_ARRAYAGG(JSON_OBJECT('WSTE_CODE', CODE, 'WSTE_NM', NAME)) INTO @json_data FROM WSTE_CODE WHERE CAST(LEFT(CODE, 2) AS UNSIGNED) <= 30 AND CAST(LEFT(CODE, 2) AS UNSIGNED) <> 10;
						ELSE
							IF IN_WSTE_CLS = '02-03-01' THEN
								SELECT JSON_ARRAYAGG(JSON_OBJECT('WSTE_CODE', CODE, 'WSTE_NM', NAME)) INTO @json_data FROM WSTE_CODE WHERE CAST(LEFT(CODE, 2) AS UNSIGNED) <= 30 AND CAST(LEFT(CODE, 2) AS UNSIGNED) <> 10;
							ELSE
								IF IN_WSTE_CLS = '02-03-02' THEN
									SELECT JSON_ARRAYAGG(JSON_OBJECT('WSTE_CODE', CODE, 'WSTE_NM', NAME)) INTO @json_data FROM WSTE_CODE WHERE CAST(LEFT(CODE, 2) AS UNSIGNED) <= 30 AND CAST(LEFT(CODE, 2) AS UNSIGNED) <> 10;
								ELSE
									IF IN_WSTE_CLS = '02-03-03' THEN
                                        SELECT JSON_ARRAYAGG(JSON_OBJECT('WSTE_CODE', CODE, 'WSTE_NM', NAME)) INTO @json_data FROM WSTE_CODE WHERE CAST(LEFT(CODE, 2) AS UNSIGNED) = 10;
									ELSE
										SET @rtn_val = 29201;
										SET @msg_txt = 'Invalid waste code';
										SET @json_data = NULL;
									END IF;
								END IF;
							END IF;
						END IF;
					END IF;
				END IF;
			END IF;
		END IF;
    END IF;
	
	CALL sp_return_results(@rtn_val, @msg_txt, @json_data);
	DROP TABLE IF EXISTS CURRENT_STATE;
END