CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_req_site_close_visiting_early`(
	IN IN_DISPOSER_ORDER_ID			BIGINT,
    OUT OUT_CLOSED_EARLY			TINYINT
)
BEGIN
	SELECT VISIT_EARLY_CLOSING INTO @SITE_CLOSED_EARLY FROM SITE_WSTE_DISPOSAL_ORDER WHERE ID = IN_DISPOSER_ORDER_ID;
    IF @SITE_CLOSED_EARLY IS NULL OR @SITE_CLOSED_EARLY = FALSE THEN
		SET OUT_CLOSED_EARLY = FALSE;
    ELSE
		SET OUT_CLOSED_EARLY = TRUE;
    END IF;
END