CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_req_order_details_110`(
	IN IN_ORDER_ID				BIGINT,
    OUT OUT_DETAILS				JSON
)
BEGIN
	CREATE TEMPORARY TABLE IF NOT EXISTS ORDER_DETAILS_110_TEMP (
		ORDER_ID							BIGINT,
		ORDER_CODE							VARCHAR(10),
        BIDDING_RANK						INT,
        COLLECTOR_SITE_ID					BIGINT,
        COLLECTOR_SITE_NAME					VARCHAR(255),
		COLLECTOR_TRMT_BIZ_CODE				VARCHAR(4),    
		COLLECTOR_TRMT_BIZ_NAME				VARCHAR(255),  
		COLLECTOR_BIDDING_ID				BIGINT,
        AVATAR_PATH							VARCHAR(255),
		DISPOSER_WSTE_LIST					JSON,
        STATE_CODE							INT,
        STATE								VARCHAR(20),
        STATE_CATEGORY_ID					INT,
        STATE_CATEGORY						VARCHAR(20)
        
	);        
    
	SET @FIRST_PLACE = NULL; 
    SET @MAX_SELECT_AT = NULL;
    SET @SITE_ID = NULL;
    SET @SITE_NAME = NULL;
    SET @TRMT_BIZ_CODE = NULL;
    SET @TRMT_BIZ_NAME = NULL;
    SET @COLLECTOR_BIDDING_ID = NULL;
    SET @STATE_CODE = NULL;
    SET @STATE = NULL;
    SET @STATE_CATEGORY_ID = NULL;
    SET @STATE_CATEGORY = NULL;
    CALL sp_req_current_time(@REG_DT);
    
    INSERT INTO ORDER_DETAILS_110_TEMP(
		ORDER_ID, 
        ORDER_CODE
    )
    SELECT 
		ID,
        ORDER_CODE
    FROM SITE_WSTE_DISPOSAL_ORDER
    WHERE ID = IN_ORDER_ID;  
    
    SELECT 
		A.FIRST_PLACE, 
        A.MAX_SELECT_AT, 
        B.COLLECTOR_ID,
        C.SITE_NAME,
        C.TRMT_BIZ_CODE,
        D.NAME,
        B.ID
    INTO 
		@FIRST_PLACE, 
        @MAX_SELECT_AT, 
        @SITE_ID,
        @SITE_NAME,
        @TRMT_BIZ_CODE,
        @TRMT_BIZ_NAME,
        @COLLECTOR_BIDDING_ID
    FROM SITE_WSTE_DISPOSAL_ORDER A
    LEFT JOIN COLLECTOR_BIDDING B ON A.FIRST_PLACE = B.ID
    LEFT JOIN COMP_SITE C ON B.COLLECTOR_ID = C.ID
    LEFT JOIN WSTE_TRMT_BIZ D ON C.TRMT_BIZ_CODE = D.CODE
    WHERE A.ID = IN_ORDER_ID;
    
    SELECT AVATAR_PATH INTO @AVATAR_PATH
    FROM USERS
    WHERE 
		AFFILIATED_SITE = @SITE_ID AND
        CLASS = 201 AND
        ACTIVE = TRUE;
	
    CALL sp_get_disposal_wste_lists(
		IN_ORDER_ID,
        @DISPOSER_WSTE_LIST
    );
        
	CALL sp_get_collector_state(
		IN_ORDER_ID,
		@SITE_ID,
		@STATE,
		@STATE_CODE,
		@STATE_CATEGORY_ID,
		@STATE_CATEGORY
	);
    
    UPDATE ORDER_DETAILS_110_TEMP 
    SET 
		BIDDING_RANK 				= @BIDDING_RANK, 
		COLLECTOR_SITE_ID 			= @SITE_ID,
		COLLECTOR_SITE_NAME 		= @SITE_NAME, 
		COLLECTOR_TRMT_BIZ_CODE 	= @TRMT_BIZ_CODE, 
		COLLECTOR_TRMT_BIZ_NAME 	= @TRMT_BIZ_NAME, 
		AVATAR_PATH 				= @AVATAR_PATH, 
		COLLECTOR_BIDDING_ID 		= @COLLECTOR_BIDDING_ID, 
		DISPOSER_WSTE_LIST 			= @DISPOSER_WSTE_LIST,
		STATE 						= @STATE,
		STATE_CODE 					= @STATE_CODE,
		STATE_CATEGORY_ID 			= @STATE_CATEGORY_ID,
		STATE_CATEGORY 				= @STATE_CATEGORY 
    WHERE ORDER_ID = IN_ORDER_ID;
    
	SELECT JSON_ARRAYAGG(JSON_OBJECT(
		'ORDER_ID'					, ORDER_ID, 
        'ORDER_CODE'				, ORDER_CODE, 
        'BIDDING_RANK'				, BIDDING_RANK, 
        'COLLECTOR_SITE_ID'			, COLLECTOR_SITE_ID, 
        'COLLECTOR_SITE_NAME'		, COLLECTOR_SITE_NAME, 
        'COLLECTOR_TRMT_BIZ_CODE'	, COLLECTOR_TRMT_BIZ_CODE, 
        'COLLECTOR_TRMT_BIZ_NAME'	, COLLECTOR_TRMT_BIZ_NAME, 
        'AVATAR_PATH'				, AVATAR_PATH, 
        'COLLECTOR_BIDDING_ID'		, COLLECTOR_BIDDING_ID, 
        'DISPOSER_WSTE_LIST'		, DISPOSER_WSTE_LIST, 
		'STATE'						, STATE, 
		'STATE_CODE'				, STATE_CODE, 
		'STATE_CATEGORY_ID'			, STATE_CATEGORY_ID, 
		'STATE_CATEGORY'			, STATE_CATEGORY
	)) 
    INTO OUT_DETAILS 
    FROM ORDER_DETAILS_110_TEMP;
	DROP TABLE IF EXISTS ORDER_DETAILS_110_TEMP;
END