CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_retrieve_sites_that_can_bid`(
	IN IN_DISPOSER_ORDER_ID					BIGINT,
    OUT rtn_val								INT,
    OUT msg_txt								VARCHAR(200),
    OUT json_data							JSON
)
BEGIN

/*
Procedure Name 	: sp_retrieve_sites_that_can_bid
Input param 	: 1개
Output param 	: 3개
Job 			: 투찰가능 수거업체 리스트 반환
Update 			: 2022.03.17
Version			: 0.0.1
AUTHOR 			: Leo Nam
*/

    DECLARE vRowCount 								INT DEFAULT 0;
    DECLARE endOfRow 								TINYINT DEFAULT FALSE;    
    DECLARE CUR_COLLECTOR_SITE_ID					BIGINT;
    DECLARE CUR_COLLECTOR_SITE_NAME					VARCHAR(255);
    DECLARE CUR_COLLECTOR_BIDDING_ID				BIGINT;
    DECLARE CUR_TRMT_BIZ_NM							VARCHAR(50);
    DECLARE TEMP_CURSOR		 						CURSOR FOR 
	SELECT 
		COLLECTOR_SITE_ID, 
        COLLECTOR_SITE_NAME, 
        COLLECTOR_BIDDING_ID,
        TRMT_BIZ_NM
    FROM V_COLLECTOR_BIDDING_WITH_STATE
	WHERE 
		DISPOSER_ORDER_ID = IN_DISPOSER_ORDER_ID AND
        (STATE_PID <> 211 AND STATE_CODE <> 211);
            
            
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET endOfRow = TRUE;
    
	CREATE TEMPORARY TABLE IF NOT EXISTS TEMP_BIDDING_ABLED_SITE_LISTS (
		COLLECTOR_SITE_ID					BIGINT,
		COLLECTOR_SITE_NAME					VARCHAR(255),
		COLLECTOR_BIDDING_ID				BIGINT,
		COLLECTOR_TRMT_BIZ_NM				VARCHAR(50),
        COLLECTOR_AVATAR_PATH				VARCHAR(255)
	);        
	
	OPEN TEMP_CURSOR;	
	cloop: LOOP
		FETCH TEMP_CURSOR 
		INTO 
			CUR_COLLECTOR_SITE_ID,
			CUR_COLLECTOR_SITE_NAME,
			CUR_COLLECTOR_BIDDING_ID,    
			CUR_TRMT_BIZ_NM;   
		
		SET vRowCount = vRowCount + 1;
		IF endOfRow THEN
			LEAVE cloop;
		END IF;
		
		INSERT INTO 
		TEMP_BIDDING_ABLED_SITE_LISTS(
			COLLECTOR_SITE_ID, 
			COLLECTOR_SITE_NAME, 
			COLLECTOR_BIDDING_ID,     
			COLLECTOR_TRMT_BIZ_NM
		)
		VALUES(
			CUR_COLLECTOR_SITE_ID, 
			CUR_COLLECTOR_SITE_NAME, 
			CUR_COLLECTOR_BIDDING_ID,     
			CUR_TRMT_BIZ_NM
		);
        
        SELECT A.AVATAR_PATH INTO @COLLECTOR_AVATAR_PATH FROM USERS A LEFT JOIN COMP_SITE B ON A.AFFILIATED_SITE = B.ID WHERE B.ID = CUR_COLLECTOR_SITE_ID AND A.CLASS = 201;		
		UPDATE TEMP_BIDDING_ABLED_SITE_LISTS SET COLLECTOR_AVATAR_PATH = @COLLECTOR_AVATAR_PATH WHERE COLLECTOR_SITE_ID = CUR_COLLECTOR_SITE_ID;
        
		
	END LOOP;   
	CLOSE TEMP_CURSOR;
	
	SELECT JSON_ARRAYAGG(
		JSON_OBJECT(
			'COLLECTOR_SITE_ID'					, COLLECTOR_SITE_ID, 
            'COLLECTOR_SITE_NAME'				, COLLECTOR_SITE_NAME, 
            'COLLECTOR_BIDDING_ID'				, COLLECTOR_BIDDING_ID, 
            'COLLECTOR_TRMT_BIZ_NM'				, COLLECTOR_TRMT_BIZ_NM, 
            'COLLECTOR_AVATAR_PATH'				, COLLECTOR_AVATAR_PATH
		)
	) 
    INTO json_data 
    FROM TEMP_BIDDING_ABLED_SITE_LISTS;
    
    IF vRowCount = 0 THEN
		SET json_data 				= NULL;
		SET rtn_val 				= 34001;
		SET msg_txt 				= 'No data found';
    ELSE
		SET rtn_val 				= 0;
		SET msg_txt 				= 'Success';
    END IF;
	DROP TABLE IF EXISTS TEMP_BIDDING_ABLED_SITE_LISTS;
END