CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_retrieve_my_disposal_details_20220523`(
	IN IN_ORDER_ID					BIGINT,
	OUT OUT_EXISTING_TRANSACTION	TINYINT,
	OUT OUT_STATE_CODE				INT,
    OUT OUT_DETAILS					JSON
)
BEGIN
	DECLARE VAR_ORDER_STATE_CODE				INT DEFAULT NULL;
	DECLARE VAR_TRANSACTION_STATE_CODE			INT DEFAULT NULL;
	DECLARE VAR_IS_EXISTING_TRANSACTION			TINYINT DEFAULT 0;
        
    SELECT 
		A.STATE_CODE, 
        B.TRANSACTION_STATE_CODE,
        IF(B.DISPOSAL_ORDER_ID = IN_ORDER_ID AND 
            B.TRANSACTION_STATE_CODE IN (250, 251, 252) AND
            C.COLLECTOR_ID IS NOT NULL,
            1,
            0
		)
    INTO 
		VAR_ORDER_STATE_CODE, 
        VAR_TRANSACTION_STATE_CODE,
        VAR_IS_EXISTING_TRANSACTION
    FROM V_ORDER_STATE A
    LEFT JOIN V_TRANSACTION_STATE B ON A.DISPOSER_ORDER_ID = B.DISPOSAL_ORDER_ID
    LEFT JOIN SITE_WSTE_DISPOSAL_ORDER C ON A.DISPOSER_ORDER_ID = C.ID
    WHERE (
		A.DISPOSER_ORDER_ID = IN_ORDER_ID OR
        (
			B.DISPOSAL_ORDER_ID = IN_ORDER_ID AND 
            B.TRANSACTION_STATE_CODE IN (250, 251, 252) AND
            C.COLLECTOR_ID IS NOT NULL
		)
	);
    
    SET OUT_EXISTING_TRANSACTION = VAR_IS_EXISTING_TRANSACTION;
    
    IF VAR_IS_EXISTING_TRANSACTION = 0 THEN
		IF VAR_ORDER_STATE_CODE IS NOT NULL THEN
			SET OUT_STATE_CODE = VAR_ORDER_STATE_CODE;
			IF VAR_ORDER_STATE_CODE = 101 THEN		/*방문대기중 => NULL 반환*/
				SET OUT_DETAILS = NULL;
			END IF;
			IF VAR_ORDER_STATE_CODE = 102 THEN		/*방문중*/
				CALL sp_req_order_details_102(
					IN_ORDER_ID,
					OUT_DETAILS
				);
			END IF;
			IF VAR_ORDER_STATE_CODE = 103 THEN		/*입찰중 => 117 사용*/
			/*상태 117과 동일하게 처리함*/
				CALL sp_req_order_details_117(
					IN_ORDER_ID,
					OUT_DETAILS
				);
			END IF;
			IF VAR_ORDER_STATE_CODE = 104 THEN		/*기존거래 => NULL 반환*/
			/*
				CALL sp_req_order_details_104(
					IN_ORDER_ID,
					OUT_DETAILS
				);
			*/
				SET OUT_DETAILS = NULL;
			END IF;
			IF VAR_ORDER_STATE_CODE = 105 THEN		/*거래종료 => NULL 반환*/
				SET OUT_DETAILS = NULL;
			END IF;
			IF VAR_ORDER_STATE_CODE = 106 THEN		/*삭제 => NULL 반환*/
				SET OUT_DETAILS = NULL;
			END IF;
			IF VAR_ORDER_STATE_CODE = 110 THEN		/*선정중*/
				CALL sp_req_order_details_110(
					IN_ORDER_ID,
					OUT_DETAILS
				);
			END IF;
			IF VAR_ORDER_STATE_CODE = 115 THEN		/*승인포기종료 => NULL 반환*/
				SET OUT_DETAILS = NULL;
			END IF;
			IF VAR_ORDER_STATE_CODE = 116 THEN		/*무방문신청종료 => NULL 반환*/
				SET OUT_DETAILS = NULL;
			END IF;
			IF VAR_ORDER_STATE_CODE = 117 THEN		/*무입찰종료*/
			/*방문자수와 입찰자수를 반환한다.*/
				CALL sp_req_order_details_117(
					IN_ORDER_ID,
					OUT_DETAILS
				);
			END IF;
			IF VAR_ORDER_STATE_CODE = 118 THEN		/*처리중 => NULL 반환*/
				CALL sp_req_order_details_118(
					IN_ORDER_ID,
					OUT_DETAILS
				);
			END IF;
			IF VAR_ORDER_STATE_CODE = 119 THEN		/*확인중(선정수락대기중[new plan])*/
				CALL sp_req_order_details_119(
					IN_ORDER_ID,
					OUT_DETAILS
				);
			END IF;
			IF VAR_ORDER_STATE_CODE = 121 THEN		/*확인포기종료 => NULL 반환*/
				SET OUT_DETAILS = NULL;
			END IF;
			IF VAR_ORDER_STATE_CODE = 122 THEN		/*기존거래거절종료 => NULL 반환*/
				SET OUT_DETAILS = NULL;
			END IF;
		ELSE
			SET OUT_DETAILS = NULL;
		END IF;
    ELSE
		SET OUT_DETAILS = NULL;
		SET OUT_STATE_CODE = VAR_TRANSACTION_STATE_CODE;
		IF VAR_TRANSACTION_STATE_CODE = 252 THEN
			CALL sp_req_order_details_t252(
				IN_ORDER_ID,
				OUT_DETAILS
			);
		END IF;
		IF VAR_TRANSACTION_STATE_CODE = 250 OR VAR_TRANSACTION_STATE_CODE = 251 THEN
			SET OUT_DETAILS = NULL;
		END IF;
    END IF;

END