CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_req_user_class`(
	IN IN_USER_REG_ID		VARCHAR(50),
    OUT OUT_USER_CLASS	INT
)
BEGIN
	SELECT CLASS INTO OUT_USER_CLASS FROM USERS WHERE USER_ID = IN_USER_REG_ID;
END