CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_set_display_time`(
	IN IN_DISPOSER_ORDER_ID			BIGINT,
	IN IN_STATE_CATEGORY_ID			INT,
    OUT OUT_DISPLAY_TIME			DATETIME
)
BEGIN
	SELECT 
	CASE
		WHEN IN_STATE_CATEGORY_ID = 2
			THEN (
				SELECT 
					IF(VISIT_START_AT IS NOT NULL, 
						IF(VISIT_START_AT <= NOW(), 
							VISIT_END_AT, 
							VISIT_START_AT
						),
						VISIT_END_AT
					) 
				FROM SITE_WSTE_DISPOSAL_ORDER 
				WHERE ID = IN_DISPOSER_ORDER_ID
			)
		WHEN IN_STATE_CATEGORY_ID = 3
			THEN (
				SELECT BIDDING_END_AT
				FROM SITE_WSTE_DISPOSAL_ORDER 
				WHERE ID = IN_DISPOSER_ORDER_ID
			)
		WHEN IN_STATE_CATEGORY_ID = 4
			THEN (
				SELECT MAX_SELECT_AT FROM SITE_WSTE_DISPOSAL_ORDER 
				WHERE ID = IN_DISPOSER_ORDER_ID
			)
		WHEN IN_STATE_CATEGORY_ID = 5
			THEN (
				SELECT 
					IF(COLLECTOR_SELECTION_CONFIRMED IS NOT NULL,
						IF(COLLECTOR_SELECTION_CONFIRMED = TRUE,
							UPDATED_AT,
							IF(BIDDERS > 1,
								IF(COLLECTOR_SELECTION_CONFIRMED2 IS NOT NULL,
									UPDATED_AT,
									COLLECTOR_MAX_DECISION2_AT
								),
								UPDATED_AT
							)
						),
						IF(COLLECTOR_MAX_DECISION_AT <= NOW(),
							IF(BIDDERS > 1,
								IF(COLLECTOR_SELECTION_CONFIRMED2 IS NOT NULL,
									UPDATED_AT,
									COLLECTOR_MAX_DECISION2_AT
								),
								UPDATED_AT
							),
							COLLECTOR_MAX_DECISION_AT
						)
					)
				FROM SITE_WSTE_DISPOSAL_ORDER 
				WHERE ID = IN_DISPOSER_ORDER_ID
			)
		WHEN IN_STATE_CATEGORY_ID = 6
			THEN (
				SELECT 
					IF(A.COLLECT_ASK_END_AT <= NOW(), 
						B.CLOSE_AT,
						A.COLLECT_ASK_END_AT
					) 
				FROM WSTE_CLCT_TRMT_TRANSACTION A 
                LEFT JOIN SITE_WSTE_DISPOSAL_ORDER B ON A.DISPOSAL_ORDER_ID = B.ID
				WHERE 
					A.DISPOSAL_ORDER_ID = IN_DISPOSER_ORDER_ID AND
					A.IN_PROGRESS = TRUE
			)
		WHEN IN_STATE_CATEGORY_ID = 7
			THEN (
				SELECT CLOSE_AT
				FROM SITE_WSTE_DISPOSAL_ORDER 
				WHERE ID = IN_DISPOSER_ORDER_ID
			)
		ELSE NULL
	END INTO OUT_DISPLAY_TIME;
END