CREATE DEFINER=`chiumdb`@`%` PROCEDURE `sp_set_site_undeleted`(
	IN IN_REPORT_ID					BIGINT
)
BEGIN
	DECLARE VAR_USER_ID				BIGINT;
	DECLARE VAR_SITE_ID				BIGINT;
    DECLARE VAR_ORDER_ID			BIGINT;
    DECLARE VAR_TARGET_ID			BIGINT;
    
    SELECT DISPOSER_ORDER_ID, DISPOSER_SITE_ID, COLLECTOR_SITE_ID, DISPOSER_MANAGER_ID
    INTO VAR_ORDER_ID, VAR_SITE_ID, VAR_TARGET_ID, VAR_USER_ID
    FROM TRANSACTION_REPORT
    WHERE ID = IN_REPORT_ID;
    
    UPDATE REGISTERED_SITE
    SET ACTIVE = FALSE
    WHERE
		USER_ID = VAR_USER_ID AND
        SITE_ID = VAR_SITE_ID AND
        TARGET_ID = VAR_TARGET_ID AND
        ACTIVE = TRUE AND
        REGISTER_TYPE = 2;
END