CREATE 
    ALGORITHM = UNDEFINED 
    DEFINER = `chiumdb`@`%` 
    SQL SECURITY DEFINER
VIEW `chiumdev_2`.`V_COLLECTOR_BIDDING` AS
    SELECT 
        `A`.`ID` AS `COLLECTOR_BIDDING_ID`,
        `A`.`COLLECTOR_ID` AS `COLLECTOR_SITE_ID`,
        `F`.`SI_DO` AS `COLLECTOR_SI_DO`,
        `F`.`SI_GUN_GU` AS `COLLECTOR_SI_GUN_GU`,
        `F`.`EUP_MYEON_DONG` AS `COLLECTOR_EUP_MYEON_DONG`,
        `F`.`DONG_RI` AS `COLLECTOR_DONG_RI`,
        `D`.`KIKCD_B_CODE` AS `COLLECTOR_KIKCD_B_CODE`,
        `D`.`ADDR` AS `COLLECTOR_ADDR`,
        `D`.`CONTACT` AS `COLLECTOR_CONTACT`,
        `D`.`LAT` AS `COLLECTOR_LAT`,
        `D`.`LNG` AS `COLLECTOR_LNG`,
        `D`.`SITE_NAME` AS `COLLECTOR_SITE_NAME`,
        `D`.`HEAD_OFFICE` AS `COLLECTOR_HEAD_OFFICE`,
        `D`.`TRMT_BIZ_CODE` AS `COLLECTOR_TRMT_BIZ_CODE`,
        `H`.`NAME` AS `TRMT_BIZ_NM`,
        `A`.`BID_AMOUNT` AS `COLLECTOR_BID_AMOUNT`,
        `A`.`GREENHOUSE_GAS` AS `COLLECTOR_GREENHOUSE_GAS`,
        `A`.`WINNER` AS `COLLECTOR_WINNER`,
        `A`.`ACTIVE` AS `COLLECTOR_ACTIVE`,
        `A`.`CANCEL_VISIT` AS `COLLECTOR_CANCEL_VISIT`,
        `A`.`CANCEL_BIDDING` AS `COLLECTOR_CANCEL_BIDDING`,
        `A`.`DATE_OF_VISIT` AS `COLLECTOR_DATE_OF_VISIT`,
        `A`.`DATE_OF_BIDDING` AS `COLLECTOR_DATE_OF_BIDDING`,
        `A`.`SELECTED` AS `COLLECTOR_SELECTED`,
        `A`.`SELECTED_AT` AS `COLLECTOR_SELECTED_AT`,
        `A`.`MAKE_DECISION` AS `COLLECTOR_MAKE_DECISION`,
        `A`.`RESPONSE_VISIT` AS `DISPOSER_RESPONSE_VISIT`,
        `A`.`REJECT_BIDDING` AS `DISPOSER_REJECT_BIDDING`,
        `A`.`RESPONSE_VISIT_AT` AS `DISPOSER_RESPONSE_VISIT_AT`,
        `A`.`REJECT_BIDDING_AT` AS `DISPOSER_REJECT_BIDDING_AT`,
        `A`.`MAKE_DECISION_AT` AS `COLLECTOR_MAKE_DECISION_AT`,
        `A`.`CREATED_AT` AS `COLLECTOR_RECORD_CREATED_AT`,
        `A`.`UPDATED_AT` AS `COLLECTOR_RECORD_UPDATED_AT`,
        `A`.`MAX_DECISION_AT` AS `COLLECTOR_MAX_DECISION_AT`,
        `B`.`ID` AS `DISPOSER_ORDER_ID`,
        `B`.`COLLECTOR_ID` AS `DISPOSER_ORDER_COLLECTOR_ID`,
        `B`.`DISPOSER_TYPE` AS `DISPOSER_TYPE`,
        `B`.`SITE_ID` AS `DISPOSER_SITE_ID`,
        `G`.`SI_DO` AS `DISPOSER_SI_DO`,
        `G`.`SI_GUN_GU` AS `DISPOSER_SI_GUN_GU`,
        `G`.`EUP_MYEON_DONG` AS `DISPOSER_EUP_MYEON_DONG`,
        `G`.`DONG_RI` AS `DISPOSER_DONG_RI`,
        `E`.`KIKCD_B_CODE` AS `DISPOSER_KIKCD_B_CODE`,
        `E`.`ADDR` AS `DISPOSER_ADDR`,
        `E`.`CONTACT` AS `DISPOSER_CONTACT`,
        `E`.`LAT` AS `DISPOSER_LAT`,
        `E`.`LNG` AS `DISPOSER_LNG`,
        `E`.`SITE_NAME` AS `DISPOSER_SITE_NAME`,
        `E`.`HEAD_OFFICE` AS `DISPOSER_HEAD_OFFICE`,
        `E`.`TRMT_BIZ_CODE` AS `DISPOSER_TRMT_BIZ_CODE`,
        `B`.`ACTIVE` AS `DISPOSER_ACTIVE`,
        `B`.`ORDER_CODE` AS `DISPOSER_ORDER_CODE`,
        `B`.`MANAGER_ID` AS `DISPOSER_ORDER_MANAGER_ID`,
        `B`.`VISIT_END_AT` AS `DISPOSER_VISIT_END_AT`,
        `B`.`BIDDING_END_AT` AS `DISPOSER_BIDDING_END_AT`,
        `B`.`OPEN_AT` AS `DISPOSER_OPEN_AT`,
        `B`.`CLOSE_AT` AS `DISPOSER_CLOSE_AT`,
        `B`.`SERVICE_INSTRUCTION_ID` AS `DISPOSER_SERVICE_INSTRUCTION_ID`,
        `B`.`CREATED_AT` AS `DISPOSER_CREATED_AT`,
        `B`.`VISIT_EARLY_CLOSING` AS `DISPOSER_VISIT_EARLY_CLOSING`,
        `B`.`VISIT_EARLY_CLOSED_AT` AS `DISPOSER_VISIT_EARLY_CLOSED_AT`,
        `B`.`UPDATED_AT` AS `DISPOSER_UPDATED_AT`,
        `B`.`BIDDING_EARLY_CLOSING` AS `DISPOSER_BIDDING_EARLY_CLOSING`,
        `B`.`BIDDING_EARLY_CLOSED_AT` AS `DISPOSER_BIDDING_EARLY_CLOSED_AT`,
        `B`.`IS_DELETED` AS `DISPOSER_ORDER_DELETED`,
        `B`.`DELETED_AT` AS `DISPOSER_ORDER_DELETED_AT`,
        `A`.`BIDDING_RANK` AS `BIDDING_RANK`,
        `B`.`FIRST_PLACE` AS `FIRST_PLACE`,
        `B`.`SECOND_PLACE` AS `SECOND_PLACE`,
        `B`.`SELECTED2` AS `DISPOSER_SELECTED2`,
        `B`.`SELECTED2_AT` AS `DISPOSER_SELECTED2_AT`,
        `B`.`COLLECTOR_SELECTION_CONFIRMED2` AS `COLLECTOR_SELECTION_CONFIRMED2`,
        `B`.`COLLECTOR_SELECTION_CONFIRMED2_AT` AS `COLLECTOR_SELECTION_CONFIRMED2_AT`,
        `B`.`MAX_SELECT2_AT` AS `DISPOSER_MAX_SELECT2_AT`,
        `B`.`NOTE` AS `DISPOSER_NOTE`,
        SQRT((POW((`D`.`LAT` - `B`.`LAT`), 2) + POW((`D`.`LNG` - `B`.`LNG`), 2))) AS `STRAIGHT_DISTANCE`,
        IF((`B`.`IS_DELETED` = TRUE),
            214,
            IF((`B`.`VISIT_END_AT` IS NOT NULL),
                IF((`A`.`DATE_OF_VISIT` IS NOT NULL),
                    IF((`A`.`CANCEL_VISIT` = TRUE),
                        202,
                        IF((`A`.`RESPONSE_VISIT` IS NOT NULL),
                            IF((`A`.`RESPONSE_VISIT` = TRUE),
                                IF((`B`.`VISIT_END_AT` <= NOW()),
                                    IF((`A`.`DATE_OF_BIDDING` IS NOT NULL),
                                        IF((`A`.`CANCEL_BIDDING` = TRUE),
                                            207,
                                            IF((`A`.`REJECT_BIDDING` = TRUE),
                                                231,
                                                IF((`B`.`BIDDING_END_AT` <= NOW()),
                                                    IF((`A`.`SELECTED` IS NOT NULL),
                                                        IF((`B`.`SELECTED` = `A`.`ID`),
                                                            IF((`A`.`MAKE_DECISION` IS NOT NULL),
                                                                IF((`A`.`MAKE_DECISION` = TRUE),
                                                                    IF((`A`.`MAX_DECISION_AT` <= NOW()),
                                                                        IF((`B`.`CLOSE_AT` > NOW()), 212, 218),
                                                                        220),
                                                                    210),
                                                                IF((`B`.`MAX_SELECT2_AT` <= NOW()),
                                                                    210,
                                                                    236)),
                                                            IF((`B`.`SECOND_PLACE` = `A`.`ID`),
                                                                IF((`B`.`MAX_SELECT2_AT` <= NOW()),
                                                                    213,
                                                                    233),
                                                                213)),
                                                        IF((`B`.`MAX_SELECT2_AT` <= NOW()),
                                                            213,
                                                            IF((`A`.`BIDDING_RANK` = 1),
                                                                208,
                                                                IF((`A`.`BIDDING_RANK` = 2), 233, 213)))),
                                                    206))),
                                        IF((`B`.`BIDDING_END_AT` <= NOW()),
                                            211,
                                            224)),
                                    IF((`A`.`REJECT_BIDDING_APPLY` = TRUE),
                                        232,
                                        IF((`A`.`DATE_OF_BIDDING` IS NOT NULL),
                                            IF((`A`.`CANCEL_BIDDING` = TRUE),
                                                207,
                                                IF((`A`.`REJECT_BIDDING` = TRUE),
                                                    231,
                                                    IF((`B`.`BIDDING_END_AT` <= NOW()),
                                                        IF((`A`.`SELECTED` IS NOT NULL),
                                                            IF((`B`.`SELECTED` = `A`.`ID`),
                                                                IF((`A`.`MAKE_DECISION` IS NOT NULL),
                                                                    IF((`A`.`MAKE_DECISION` = TRUE),
                                                                        IF((`A`.`MAX_DECISION_AT` <= NOW()),
                                                                            IF((`B`.`CLOSE_AT` > NOW()), 212, 218),
                                                                            220),
                                                                        210),
                                                                    IF((`B`.`MAX_SELECT2_AT` <= NOW()),
                                                                        210,
                                                                        236)),
                                                                IF((`B`.`SECOND_PLACE` = `A`.`ID`),
                                                                    IF((`B`.`MAX_SELECT2_AT` <= NOW()),
                                                                        213,
                                                                        233),
                                                                    213)),
                                                            IF((`B`.`MAX_SELECT2_AT` <= NOW()),
                                                                213,
                                                                IF((`A`.`BIDDING_RANK` = 1),
                                                                    208,
                                                                    IF((`A`.`BIDDING_RANK` = 2), 233, 213)))),
                                                        206))),
                                            IF((`B`.`BIDDING_END_AT` <= NOW()),
                                                211,
                                                224)))),
                                203),
                            IF((`B`.`VISIT_END_AT` <= NOW()),
                                230,
                                222))),
                    IF((`B`.`VISIT_END_AT` <= NOW()),
                        203,
                        204)),
                IF((`A`.`DATE_OF_BIDDING` IS NOT NULL),
                    IF((`A`.`CANCEL_BIDDING` = TRUE),
                        207,
                        IF((`A`.`REJECT_BIDDING` = TRUE),
                            231,
                            IF((`B`.`BIDDING_END_AT` <= NOW()),
                                IF((`A`.`SELECTED` IS NOT NULL),
                                    IF((`B`.`SELECTED` = `A`.`ID`),
                                        IF((`A`.`MAKE_DECISION` IS NOT NULL),
                                            IF((`A`.`MAKE_DECISION` = TRUE),
                                                IF((`A`.`MAX_DECISION_AT` <= NOW()),
                                                    IF((`B`.`CLOSE_AT` > NOW()), 212, 218),
                                                    220),
                                                210),
                                            IF((`B`.`MAX_SELECT2_AT` <= NOW()),
                                                210,
                                                236)),
                                        IF((`B`.`SECOND_PLACE` = `A`.`ID`),
                                            IF((`B`.`MAX_SELECT2_AT` <= NOW()),
                                                213,
                                                233),
                                            213)),
                                    IF((`B`.`MAX_SELECT2_AT` <= NOW()),
                                        213,
                                        IF((`A`.`BIDDING_RANK` = 1),
                                            208,
                                            IF((`A`.`BIDDING_RANK` = 2), 233, 213)))),
                                206))),
                    IF((`B`.`BIDDING_END_AT` <= NOW()),
                        211,
                        224)))) AS `STATE_CODE`
    FROM
        ((((((`chiumdev_2`.`COLLECTOR_BIDDING` `A`
        LEFT JOIN `chiumdev_2`.`SITE_WSTE_DISPOSAL_ORDER` `B` ON ((`A`.`DISPOSAL_ORDER_ID` = `B`.`ID`)))
        LEFT JOIN `chiumdev_2`.`COMP_SITE` `D` ON ((`A`.`COLLECTOR_ID` = `D`.`ID`)))
        LEFT JOIN `chiumdev_2`.`COMP_SITE` `E` ON ((`B`.`SITE_ID` = `E`.`ID`)))
        LEFT JOIN `chiumdev_2`.`KIKCD_B` `F` ON ((`D`.`KIKCD_B_CODE` = `F`.`B_CODE`)))
        LEFT JOIN `chiumdev_2`.`KIKCD_B` `G` ON ((`B`.`KIKCD_B_CODE` = `G`.`B_CODE`)))
        LEFT JOIN `chiumdev_2`.`WSTE_TRMT_BIZ` `H` ON ((`D`.`TRMT_BIZ_CODE` = `H`.`CODE`)))