CREATE 
    ALGORITHM = UNDEFINED 
    DEFINER = `chiumdb`@`%` 
    SQL SECURITY DEFINER
VIEW `chiumdev_2`.`V_ORDER_STATE` AS
    SELECT 
        `A`.`ID` AS `DISPOSER_ORDER_ID`,
        IF((`A`.`COLLECTOR_ID` IS NULL),
            IF((`A`.`IS_DELETED` = TRUE),
                106,
                IF((`A`.`VISIT_END_AT` IS NOT NULL),
                    IF((`A`.`VISIT_START_AT` IS NOT NULL),
                        IF((`A`.`VISIT_START_AT` <= NOW()),
                            IF((`A`.`VISIT_END_AT` <= NOW()),
                                IF((`A`.`PROSPECTIVE_VISITORS` > 0),
                                    IF((`A`.`BIDDING_END_AT` <= NOW()),
                                        IF((`A`.`BIDDERS` > 0),
                                            IF((`B`.`COLLECT_ASK_END_AT` IS NOT NULL),
                                                IF((`A`.`COLLECTOR_SELECTION_CONFIRMED` IS NOT NULL),
                                                    IF((`A`.`COLLECTOR_SELECTION_CONFIRMED` = TRUE),
                                                        IF((`A`.`CLOSE_AT` <= NOW()), 105, 118),
                                                        IF((`A`.`SECOND_PLACE` IS NOT NULL),
                                                            IF((`A`.`COLLECTOR_SELECTION_CONFIRMED2` IS NOT NULL),
                                                                IF((`A`.`COLLECTOR_SELECTION_CONFIRMED2` = TRUE),
                                                                    IF((`A`.`CLOSE_AT` <= NOW()), 105, 118),
                                                                    121),
                                                                IF((`A`.`COLLECTOR_MAX_DECISION2_AT` <= NOW()),
                                                                    121,
                                                                    119)),
                                                            121)),
                                                    IF((`A`.`COLLECTOR_MAX_DECISION_AT` <= NOW()),
                                                        121,
                                                        119)),
                                                IF((`A`.`MAX_SELECT_AT` <= NOW()),
                                                    115,
                                                    110)),
                                            117),
                                        103),
                                    116),
                                102),
                            101),
                        IF((`A`.`VISIT_END_AT` <= NOW()),
                            IF((`A`.`PROSPECTIVE_VISITORS` > 0),
                                IF((`A`.`BIDDING_END_AT` <= NOW()),
                                    IF((`A`.`BIDDERS` > 0),
                                        IF((`B`.`COLLECT_ASK_END_AT` IS NOT NULL),
                                            IF((`A`.`COLLECTOR_SELECTION_CONFIRMED` IS NOT NULL),
                                                IF((`A`.`COLLECTOR_SELECTION_CONFIRMED` = TRUE),
                                                    IF((`A`.`CLOSE_AT` <= NOW()), 105, 118),
                                                    IF((`A`.`SECOND_PLACE` IS NOT NULL),
                                                        IF((`A`.`COLLECTOR_SELECTION_CONFIRMED2` IS NOT NULL),
                                                            IF((`A`.`COLLECTOR_SELECTION_CONFIRMED2` = TRUE),
                                                                IF((`A`.`CLOSE_AT` <= NOW()), 105, 118),
                                                                121),
                                                            IF((`A`.`COLLECTOR_MAX_DECISION2_AT` <= NOW()),
                                                                121,
                                                                119)),
                                                        121)),
                                                IF((`A`.`COLLECTOR_MAX_DECISION_AT` <= NOW()),
                                                    121,
                                                    119)),
                                            IF((`A`.`MAX_SELECT_AT` <= NOW()),
                                                115,
                                                110)),
                                        117),
                                    103),
                                116),
                            102)),
                    IF((`A`.`BIDDING_END_AT` <= NOW()),
                        IF((`A`.`BIDDERS` > 0),
                            IF((`B`.`COLLECT_ASK_END_AT` IS NOT NULL),
                                IF((`A`.`COLLECTOR_SELECTION_CONFIRMED` IS NOT NULL),
                                    IF((`A`.`COLLECTOR_SELECTION_CONFIRMED` = TRUE),
                                        IF((`A`.`CLOSE_AT` <= NOW()), 105, 118),
                                        IF((`A`.`SECOND_PLACE` IS NOT NULL),
                                            IF((`A`.`COLLECTOR_SELECTION_CONFIRMED2` IS NOT NULL),
                                                IF((`A`.`COLLECTOR_SELECTION_CONFIRMED2` = TRUE),
                                                    IF((`A`.`CLOSE_AT` <= NOW()), 105, 118),
                                                    121),
                                                IF((`A`.`COLLECTOR_MAX_DECISION2_AT` <= NOW()),
                                                    121,
                                                    119)),
                                            121)),
                                    IF((`A`.`COLLECTOR_MAX_DECISION_AT` <= NOW()),
                                        121,
                                        119)),
                                IF((`A`.`MAX_SELECT_AT` <= NOW()),
                                    115,
                                    110)),
                            117),
                        103))),
            IF((`A`.`CLOSE_AT` <= NOW()),
                105,
                IF((`B`.`ACCEPT_ASK_END` IS NOT NULL),
                    IF((`B`.`ACCEPT_ASK_END` = TRUE),
                        118,
                        122),
                    IF((`B`.`MAX_DECISION_AT` <= NOW()),
                        122,
                        104)))) AS `STATE_CODE`
    FROM
        (`chiumdev_2`.`SITE_WSTE_DISPOSAL_ORDER` `A`
        LEFT JOIN `chiumdev_2`.`WSTE_CLCT_TRMT_TRANSACTION` `B` ON ((`A`.`ID` = `B`.`DISPOSAL_ORDER_ID`)))