CREATE 
    ALGORITHM = UNDEFINED 
    DEFINER = `chiumdb`@`%` 
    SQL SECURITY DEFINER
VIEW `chiumdev_2`.`V_WSTE_CLCT_TRMT_TRANSACTION` AS
    SELECT 
        `A`.`ID` AS `TRANSACTION_ID`,
        `A`.`DISPOSAL_ORDER_ID` AS `DISPOSER_ORDER_ID`,
        `A`.`COLLECTOR_BIDDING_ID` AS `COLLECTOR_BIDDING_ID`,
        `E`.`COLLECTOR_ID` AS `COLLECTOR_SITE_ID`,
        `F`.`SITE_NAME` AS `COLLECTOR_SITE_NAME`,
        `H`.`SI_DO` AS `DISPOSER_SI_DO`,
        `H`.`SI_GUN_GU` AS `DISPOSER_SI_GUN_GU`,
        `H`.`EUP_MYEON_DONG` AS `DISPOSER_EUP_MYEON_DONG`,
        `H`.`DONG_RI` AS `DISPOSER_DONG_RI`,
        `G`.`ADDR` AS `DISPOSER_ADDR`,
        `G`.`KIKCD_B_CODE` AS `DISPOSER_KIKCD_B_CODE`,
        `G`.`COLLECTOR_ID` AS `DISPOSER_ORDER_COLLECTOR_ID`,
        `G`.`OPEN_AT` AS `DISPOSER_OPEN_AT`,
        `G`.`CLOSE_AT` AS `DISPOSER_CLOSE_AT`,
        `G`.`ORDER_CODE` AS `DISPOSER_ORDER_CODE`,
        `A`.`ASKER_ID` AS `ASKER_ID`,
        `G`.`SITE_ID` AS `DISPOSER_SITE_ID`,
        `I`.`SITE_NAME` AS `DISPOSER_SITE_NM`,
        `A`.`COLLECT_ASK_END_AT` AS `COLLECT_ASK_END_AT`,
        `A`.`COLLECTING_TRUCK_ID` AS `COLLECTING_TRUCK_ID`,
        `A`.`TRUCK_DRIVER_ID` AS `TRUCK_DRIVER_ID`,
        `A`.`TRUCK_START_AT` AS `TRUCK_START_AT`,
        `A`.`COLLECT_END_AT` AS `COLLECT_END_AT`,
        `A`.`WSTE_CODE` AS `WSTE_CODE`,
        `B`.`WSTE_CLASS` AS `WSTE_CLASS`,
        `B`.`NAME` AS `WSTE_NM`,
        `A`.`WSTE_QUANTITY` AS `WSTE_QUANTITY`,
        `A`.`WSTE_UNIT` AS `WSTE_UNIT`,
        `A`.`PRICE_UNIT` AS `PRICE_UNIT`,
        `A`.`TRMT_METHOD_CODE` AS `TRMT_METHOD_CODE`,
        `D`.`NAME` AS `TRMT_METHOD_NM`,
        `A`.`CONTRACT_ID` AS `CONTRACT_ID`,
        `A`.`CONFIRMER_ID` AS `CONFIRMER_ID`,
        `A`.`CONFIRMED_AT` AS `CONFIRMED_AT`,
        `A`.`DATE_OF_VISIT` AS `DATE_OF_VISIT`,
        `A`.`VISIT_START_AT` AS `VISIT_START_AT`,
        `A`.`VISIT_END_AT` AS `VISIT_END_AT`,
        `A`.`CREATED_AT` AS `CREATED_AT`,
        `A`.`UPDATED_AT` AS `UPDATED_AT`,
        IF((`G`.`CLOSE_AT` < NOW()),
            211,
            IF((`A`.`VISIT_END_AT` IS NOT NULL),
                IF((`A`.`VISIT_START_AT` IS NOT NULL),
                    IF((`A`.`VISIT_START_AT` > NOW()),
                        217,
                        IF((`A`.`VISIT_END_AT` > NOW()),
                            201,
                            IF((`A`.`TRUCK_START_AT` IS NULL),
                                220,
                                IF((`A`.`COLLECT_END_AT` IS NULL),
                                    212,
                                    IF((`A`.`COLLECTOR_REPORTED` IS NULL),
                                        221,
                                        IF((`A`.`CONFIRMED_AT` IS NULL),
                                            242,
                                            243)))))),
                    IF((`A`.`VISIT_END_AT` > NOW()),
                        201,
                        IF((`A`.`TRUCK_START_AT` IS NULL),
                            220,
                            IF((`A`.`COLLECT_END_AT` IS NULL),
                                212,
                                IF((`A`.`COLLECTOR_REPORTED` IS NULL),
                                    221,
                                    IF((`A`.`CONFIRMED_AT` IS NULL),
                                        242,
                                        243)))))),
                IF((`A`.`TRUCK_START_AT` IS NULL),
                    220,
                    IF((`A`.`COLLECT_END_AT` IS NULL),
                        212,
                        IF((`A`.`COLLECTOR_REPORTED` IS NULL),
                            221,
                            IF((`A`.`CONFIRMED_AT` IS NULL),
                                242,
                                243)))))) AS `TRANSACTION_STATE_CODE`
    FROM
        ((((((((`chiumdev_2`.`WSTE_CLCT_TRMT_TRANSACTION` `A`
        LEFT JOIN `chiumdev_2`.`WSTE_CODE` `B` ON ((`A`.`WSTE_CODE` = `B`.`CODE`)))
        LEFT JOIN `chiumdev_2`.`V_USERS` `C` ON ((`A`.`ASKER_ID` = `chiumdev_2`.`C`.`ID`)))
        LEFT JOIN `chiumdev_2`.`WSTE_TRMT_METHOD` `D` ON ((`A`.`TRMT_METHOD_CODE` = `D`.`CODE`)))
        LEFT JOIN `chiumdev_2`.`COLLECTOR_BIDDING` `E` ON ((`A`.`COLLECTOR_BIDDING_ID` = `E`.`ID`)))
        LEFT JOIN `chiumdev_2`.`COMP_SITE` `F` ON ((`E`.`COLLECTOR_ID` = `F`.`ID`)))
        LEFT JOIN `chiumdev_2`.`SITE_WSTE_DISPOSAL_ORDER` `G` ON ((`A`.`DISPOSAL_ORDER_ID` = `G`.`ID`)))
        LEFT JOIN `chiumdev_2`.`KIKCD_B` `H` ON ((`G`.`KIKCD_B_CODE` = `H`.`B_CODE`)))
        LEFT JOIN `chiumdev_2`.`COMP_SITE` `I` ON ((`G`.`SITE_ID` = `I`.`ID`)))