CREATE 
    ALGORITHM = UNDEFINED 
    DEFINER = `chiumdb`@`%` 
    SQL SECURITY DEFINER
VIEW `chiumdev_2`.`V_WSTE_LIST_DISCHARGED` AS
    SELECT 
        `A`.`ID` AS `WSTE_LIST_DISCHARGED_ID`,
        `A`.`WSTE_CLCT_TRMT_TRANSACTION_ID` AS `WSTE_CLCT_TRMT_TRANSACTION_ID`,
        `A`.`WSTE_CODE` AS `WSTE_CODE`,
        `B`.`NAME` AS `WSTE_NM`,
        `A`.`WSTE_QUANTITY` AS `WSTE_QUANTITY`,
        `A`.`WSTE_UNIT` AS `WSTE_UNIT`,
        `A`.`WSTE_UNIT_PRICE` AS `WSTE_UNIT_PRICE`,
        `A`.`WSTE_DISCHARGED_AT` AS `WSTE_DISCHARGED_AT`,
        `A`.`CREATED_AT` AS `CREATED_AT`,
        `A`.`UPDATED_AT` AS `UPDATED_AT`,
        `A`.`WSTE_TRMT_METHOD` AS `WSTE_TRMT_METHOD`,
        `A`.`WSTE_APPEARANCE` AS `WSTE_APPEARANCE`,
        `D`.`KOREAN` AS `WSTE_APPEARANCE_NM_KO`,
        `C`.`NAME` AS `WSTE_TRMT_METHOD_NM`
    FROM
        (((`chiumdev_2`.`WSTE_LIST_DISCHARGED` `A`
        LEFT JOIN `chiumdev_2`.`WSTE_CODE` `B` ON ((`A`.`WSTE_CODE` = `B`.`CODE`)))
        LEFT JOIN `chiumdev_2`.`WSTE_TRMT_METHOD` `C` ON ((`A`.`WSTE_TRMT_METHOD` = `C`.`CODE`)))
        LEFT JOIN `chiumdev_2`.`WSTE_APPEARANCE` `D` ON ((`A`.`WSTE_APPEARANCE` = `D`.`ID`)))