USE chium;

CREATE TABLE `WSTE_PHYSICAL_COMPOSITION` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `CATEGORY` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'WSTE_CODE의 CODE참조하며 사업장인 경우 51, 생활폐기물인 경우에는 91로 처리하며 지정폐기물은 사업장 폐기물 영역에 포함됨',
  `CODE` int DEFAULT NULL COMMENT '카테고리별 연번',
  `NAME` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '폐기물의 물리적 조성 구분 이름',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='폐기물의 물리적 조성 분류표(폐기물의 소각시 적용됨)';

CREATE TABLE `WSTE_PHYSICAL_COMPOSITION_MATCH` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `WSTE_CODE` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '폐기물 분류코드(WSTE_CODE.CODE)',
  `PHYSICAL_COMPOSITION` int DEFAULT NULL COMMENT '폐기물의 물리적 조성 분류코드(WSTE_PHYSICAL_COMPOSITION.ID)',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='폐기물 분류코드별 폐기물의 물리적 조성 분류표';


INSERT INTO WSTE_PHYSICAL_COMPOSITION(CATEGORY, CODE, NAME) VALUES('51', 1, '음식물');
INSERT INTO WSTE_PHYSICAL_COMPOSITION(CATEGORY, CODE, NAME) VALUES('51', 2, '섬유');
INSERT INTO WSTE_PHYSICAL_COMPOSITION(CATEGORY, CODE, NAME) VALUES('51', 3, '폐목재');
INSERT INTO WSTE_PHYSICAL_COMPOSITION(CATEGORY, CODE, NAME) VALUES('51', 4, '제지');
INSERT INTO WSTE_PHYSICAL_COMPOSITION(CATEGORY, CODE, NAME) VALUES('51', 5, '석유제품');
INSERT INTO WSTE_PHYSICAL_COMPOSITION(CATEGORY, CODE, NAME) VALUES('51', 6, '고무');
INSERT INTO WSTE_PHYSICAL_COMPOSITION(CATEGORY, CODE, NAME) VALUES('51', 7, '건설폐기물');
INSERT INTO WSTE_PHYSICAL_COMPOSITION(CATEGORY, CODE, NAME) VALUES('51', 8, '하수슬러지');
INSERT INTO WSTE_PHYSICAL_COMPOSITION(CATEGORY, CODE, NAME) VALUES('51', 9, '폐수슬러지');
INSERT INTO WSTE_PHYSICAL_COMPOSITION(CATEGORY, CODE, NAME) VALUES('51', 10, '병원성폐기물');
INSERT INTO WSTE_PHYSICAL_COMPOSITION(CATEGORY, CODE, NAME) VALUES('51', 11, '폐피혁');
INSERT INTO WSTE_PHYSICAL_COMPOSITION(CATEGORY, CODE, NAME) VALUES('51', 12, '기타');
INSERT INTO WSTE_PHYSICAL_COMPOSITION(CATEGORY, CODE, NAME) VALUES('51', 13, '액상폐기물');
INSERT INTO WSTE_PHYSICAL_COMPOSITION(CATEGORY, CODE, NAME) VALUES('91', 1, '음식물');
INSERT INTO WSTE_PHYSICAL_COMPOSITION(CATEGORY, CODE, NAME) VALUES('91', 2, '섬유');
INSERT INTO WSTE_PHYSICAL_COMPOSITION(CATEGORY, CODE, NAME) VALUES('91', 3, '나무류');
INSERT INTO WSTE_PHYSICAL_COMPOSITION(CATEGORY, CODE, NAME) VALUES('91', 4, '종이류');
INSERT INTO WSTE_PHYSICAL_COMPOSITION(CATEGORY, CODE, NAME) VALUES('91', 5, '고무/가죽');
INSERT INTO WSTE_PHYSICAL_COMPOSITION(CATEGORY, CODE, NAME) VALUES('91', 6, '플라스틱류');
INSERT INTO WSTE_PHYSICAL_COMPOSITION(CATEGORY, CODE, NAME) VALUES('91', 7, '금속');
INSERT INTO WSTE_PHYSICAL_COMPOSITION(CATEGORY, CODE, NAME) VALUES('91', 8, '유리');
INSERT INTO WSTE_PHYSICAL_COMPOSITION(CATEGORY, CODE, NAME) VALUES('91', 9, '정원/공원폐기물');
INSERT INTO WSTE_PHYSICAL_COMPOSITION(CATEGORY, CODE, NAME) VALUES('91', 10, '기저귀');
INSERT INTO WSTE_PHYSICAL_COMPOSITION(CATEGORY, CODE, NAME) VALUES('91', 11, '기타');

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('01-01-01', 5);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('01-01-02', 5);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('01-01-03', 5);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('01-01-04', 5);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('01-01-05', 5);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('01-01-06', 5);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('01-01-07', 5);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('01-01-08', 5);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('01-01-09', 5);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('01-01-99', 5);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('01-02-01', 9);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('01-02-02', 9);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('01-02-03', 9);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('01-02-04', 9);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('01-02-05', 9);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('01-02-99', 9);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('01-03-01', 13);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('01-03-02', 13);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('01-03-03', 13);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('01-03-99', 13);


INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('02-01-01', 13);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('02-01-02', 13);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('02-01-03', 13);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('02-01-04', 13);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('02-01-05', 13);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('02-01-06', 13);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('02-01-99', 13);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('02-02-01', 13);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('02-02-02', 13);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('02-02-03', 13);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('02-02-04', 13);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('02-02-99', 13);


INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('03-01-01', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('03-01-02', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('03-01-03', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('03-01-04', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('03-01-99', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('03-02-00', 12);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('03-03-01', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('03-03-02', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('03-03-03', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('03-03-99', 12);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('03-04-01', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('03-04-02', 12);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('03-05-01', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('03-05-02', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('03-05-03', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('03-05-04', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('03-05-05', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('03-05-06', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('03-05-07', 12);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('03-06-01', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('03-06-02', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('03-06-03', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('03-06-04', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('03-06-05', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('03-06-99', 12);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('03-07-01', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('03-07-02', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('03-08', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('03-08-01', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('03-08-02', 12);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('04-01-00', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('04-02-00', 12);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('05-01-00', 13);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('05-02-00', 13);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('05-03-00', 13);


INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('06-01-01', 13);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('06-01-02', 13);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('06-01-03', 13);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('06-01-04', 13);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('06-01-05', 13);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('06-01-06', 13);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('06-01-07', 13);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('06-01-99', 13);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('06-02-00', 13);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('06-03-00', 13);


INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('07-01-01', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('07-01-02', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('07-02-00', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('07-03-00', 12);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('08-01-00', 13);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('08-02-00', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('08-03-00', 13);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('08-04-00', 12);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('09-01-00', 13);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('09-02-00', 13);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('09-03-00', 13);


INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('10-11-00', 10);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('10-12-01', 10);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('10-12-02', 10);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('10-12-03', 10);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('10-12-04', 10);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('10-12-05', 10);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('10-12-06', 10);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('10-13-00', 10);


INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('11-01-01', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('11-01-02', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('11-01-03', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('11-01-99', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('11-02-00', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('11-03-00', 12);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('30-00-00', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('40-01-01', 7);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('40-01-02', 7);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('40-01-03', 7);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('40-01-04', 7);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('40-01-05', 7);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('40-02-06', 7);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('40-02-07', 7);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('40-02-08', 7);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('40-02-09', 7);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('40-03-10', 7);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('40-03-11', 7);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('40-03-12', 7);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('40-04-10', 7);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('40-04-11', 7);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('40-04-12', 7);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('40-04-13', 7);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('40-04-14', 7);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('40-90-90', 7);


INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-01-01', 8);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-01-02', 8);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-01-03', 8);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-01-04', 8);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-01-05', 9);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-01-06', 9);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-01-07', 9);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-01-08', 9);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-01-99', 8);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-02-01', 9);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-02-02', 8);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-02-03', 8);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-02-04', 8);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-02-05', 8);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-02-06', 9);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-02-07', 9);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-02-08', 9);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-02-09', 8);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-02-10', 9);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-02-11', 9);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-02-19', 9);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-02-99', 9);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-03-01', 5);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-03-02', 5);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-03-03', 5);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-03-04', 5);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-03-05', 5);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-03-06', 5);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-03-07', 5);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-03-08', 5);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-03-99', 5);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-04-01', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-04-02', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-04-03', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-04-04', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-04-99', 12);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-05-01', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-05-02', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-05-03', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-05-04', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-05-99', 12);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-06-01', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-06-02', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-06-03', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-06-04', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-06-99', 12);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-07-01', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-07-02', 12);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-08-01', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-08-02', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-08-03', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-08-04', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-08-05', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-08-06', 12);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-09-01', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-09-02', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-09-03', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-09-04', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-09-99', 12);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-10-01', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-10-02', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-10-03', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-10-99', 12);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-11-01', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-11-02', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-11-03', 12);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-12-01', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-12-02', 12);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-13-01', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-13-02', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-13-03', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-13-99', 12);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-14-01', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-14-02', 12);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-15-01', 5);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-15-02', 5);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-16-00', 13);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-17-01', 10);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-17-02', 10);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-17-03', 10);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-17-04', 10);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-17-05', 10);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-17-06', 10);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-17-07', 10);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-17-08', 10);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-17-19', 10);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-17-21', 10);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-17-22', 10);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-17-23', 10);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-17-24', 10);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-17-29', 10);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-17-99', 10);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-18-01', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-18-02', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-18-03', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-18-99', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-19-00', 12);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-20-01', 3);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-20-02', 3);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-20-03', 3);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-20-04', 3);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-20-05', 3);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-20-06', 3);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-20-07', 3);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-20-08', 3);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-20-09', 3);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-20-10', 3);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-20-11', 3);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-20-12', 3);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-20-13', 3);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-20-99', 3);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-21-01', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-21-02', 7);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-21-03', 7);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-22-01', 7);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-22-02', 3);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-23-00', 7);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-24-00', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-25-00', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-26-00', 12);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-27-01', 2);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-27-02', 2);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-27-03', 2);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-27-99', 2);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-28-01', 4);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-28-02', 4);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-28-03', 4);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-29-01', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-29-02', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-29-03', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-29-04', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-29-99', 12);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-30-01', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-30-02', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-30-03', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-30-04', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-30-05', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-30-99', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-31-00', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-32-00', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-33-00', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-35-00', 12);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-36-01', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-36-02', 12);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-37-01', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-37-02', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-37-03', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-37-99', 12);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-38-01', 1);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-38-02', 1);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-38-03', 1);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-38-99', 1);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-39-00', 1);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-40-01', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-40-99', 12);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-41-01', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-41-02', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-41-03', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-41-04', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-41-05', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-42-00', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-43-00', 12);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-44-00', 12);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-45-01', 7);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-45-02', 7);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-45-99', 7);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-46-00', 10);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('51-99-00', 12);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('91-01-00', 24);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('91-02-00', 14);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('91-03-00', 24);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('91-04-00', 17);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('91-05-00', 20);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('91-06-01', 19);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('91-06-02', 19);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('91-06-03', 18);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('91-07-01', 24);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('91-07-02', 24);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('91-08-00', 15);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('91-09-00', 24);

INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('91-10-01', 16);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('91-10-02', 16);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('91-10-03', 16);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('91-11-00', 24);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('91-12-00', 24);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('91-13-00', 24);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('91-14-00', 20);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('91-15-00', 24);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('91-16-00', 24);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('91-17-00', 24);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('91-18-01', 24);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('91-18-02', 24);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('91-19-00', 24);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('91-20-00', 24);
INSERT INTO WSTE_PHYSICAL_COMPOSITION_MATCH(WSTE_CODE, PHYSICAL_COMPOSITION) VALUES('91-99-00', 24);