CREATE TABLE `BUSINESS_AREA` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `SITE_ID` bigint DEFAULT NULL,
  `KIKCD_B_CODE` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `IS_DEFAULT` tinyint DEFAULT NULL,
  `CREATED_AT` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='사이트별 영업지역 시군구 관리 테이블';
