CREATE TABLE `COMP_WSTE_TRMT_METHOD_MATCH` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `COMP_ID` bigint DEFAULT NULL,
  `WSTE_TRMT_METHOD_CODE` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=10174 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
