CREATE TABLE `SITE_WSTE_TRMT_FCTL_MATCH` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `SITE_ID` int DEFAULT NULL,
  `WSTE_TRMT_FCTL_CODE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=868 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
