CREATE TABLE `SITE_WSTE_CLS_MATCH` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `SITE_ID` int DEFAULT NULL,
  `WSTE_CLS_CODE` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'WSTE_CODE.CODE',
  `WSTE_APPEARANCE` int DEFAULT NULL COMMENT '폐기물 성상(WSTE_APPEARANCE.ID)',
  `CREATED_AT` datetime DEFAULT NULL,
  `UPDATED_AT` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9011 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='수집업자등의 관리영업대상 폐기물 종류';
