CREATE TABLE `SITE_WSTE_DISPOSAL_ORDER` (
  `ID` bigint NOT NULL AUTO_INCREMENT COMMENT 'AUTO INCREMENT NUMBER로서 SITE의 고유등록번호로 사용됨',
  `DISPOSER_ID` bigint NOT NULL COMMENT '배출자 고유등록번호(USERS.ID)',
  `COLLECTOR_ID` bigint DEFAULT NULL COMMENT '기존 거래인 경우에는 COLLECTOR_ID가 NULL값이 아니고 다른 업체들의 입찰이 안됨.\n신규거래인 경우에는 NULL이며 다른 업체들의 입찰이 가능함',
  `DISPOSER_TYPE` enum('person','company') COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '배출자의 타입(person:개인, company:사업자(를 포함한 개인이 아닌 자))으로서 개인인 경우에는 USERS.ID, 사업자인 경우에는 COMPANY.ID를 참조함',
  `SITE_ID` bigint DEFAULT NULL COMMENT '배출자 고유등록번호(COMP_SITE.ID)',
  `ACTIVE` tinyint NOT NULL DEFAULT '1' COMMENT '활성화(배출이 진행되고 있는 경우와 같은)된 배출지인 경우에는 1, 그렇지 않은 경우(배출이 일시중단 되는 등의 배출 활동이 일어나지 않는 경우)에는 0\n',
  `ORDER_CODE` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `MANAGER_ID` bigint DEFAULT NULL COMMENT '배출지 관리자 아이디로서 개인인 경우에는 배출자 아이디와 동일하게 사용하고 사업자인 경우에는 사업자의 관리자(해당사업자의 201권한을 가진 관리자가 기본 관리자로 등록됨) 아이디를 사용한다.',
  `VISIT_START_AT` datetime DEFAULT NULL,
  `VISIT_END_AT` datetime DEFAULT NULL COMMENT '사이트 방문 종료일로서 WHETHER_TO_VISIT의 값이 TRUE이면 입력날짜가 의미가 있으며 FALSE이면 NULL로 셋팅함',
  `BIDDING_END_AT` datetime DEFAULT NULL COMMENT '입찰종료일',
  `OPEN_AT` datetime DEFAULT NULL COMMENT '배출시작일',
  `CLOSE_AT` datetime DEFAULT NULL COMMENT '배출종료일',
  `SERVICE_INSTRUCTION_ID` int DEFAULT NULL COMMENT '용역지시서 아이디(SERVICE_INSTRUCTION.ID) 참조',
  `KIKCD_B_CODE` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '폐기물 배출주소지의 법정동 코드(KIKCD_B.B_CODE)',
  `ADDR` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '폐기물 배출지의 상세주소',
  `NOTE` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '요청사항',
  `LAT` decimal(12,9) DEFAULT NULL,
  `LNG` decimal(12,9) DEFAULT NULL,
  `VISIT_EARLY_CLOSING` tinyint DEFAULT '0' COMMENT '배출자가 방문일정을 조기마감 하게 되면 TRUE로 셋팅되면서 VISIT_EARLY_CLOSED_AT에 조기마감시간이 현재시간으로 입력된다.',
  `BIDDING_EARLY_CLOSING` tinyint DEFAULT '0' COMMENT '배출자가 입찰일정을 조기마감 하게 되면 TRUE로 셋팅되면서 BIDDING_EARLY_CLOSED_AT에 조기마감시간이 현재시간으로 입력된다.',
  `IS_DELETED` tinyint DEFAULT '0' COMMENT '배출자가 삭제한 경우 TRUE',
  `SELECTED` bigint DEFAULT '0' COMMENT '배출자가 수거자를 선정하게되면 선정된 COLLECTOR_BIDDING.ID를 기록하고 이후 수거자의 확인(COLLECTOR_SELECTION_CONFIRMED=TRUE)이 완성되면 기존거래가 된다.',
  `SELECTED_AT` datetime DEFAULT NULL COMMENT '배출자가 수거자를 선정할 일시',
  `COLLECTOR_SELECTION_CONFIRMED` tinyint DEFAULT '0' COMMENT '배출자가 선정한 수거자가 승인을 하게 되면 TRUE, 이후 기존거래로 상태가 변경됨',
  `COLLECTOR_SELECTION_CONFIRMED_AT` datetime DEFAULT NULL COMMENT '배출자가 선정한 수거자가 승인한 일시',
  `VISIT_EARLY_CLOSED_AT` datetime DEFAULT NULL COMMENT '배출자의 방문조기마감을 결정한 일시',
  `BIDDING_EARLY_CLOSED_AT` datetime DEFAULT NULL COMMENT '배출자의 입찰조기마감을 결정한 일시',
  `DELETED_AT` datetime DEFAULT NULL COMMENT '배출자가 배출신청을 삭제한 일시',
  `CREATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '배출지 생성일자',
  `UPDATED_AT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '배출지 정보 변경일자',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=150 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='폐기물 배출지 테이블에 수거자등의 아이디가 등록하지 않는다. 하나의 배출지는 다수의 수거자 등에 의해 폐기물이 처리될 수 있기 때문에 WSTE_DISPOSAL_COLLECTOR_MATCH 테이블에서 배출지와 수거자등에 대한 정보는 SITE 1 : COLLECTOR N의 관계가 성립된다.';
