CREATE TABLE `STATUS_HISTORY` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `DISPOSAL_ORDER_ID` bigint DEFAULT NULL COMMENT 'SITE_WSTE_DISPOSAL_ORDER.ID',
  `COLLECTOR_ID` bigint DEFAULT NULL COMMENT 'COMP_SITE.ID',
  `STATUS_CODE` int DEFAULT NULL,
  `CREATED_AT` datetime DEFAULT NULL,
  `UPDATED_AT` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='거래기본정보 등록(배출자 및 수거자 메인 디스플레이 용도로 사용)';
