CREATE TABLE `TRIGGER_TABLE` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `TABLE_NM` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `EVENT` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CREATED_AT` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2018 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
