CREATE TABLE `USERS_CLASS` (
  `ID` int NOT NULL,
  `CLASS_NM` varchar(45) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
