CREATE TABLE `USERS` (
  `ID` bigint NOT NULL COMMENT '고유번호로서 등록번호 중 최대값으로 생성하게 됨',
  `USER_ID` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '사용자 아이디',
  `PWD` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '사용자 암호',
  `USER_NAME` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '사용자 이름',
  `PHONE` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '사용자 등록 전화번호',
  `BELONG_TO` bigint NOT NULL DEFAULT '0' COMMENT '구분코드로서 개인은 0임. \\\\\\\\\\\\\\\\n0보다 큰 수는 사업자(사업자 등록시 관리자)의 관리자이므로 사업자 등록시 등록일련번호(ID)를 입력하도록 함. \\\\\\\\\\\\\\\\n사업자 등록시에는 사업자 등록일련번호(ID)를 먼저 생성한 후 생성된 번호(ID)를 DIV에 입력해야 함',
  `AFFILIATED_SITE` bigint DEFAULT NULL,
  `ACTIVE` tinyint NOT NULL DEFAULT '1',
  `CLASS` int NOT NULL DEFAULT '201',
  `JWT` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FCM` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `DEPARTMENT` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CS_MANAGER_ID` bigint DEFAULT NULL,
  `CONFIRMED` tinyint DEFAULT NULL,
  `CONFIRMED_AT` datetime DEFAULT NULL,
  `CREATED_AT` datetime DEFAULT NULL,
  `UPDATED_AT` datetime DEFAULT NULL,
  `RECOVERY_TAG` datetime DEFAULT NULL,
  `SOCIAL_NO` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `AGREEMENT_TERMS` tinyint DEFAULT NULL,
  `USER_CURRENT_TYPE` int DEFAULT NULL COMMENT '사용자의 상태(USER_TYPE.ID)로서 1:시스템, 2:배출자, 3:수거자',
  PRIMARY KEY (`PHONE`,`BELONG_TO`,`ACTIVE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
