CREATE TABLE `WSTE_CLCT_TRMT_CONTRACT` (
  `ID` bigint NOT NULL AUTO_INCREMENT COMMENT '고유등록번호 AUTO_INCREMENT',
  `SITE_WSTE_REG_ID` bigint DEFAULT NULL COMMENT '배출자가 등록한 폐기물배출정보의 고유등록번호(SITE_WSTE_REGISTRATION.ID)',
  `ACTIVE` tinyint DEFAULT NULL,
  `CONTRACT_BEGINS_AT` datetime DEFAULT NULL COMMENT '계약체결일',
  `CONTRACT_ENDS_AT` datetime DEFAULT NULL COMMENT '계약종료일',
  `CREATED_AT` datetime DEFAULT NULL COMMENT '데이타 최조 생성일',
  `UPDATED_AT` datetime DEFAULT NULL COMMENT '데이타 최종 변경일',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='폐기물 수집 및 처리 용역 계약 관리 테이블';
