CREATE TABLE `WSTE_LIST_DISCHARGED` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `WSTE_CLCT_TRMT_TRANSACTION_ID` bigint DEFAULT NULL COMMENT '배출자 처리요청 등록번호(WSTE_CLCT_TRMT_TRANSACTION.ID)',
  `WSTE_CODE` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '폐기물코드(WSTE_CODE.CODE)',
  `WSTE_QUANTITY` float DEFAULT NULL COMMENT '폐기물처리수량',
  `WSTE_UNIT` enum('kg','m3') COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '폐기물처리단위',
  `WSTE_UNIT_PRICE` float DEFAULT NULL COMMENT '폐기물처리단가',
  `WSTE_DISCHARGED_AT` datetime DEFAULT NULL COMMENT '폐기물처리일자',
  `WSTE_TRMT_METHOD` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '폐기물처리방법(WSTE_TRMT_METHOD.CODE)',
  `WSTE_APPEARANCE` int DEFAULT NULL,
  `CREATED_AT` datetime DEFAULT NULL COMMENT '레코드 최초생성일시',
  `UPDATED_AT` datetime DEFAULT NULL COMMENT '레코드 최종변경일시',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='처리중인 폐기물 리스트';
