CREATE TABLE `WSTE_COMP_MATCH` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `COMP_ID` int DEFAULT NULL,
  `WSTE_CODE` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `WSTE_CLS` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=38207 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
