CREATE TABLE `WSTE_CLCT_TRMT_TRANSACTION` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `DISPOSAL_ORDER_ID` bigint DEFAULT NULL COMMENT 'SITE_WSTE_DISPOSAL_ORDER.ID',
  `COLLECTOR_BIDDING_ID` bigint DEFAULT NULL COMMENT 'COLLECTOR_BIDDING.ID',
  `ASKER_ID` bigint DEFAULT NULL COMMENT '폐기물 처리 요청을 한 사이트의 관리자(USERS.ID)',
  `COLLECT_ASK_END_AT` datetime DEFAULT NULL COMMENT '폐기물배출요청 완료일(폐기물 배출자가 지정한 폐기물 배출완료일)',
  `COLLECTING_TRUCK_ID` bigint DEFAULT NULL COMMENT '폐기물 수거차량 등록번호(COLLECT_TRUCKS.ID)',
  `TRUCK_DRIVER_ID` bigint DEFAULT NULL COMMENT '트럭운전자 고유등록번호(CLASS:209)(USERS.ID)',
  `TRUCK_START_AT` datetime DEFAULT NULL,
  `COLLECT_END_AT` datetime DEFAULT NULL COMMENT '폐기물 수거 후 처리 완료 일시',
  `WSTE_CODE` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '폐기물코드',
  `WSTE_QUANTITY` float DEFAULT NULL COMMENT '폐기물 처리수량',
  `WSTE_UNIT` enum('kg','m3') COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '폐기물처리단위',
  `PRICE_UNIT` float DEFAULT NULL COMMENT '처리단가',
  `TRMT_METHOD_CODE` varchar(4) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '처리방법코드(WSTE_TRMT_METHOD.CODE)',
  `QCC_IMG_PATH` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'QUANTITY_CHECK_CERTIFICATE(계근증명서) 이미지 업로드 경로',
  `CONTRACT_ID` bigint DEFAULT NULL COMMENT '계약서 고유등록번호(CONTRACT.ID) / 현재는 이 값을 NULL처리함',
  `CONFIRMER_ID` bigint DEFAULT NULL COMMENT '폐기물처리에 대한 완료확인을 한 배출업체의 관리자의 고유등록번호(USERS.ID)',
  `DATE_OF_VISIT` datetime DEFAULT NULL COMMENT '수거자의 방문예정일',
  `VISIT_START_AT` datetime DEFAULT NULL,
  `VISIT_END_AT` datetime DEFAULT NULL COMMENT '배출자의 방문요청일시',
  `CONFIRMED_AT` datetime DEFAULT NULL COMMENT '배출자 관리자의 최종확인 일시(이 값이 NULL인 경우에는 처리중이며 이 값이 NULL이 아닌 경우에는 처리완료 상태임)',
  `CREATED_AT` datetime DEFAULT NULL COMMENT '폐기물 배출 요청일',
  `UPDATED_AT` datetime DEFAULT NULL COMMENT '레코드 최종변경일',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=139 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='폐기물에 대한 낙찰 이후 수거자와 배출자와의 폐기물 처리 결과 정보 관리 테이블. 폐기물계근증명서 및 처리사진은 별도의 테이블에서 관리함\n배출자가 신규입찰을 하는 경우에는 COLLECTOR_BIDDING_ID가 NULL값으로 셋팅(배출자가 레코드 생성)되며 이후 입찰이 완료되어 수거자자가 이 DISPOSAL_ORDER에 대하여 최종 수락할 때 수거자는 NULL값이었던 COLLECTOR_BIDDING_ID를 채워서 레코드를 생성한다.\n또한 배출자가 기존거래업체에게 배출을 의뢰하는 경우(DISPOSAL_ORDER가 종료되지 않은 상황으로서 DISPOSAL_ORDER.CLOSED_AT이 NULL인 경우, 이 경우는 기존 배출이 완료되지 않은 상태의 추가배출의 의미임)에는 COLLECTOR_BIDDING_ID를 배출자가 값을 채워서 레코드를 생성한다.';
