CREATE TABLE `WSTE_TRMT_METHOD` (
  `CODE` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `WSTE_TRMT_CLS_1` int DEFAULT NULL,
  `WSTE_TRMT_CLS_2` int DEFAULT NULL,
  `NAME` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
